import type { BankWoord } from "../woordenbank.ts";

export const algemeneKennis: BankWoord[] = [
  {
    niveau: "basis",
    woord: "anachronisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Iets wat niet past in de tijd waarin het geplaatst wordt, zoals een voorwerp of gewoonte uit een andere periode.",
    voorbeeldzin: "Het polshorloge van de Romeinse soldaat in de film was een opvallend anachronisme.",
    voorbeelden: [
      "In een roman over de middeleeuwen is een personage dat over 'stress' klaagt eigenlijk een anachronisme.",
      "Wie tegenwoordig nog een faxapparaat gebruikt, voelt zich soms een wandelend anachronisme.",
    ],
    herkomst: "Grieks ana (tegen, terug) + chronos (tijd).",
    beeld: "Een ridder in harnas die midden op het slagveld een selfie maakt met zijn smartphone.",
  },
  {
    niveau: "basis",
    woord: "paradox",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een uitspraak of situatie die tegenstrijdig lijkt, maar bij nader inzien toch waar of zinvol kan zijn.",
    voorbeeldzin: "Het is een paradox dat meer keuze mensen soms juist ongelukkiger maakt.",
    voorbeelden: [
      "Hoe meer je over iets weet, hoe beter je beseft wat je niet weet: een bekende paradox.",
      "De paradox van de tolerantie stelt dat een tolerante samenleving intolerantie niet onbeperkt kan toestaan.",
    ],
    herkomst: "Grieks para (tegen) + doxa (mening): tegen de verwachting in.",
    beeld: "Een bordje met de tekst 'Negeer dit bordje', waar iedereen verward naar blijft staren.",
  },
  {
    niveau: "basis",
    woord: "pragmatisch",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Gericht op wat in de praktijk werkt, in plaats van op theorie of principes.",
    voorbeeldzin: "In plaats van eindeloos te vergaderen, koos de directeur voor een pragmatische oplossing.",
    voorbeelden: [
      "Ze is niet principieel tegen thuiswerken, maar kijkt er pragmatisch naar: als het werk af komt, is het goed.",
      "Het kabinet koos een pragmatische aanpak en regelde eerst de meest dringende problemen.",
    ],
    herkomst: "Grieks pragma (handeling, zaak).",
    beeld: "Iemand die een wiebelende tafel niet repareert, maar er gewoon een bierviltje onder schuift.",
  },
  {
    niveau: "basis",
    woord: "euvel",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een gebrek, probleem of kwaal.",
    voorbeeldzin: "De nieuwe versie van de app verhelpt het euvel met de batterij.",
    voorbeelden: [
      "Een veelvoorkomend euvel bij oude huizen is vocht in de kelder.",
      "De monteur wist het euvel binnen tien minuten te verhelpen.",
    ],
    herkomst: "Middelnederlands evel (kwaad), verwant aan het Engelse evil.",
    beeld: "Een klein grijs duiveltje dat in je fietsketting zit te knagen.",
  },
  {
    niveau: "basis",
    woord: "cynisch",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Wantrouwend over de goede bedoelingen van mensen; ervan uitgaand dat iedereen uit eigenbelang handelt.",
    voorbeeldzin: "Na jaren van gebroken beloftes keek ze cynisch naar elke nieuwe verkiezingscampagne.",
    voorbeelden: [
      "'Ze doen het toch alleen voor het geld,' zei hij cynisch.",
      "Door alle schandalen zijn veel kiezers cynisch geworden over de politiek.",
    ],
    herkomst: "Grieks kynikos (hondachtig), naar Oudgriekse filosofen die maatschappelijke normen minachtten.",
    beeld: "Een hond die met opgetrokken wenkbrauw naar een glimlachende verkoper kijkt.",
  },
  {
    niveau: "gevorderd",
    woord: "eufemisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een verzachtende omschrijving voor iets onaangenaams of pijnlijks.",
    voorbeeldzin: "'Heengaan' is een eufemisme voor sterven.",
    voorbeelden: [
      "'Collateral damage' is een eufemisme voor burgerslachtoffers.",
      "Het bedrijf sprak van 'herstructureren', een eufemisme voor het schrappen van honderden banen.",
    ],
    herkomst: "Grieks eu (goed) + phèmi (spreken).",
    beeld: "Een ontslagbrief verpakt in roze cadeaupapier met een strik erom.",
  },
  {
    niveau: "gevorderd",
    woord: "ambivalent",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Tegelijk tegenstrijdige gevoelens of houdingen hebbend tegenover iets.",
    voorbeeldzin: "Ik sta ambivalent tegenover de verhuizing: ik heb er zin in, maar zie er ook tegen op.",
    voorbeelden: [
      "Veel mensen zijn ambivalent over sociale media: ze vinden het handig, maar ook vermoeiend.",
      "Zijn ambivalente houding tegenover het plan maakte het lastig om een besluit te nemen.",
    ],
    herkomst: "Latijn ambo (beide) + valere (waard zijn, gelden).",
    beeld: "Iemand die met één voet in een warm bad en met de andere in een emmer ijswater staat.",
  },
  {
    niveau: "gevorderd",
    woord: "precedent",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een eerder geval dat als voorbeeld of rechtvaardiging dient voor latere beslissingen.",
    voorbeeldzin: "Als we deze uitzondering toestaan, scheppen we een precedent.",
    voorbeelden: [
      "De rechter zocht naar een precedent, maar zo'n zaak was nog nooit voorgekomen.",
      "Zonder precedent in de geschiedenis moest de regering zelf een aanpak bedenken.",
    ],
    herkomst: "Latijn praecedere (voorafgaan).",
    beeld: "Eén schaap springt over een hek, en de hele kudde springt er daarna achteraan.",
  },
  {
    niveau: "gevorderd",
    woord: "dichotomie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een tweedeling in twee scherp tegengestelde delen of groepen.",
    voorbeeldzin: "De dichotomie tussen stad en platteland speelde een grote rol in de verkiezingen.",
    voorbeelden: [
      "Het is een valse dichotomie om te zeggen dat je óf voor economie óf voor natuur bent.",
      "Veel sprookjes draaien om de dichotomie tussen goed en kwaad.",
    ],
    herkomst: "Grieks dicha (in tweeën) + temnein (snijden).",
    beeld: "Een taart die met één messnede in een zwarte en een witte helft wordt verdeeld.",
  },
  {
    niveau: "gevorderd",
    woord: "zeitgeist",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De heersende denkbeelden, smaak en stemming van een bepaalde periode.",
    voorbeeldzin: "De punkmuziek van eind jaren zeventig paste perfect bij de zeitgeist.",
    voorbeelden: [
      "De populariteit van mindfulness zegt veel over de zeitgeist van deze tijd.",
      "Kunstenaars voelen de zeitgeist vaak eerder aan dan politici.",
    ],
    herkomst: "Duits Zeit (tijd) + Geist (geest).",
    beeld: "Een doorzichtige geest in een tijdmachine die bij elk decennium de mode van dat moment aantrekt.",
  },
  {
    niveau: "expert",
    woord: "epistemologie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het deel van de filosofie dat onderzoekt wat kennis is en hoe we iets kunnen weten.",
    voorbeeldzin: "In de epistemologie is de vraag of zintuiglijke waarneming betrouwbaar is een klassiek probleem.",
    voorbeelden: [
      "Wie zich afvraagt hoe we weten of nieuws betrouwbaar is, stelt een vraag uit de epistemologie.",
      "In de epistemologie wordt onderscheid gemaakt tussen geloven en weten.",
    ],
    herkomst: "Grieks epistèmè (kennis) + logos (leer).",
    beeld: "Een filosoof die met een vergrootglas naar zijn eigen hersenen tuurt en zich afvraagt: 'Weet ik dit echt?'",
  },
  {
    niveau: "expert",
    woord: "hermeneutiek",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De leer van het interpreteren en begrijpen van teksten, oorspronkelijk vooral religieuze en juridische teksten.",
    voorbeeldzin: "Wie een grondwetsartikel uitlegt, bedrijft eigenlijk hermeneutiek.",
    voorbeelden: [
      "Theologen gebruiken hermeneutiek om oude teksten in hun historische context te begrijpen.",
      "In de hermeneutiek speelt de vraag wat de schrijver bedoelde een grote rol.",
    ],
    herkomst: "Grieks hermèneuein (uitleggen, vertalen), vaak in verband gebracht met Hermes, de boodschapper van de goden.",
    beeld: "Hermes met gevleugelde sandalen die gebogen zit over een oude perkamentrol om die te ontcijferen.",
  },
  {
    niveau: "expert",
    woord: "teleologisch",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Iets verklarend vanuit het doel waarnaar het streeft, in plaats van vanuit de oorzaak.",
    voorbeeldzin: "'De giraf heeft een lange nek om bij de bladeren te kunnen' is een teleologische verklaring.",
    voorbeelden: [
      "Een teleologische blik op de geschiedenis doet alsof alles onvermijdelijk naar het heden leidde.",
      "Biologen vermijden teleologische taal, omdat evolutie geen doel voor ogen heeft.",
    ],
    herkomst: "Grieks telos (doel, einde) + logos (leer).",
    beeld: "Een pijl die al in de roos steekt en tevreden terugkijkt naar de boog.",
  },
  {
    niveau: "expert",
    woord: "apocrief",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Van twijfelachtige echtheid of herkomst; oorspronkelijk: niet opgenomen in de officiële bijbel.",
    voorbeeldzin: "Het verhaal dat Einstein slecht was in wiskunde is apocrief.",
    voorbeelden: [
      "Veel beroemde citaten van Churchill zijn apocrief: hij heeft ze waarschijnlijk nooit gezegd.",
      "Het apocriefe verhaal over een appel die op Newtons hoofd viel, wordt nog steeds verteld.",
    ],
    herkomst: "Grieks apokryphos (verborgen).",
    beeld: "Een stoffig boek dat uit de kloosterbibliotheek is verbannen en stiekem onder een deken wordt bewaard.",
  },
  {
    niveau: "expert",
    woord: "serendipiteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het doen van een gelukkige, onverwachte ontdekking terwijl je naar iets anders zoekt.",
    voorbeeldzin: "De ontdekking van penicilline wordt vaak genoemd als voorbeeld van serendipiteit.",
    voorbeelden: [
      "Door serendipiteit vond ze in een tweedehands boekwinkel precies het boek dat ze voor haar scriptie nodig had.",
      "Wetenschappers noemen serendipiteit een onderschatte bron van ontdekkingen.",
    ],
    herkomst: "Engels serendipity, bedacht door Horace Walpole naar het sprookje 'De drie prinsen van Serendip' (een oude naam voor Sri Lanka).",
    beeld: "Iemand die in de tuin naar zijn kwijtgeraakte sleutels graaft en een schatkist vindt.",
  },
  {
    niveau: "basis",
    woord: "nuance",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een subtiel verschil of een fijne schakering in betekenis, kleur of mening.",
    voorbeeldzin: "Het debat werd in zwart-wit gevoerd, zonder enig oog voor nuance.",
    voorbeelden: [
      "Het rapport bracht nuance aan in het beeld dat alle jongeren slecht lezen.",
      "In een bericht van een paar zinnen gaat de nuance vaak verloren.",
    ],
    herkomst: "Frans nuance (schakering), van nue (wolk).",
    beeld: "Een verfkaart met twintig bijna identieke tinten blauw.",
  },
  {
    niveau: "basis",
    woord: "consensus",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Algemene overeenstemming binnen een groep.",
    voorbeeldzin: "Onder klimaatwetenschappers bestaat brede consensus dat de aarde opwarmt door menselijk handelen.",
    voorbeelden: [
      "Na urenlang overleg bereikte de werkgroep eindelijk consensus.",
      "Er is geen consensus over de beste manier om het woningtekort op te lossen.",
    ],
    herkomst: "Latijn consentire (overeenstemmen).",
    beeld: "Een vergadertafel waar iedereen tegelijk zijn duim opsteekt.",
  },
  {
    niveau: "basis",
    woord: "hypocriet",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Schijnheilig; anders handelend dan je zelf zegt of van anderen verlangt.",
    voorbeeldzin: "Het is hypocriet om over het milieu te preken en elke maand een vliegvakantie te boeken.",
    voorbeelden: [
      "Hij vond het hypocriet dat de directeur bezuinigingen predikte en zelf een bonus kreeg.",
      "Het is niet hypocriet om van mening te veranderen als je nieuwe informatie krijgt.",
    ],
    herkomst: "Grieks hypokritès (toneelspeler).",
    beeld: "Een acteur die op het podium tegen snoep predikt en achter de coulissen een zak drop leegeet.",
  },
  {
    niveau: "gevorderd",
    woord: "ambigu",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Voor meer dan één uitleg vatbaar; dubbelzinnig.",
    voorbeeldzin: "Het antwoord van de minister was zo ambigu dat beide partijen dachten dat ze gelijk kregen.",
    voorbeelden: [
      "De ambigue formulering in het contract leidde tot een rechtszaak.",
      "Het einde van de film is bewust ambigu gehouden, zodat de kijker zelf kan kiezen.",
    ],
    herkomst: "Latijn ambiguus (twijfelachtig, naar twee kanten neigend).",
    beeld: "Een tekening die je zowel als een eend als een konijn kunt zien.",
  },
  {
    niveau: "gevorderd",
    woord: "lethargie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een toestand van grote lusteloosheid, sloomheid en gebrek aan energie.",
    voorbeeldzin: "Na de zware nederlaag hing er een sfeer van lethargie in de kleedkamer.",
    voorbeelden: [
      "Na de feestdagen overviel hem een lichte lethargie.",
      "Door de hitte hing er een lethargie over de hele stad.",
    ],
    herkomst: "Grieks lèthè (vergetelheid) + argos (traag).",
    beeld: "Een kat die op een warme middag niet eens de moeite neemt om een vlieg weg te slaan.",
  },
  {
    niveau: "expert",
    woord: "sui generis",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Uniek in zijn soort; niet in een bestaande categorie in te delen.",
    voorbeeldzin: "De Europese Unie wordt vaak sui generis genoemd: geen staat, maar ook geen gewone internationale organisatie.",
    voorbeelden: [
      "Het Nederlandse poldermodel wordt soms een verschijnsel sui generis genoemd.",
      "Zijn stijl was sui generis: niemand schilderde zoals hij.",
    ],
    herkomst: "Latijn: 'van zijn eigen soort'.",
    beeld: "Een vogelbekdier dat in de dierentuin bij geen enkel verblijf naar binnen mag.",
  },
];
