import type { BankWoord } from "../woordenbank.ts";

export const biologie: BankWoord[] = [
  {
    niveau: "basis",
    woord: "fotosynthese",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het proces waarbij planten met behulp van licht water en koolstofdioxide omzetten in suikers en zuurstof.",
    voorbeeldzin: "Zonder fotosynthese zou er nauwelijks zuurstof in de atmosfeer zijn.",
    voorbeelden: [
      "Bij fotosynthese speelt het groene bladgroen een hoofdrol.",
      "Ook algen in de oceaan doen aan fotosynthese en leveren zo veel zuurstof.",
    ],
    herkomst: "Grieks phoos (licht) + synthesis (samenstelling).",
    beeld: "Een blad met een klein zonnepaneel dat suikerklontjes en zuurstofbelletjes uitspuugt.",
  },
  {
    niveau: "basis",
    woord: "symbiose",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het langdurig samenleven van twee verschillende soorten, vaak tot wederzijds voordeel.",
    voorbeeldzin: "Clownvissen leven in symbiose met zeeanemonen.",
    voorbeelden: [
      "Mensen leven in symbiose met miljarden bacteriën in hun darmen.",
      "Een korstmos is een symbiose van een schimmel en een alg.",
    ],
    herkomst: "Grieks sym (samen) + bios (leven).",
    beeld: "Een clownvis die veilig tussen de prikkende tentakels van een anemoon woont en ze schoonhoudt.",
  },
  {
    niveau: "basis",
    woord: "mutatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een verandering in het DNA van een organisme, die erfelijk kan zijn.",
    voorbeeldzin: "Een enkele mutatie kan ervoor zorgen dat een bacterie ongevoelig wordt voor antibiotica.",
    voorbeelden: [
      "Door een mutatie kan een virus besmettelijker worden.",
      "Niet elke mutatie is schadelijk; sommige zijn zelfs nuttig.",
    ],
    herkomst: "Latijn mutare (veranderen).",
    beeld: "Iemand die een lang recept overschrijft, per ongeluk één letter verandert, en nu wordt de taart blauw.",
  },
  {
    niveau: "basis",
    woord: "ecosysteem",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een gemeenschap van organismen samen met hun omgeving, waarin ze allemaal op elkaar inwerken.",
    voorbeeldzin: "De Waddenzee is een uniek ecosysteem.",
    voorbeelden: [
      "Het verdwijnen van één soort kan een heel ecosysteem uit balans brengen.",
      "Ook een sloot in de polder is een klein ecosysteem.",
    ],
    herkomst: "Grieks oikos (huis) + systema (geheel).",
    beeld: "Een afgesloten glazen pot waarin planten, slakjes, water en licht samen een klein wereldje vormen.",
  },
  {
    niveau: "basis",
    woord: "metabolisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Stofwisseling: alle chemische processen waarmee een organisme energie en bouwstoffen verkrijgt en verwerkt.",
    voorbeeldzin: "Kolibries hebben een extreem snel metabolisme.",
    voorbeelden: [
      "Met de jaren vertraagt bij de meeste mensen het metabolisme.",
      "Schildklierhormonen hebben grote invloed op het metabolisme.",
    ],
    herkomst: "Grieks metabolè (verandering).",
    beeld: "Een drukke fabriek in je buik waar voedsel binnenkomt en energie in batterijen de deur uit gaat.",
  },
  {
    niveau: "gevorderd",
    woord: "homeostase",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het vermogen van een organisme om zijn interne omstandigheden, zoals temperatuur en bloedsuiker, stabiel te houden.",
    voorbeeldzin: "Zweten is een manier waarop het lichaam de homeostase van de lichaamstemperatuur bewaart.",
    voorbeelden: [
      "Rillen van de kou helpt het lichaam om de homeostase te herstellen.",
      "Diabetes verstoort de homeostase van de bloedsuikerspiegel.",
    ],
    herkomst: "Grieks homoios (gelijk) + stasis (stilstand).",
    beeld: "Een thermostaat in je hoofd die de verwarming aan- en uitzet om precies 37 graden te houden.",
  },
  {
    niveau: "gevorderd",
    woord: "endemisch",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Alleen van nature voorkomend in één bepaald gebied.",
    voorbeeldzin: "De dodo was endemisch op Mauritius.",
    voorbeelden: [
      "De komodovaraan is endemisch op een paar eilanden in Indonesië.",
      "Op Madagaskar zijn veel diersoorten endemisch.",
    ],
    herkomst: "Grieks endèmos (inheems), van en (in) + dèmos (volk).",
    beeld: "Een schildpad met een paspoort waarin staat: 'Mag dit eiland nooit verlaten'.",
  },
  {
    niveau: "gevorderd",
    woord: "enzym",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een eiwit dat een chemische reactie in een organisme versnelt zonder zelf te worden verbruikt.",
    voorbeeldzin: "Het enzym amylase in speeksel begint al in je mond met het afbreken van zetmeel.",
    voorbeelden: [
      "Lactase is het enzym dat melksuiker afbreekt.",
      "Wasmiddelen bevatten vaak een enzym dat eiwitvlekken oplost.",
    ],
    herkomst: "Grieks en (in) + zymè (zuurdesem, gist).",
    beeld: "Een klein schaartje dat razendsnel lange kettingen doorknipt en daarna onbeschadigd verdergaat met de volgende.",
  },
  {
    niveau: "gevorderd",
    woord: "fenotype",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De waarneembare eigenschappen van een organisme, zoals uiterlijk en gedrag, als resultaat van genen en omgeving.",
    voorbeeldzin: "Eeneiige tweelingen hebben dezelfde genen, maar hun fenotype kan door hun leefstijl verschillen.",
    voorbeelden: [
      "Oogkleur is een onderdeel van het fenotype.",
      "Het fenotype van een plant hangt ook af van de hoeveelheid zon en water.",
    ],
    herkomst: "Grieks phainein (tonen) + typos (vorm).",
    beeld: "Twee identieke fietsen uit dezelfde fabriek: de een glanst in de schuur, de ander roest na jaren in de regen.",
  },
  {
    niveau: "gevorderd",
    woord: "mitochondrium",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een onderdeel van de cel dat via de celademhaling energie (ATP) produceert.",
    voorbeeldzin: "Mitochondriën hebben hun eigen DNA, dat je alleen van je moeder erft.",
    voorbeelden: [
      "Spiercellen bevatten veel mitochondriën, omdat ze veel energie nodig hebben.",
      "Wetenschappers denken dat het mitochondrium ooit een zelfstandige bacterie was.",
    ],
    herkomst: "Grieks mitos (draad) + chondrion (korreltje).",
    beeld: "Kleine energiecentrales in de vorm van boontjes die in elke cel staan te zoemen.",
  },
  {
    niveau: "expert",
    woord: "apoptose",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Geprogrammeerde celdood: het gecontroleerd opruimen van cellen die beschadigd zijn of niet meer nodig zijn.",
    voorbeeldzin: "Bij een embryo zorgt apoptose ervoor dat de vliezen tussen de vingers verdwijnen.",
    voorbeelden: [
      "Als apoptose niet goed werkt, kunnen beschadigde cellen uitgroeien tot een tumor.",
      "Apoptose is een normaal onderdeel van de levenscyclus van een cel.",
    ],
    herkomst: "Grieks apoptosis (het afvallen, zoals bladeren van een boom).",
    beeld: "Herfstbladeren die keurig één voor één loslaten, zodat de boom gezond de winter in gaat.",
  },
  {
    niveau: "expert",
    woord: "epigenetica",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De studie van erfelijke veranderingen in genactiviteit die niet berusten op veranderingen in de DNA-volgorde zelf.",
    voorbeeldzin: "Onderzoek naar kinderen van moeders uit de Hongerwinter laat zien hoe epigenetica de gezondheid kan beïnvloeden.",
    voorbeelden: [
      "Volgens de epigenetica kunnen stress en voeding invloed hebben op welke genen actief zijn.",
      "De epigenetica helpt verklaren waarom cellen met hetzelfde DNA toch heel verschillend zijn.",
    ],
    herkomst: "Grieks epi (bovenop) + genetica.",
    beeld: "Een pianopartituur (het DNA) waarop met potlood staat welke passages zacht of helemaal niet gespeeld worden.",
  },
  {
    niveau: "expert",
    woord: "allopatrisch",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Gezegd van soortvorming die ontstaat doordat populaties geografisch van elkaar gescheiden raken.",
    voorbeeldzin: "Wanneer een bergketen een populatie in tweeën splitst, kan allopatrische soortvorming optreden.",
    voorbeelden: [
      "Allopatrische soortvorming kan optreden als een groep dieren op een eiland terechtkomt.",
      "Biologen onderzoeken of de twee vissoorten allopatrisch zijn ontstaan.",
    ],
    herkomst: "Grieks allos (ander) + patris (vaderland).",
    beeld: "Een groep muizen die door een nieuwe rivier in tweeën wordt gesplitst en aan beide oevers anders evolueert.",
  },
  {
    niveau: "expert",
    woord: "trofisch niveau",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De positie van een organisme in een voedselketen, zoals producent, planteneter of roofdier.",
    voorbeeldzin: "Bij elke stap naar een hoger trofisch niveau gaat ongeveer negentig procent van de energie verloren.",
    voorbeelden: [
      "Planten vormen het eerste trofisch niveau in een voedselketen.",
      "Roofdieren op het hoogste trofisch niveau zijn gevoelig voor gifstoffen die zich ophopen.",
    ],
    herkomst: "Grieks trophè (voeding).",
    beeld: "Een piramide met etages: gras onderin, konijnen daarboven en een vos helemaal bovenop.",
  },
  {
    niveau: "expert",
    woord: "convergente evolutie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het onafhankelijk ontstaan van vergelijkbare eigenschappen bij niet-verwante soorten die zich aan vergelijkbare omstandigheden aanpassen.",
    voorbeeldzin: "De vleugels van vleermuizen en vogels zijn een voorbeeld van convergente evolutie.",
    voorbeelden: [
      "Dat haaien en dolfijnen dezelfde vorm hebben, komt door convergente evolutie.",
      "Convergente evolutie laat zien dat de natuur vaak op dezelfde oplossing uitkomt.",
    ],
    herkomst: "Latijn convergere (naar elkaar toe buigen, samenkomen).",
    beeld: "Een haai en een dolfijn die geen familie zijn, maar toch in hetzelfde gestroomlijnde pak op een feest verschijnen.",
  },
  {
    niveau: "basis",
    woord: "natuurlijke selectie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het proces waarbij organismen met eigenschappen die beter bij hun omgeving passen meer nakomelingen krijgen, zodat die eigenschappen vaker voorkomen.",
    voorbeeldzin: "Door natuurlijke selectie werden donkere berkenspanners algemener in gebieden vol roet.",
    voorbeelden: [
      "Door natuurlijke selectie worden bacteriën resistent tegen antibiotica.",
      "Darwin beschreef natuurlijke selectie als de motor van evolutie.",
    ],
    herkomst: "Begrip uitgewerkt door Charles Darwin (1859).",
    beeld: "Een bos met donkere bomen, waar lichte motten opvallen en worden opgegeten en donkere motten overleven.",
  },
  {
    niveau: "basis",
    woord: "chromosoom",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een draadvormige structuur in de celkern die DNA met erfelijke informatie bevat; mensen hebben er normaal 46.",
    voorbeeldzin: "Mensen met het syndroom van Down hebben een extra kopie van chromosoom 21.",
    voorbeelden: [
      "Het Y-chromosoom bepaalt bij mensen meestal het mannelijk geslacht.",
      "Voor een celdeling wordt elk chromosoom eerst gekopieerd.",
    ],
    herkomst: "Grieks chroma (kleur) + soma (lichaam), omdat ze goed kleuren onder de microscoop.",
    beeld: "Een rij opgerolde boekdelen in een bibliotheek, elk vol bouwinstructies voor het lichaam.",
  },
  {
    niveau: "basis",
    woord: "biodiversiteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De verscheidenheid aan leven op aarde of in een gebied: soorten, genen en ecosystemen.",
    voorbeeldzin: "Het tropisch regenwoud heeft een enorme biodiversiteit.",
    voorbeelden: [
      "Bloemrijke bermen dragen bij aan de biodiversiteit.",
      "Door ontbossing neemt de biodiversiteit wereldwijd af.",
    ],
    herkomst: "Grieks bios (leven) + Latijn diversitas (verscheidenheid).",
    beeld: "Een regenwoud vol kikkers, papegaaien, orchideeën en insecten in alle kleuren.",
  },
  {
    niveau: "gevorderd",
    woord: "homoloog",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Gezegd van lichaamsdelen bij verschillende soorten die dezelfde evolutionaire oorsprong hebben, ook al hebben ze nu een andere functie.",
    voorbeeldzin: "De arm van een mens en de vleugel van een vleermuis zijn homologe organen.",
    voorbeelden: [
      "De vin van een walvis is homoloog aan de arm van een mens.",
      "Homologe organen verraden een gemeenschappelijke voorouder.",
    ],
    herkomst: "Grieks homologos (overeenstemmend).",
    beeld: "Hetzelfde bouwpakket botjes dat bij de ene soort een hand wordt, bij de andere een vin en bij een derde een vleugel.",
  },
  {
    niveau: "gevorderd",
    woord: "microbioom",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het geheel van micro-organismen, zoals bacteriën, dat in en op een lichaam leeft, bijvoorbeeld in de darmen.",
    voorbeeldzin: "Onderzoekers vinden steeds meer verbanden tussen het darmmicrobioom en onze gezondheid.",
    voorbeelden: [
      "Antibiotica kunnen het microbioom in je darmen tijdelijk verstoren.",
      "Ook de huid heeft een eigen microbioom.",
    ],
    herkomst: "Grieks mikros (klein) + bios (leven).",
    beeld: "Een drukke stad van miljarden bacteriën in je darmen, met eigen wijken en bewoners.",
  },
  {
    niveau: "expert",
    woord: "CRISPR",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een techniek waarmee wetenschappers DNA heel precies kunnen knippen en aanpassen, als een moleculaire schaar.",
    voorbeeldzin: "Met CRISPR kunnen onderzoekers genen uitschakelen om hun functie te bestuderen.",
    voorbeelden: [
      "Met CRISPR hopen artsen erfelijke ziektes ooit te kunnen genezen.",
      "De ontdekkers van CRISPR kregen in 2020 de Nobelprijs voor Scheikunde.",
    ],
    herkomst: "Engelse afkorting (Clustered Regularly Interspaced Short Palindromic Repeats); oorspronkelijk een afweersysteem van bacteriën.",
    beeld: "Een tekstverwerker die met zoeken-en-vervangen één letter in het boek van het leven verandert.",
  },
];
