import type { BankWoord } from "../woordenbank.ts";

export const biologie: BankWoord[] = [
  {
    niveau: "basis",
    woord: "fotosynthese",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het proces waarbij planten met behulp van licht water en koolstofdioxide omzetten in suikers en zuurstof.",
    voorbeeldzin: "Zonder fotosynthese zou er nauwelijks zuurstof in de atmosfeer zijn.",
    herkomst: "Grieks phoos (licht) + synthesis (samenstelling).",
    beeld: "Een blad met een klein zonnepaneel dat suikerklontjes en zuurstofbelletjes uitspuugt.",
    emoji: "🌿☀️",
  },
  {
    niveau: "basis",
    woord: "symbiose",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het langdurig samenleven van twee verschillende soorten, vaak tot wederzijds voordeel.",
    voorbeeldzin: "Clownvissen leven in symbiose met zeeanemonen.",
    herkomst: "Grieks sym (samen) + bios (leven).",
    beeld: "Een clownvis die veilig tussen de prikkende tentakels van een anemoon woont en ze schoonhoudt.",
    emoji: "🐠🪸",
  },
  {
    niveau: "basis",
    woord: "mutatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een verandering in het DNA van een organisme, die erfelijk kan zijn.",
    voorbeeldzin: "Een enkele mutatie kan ervoor zorgen dat een bacterie ongevoelig wordt voor antibiotica.",
    herkomst: "Latijn mutare (veranderen).",
    beeld: "Iemand die een lang recept overschrijft, per ongeluk één letter verandert, en nu wordt de taart blauw.",
    emoji: "⌨️🎂",
  },
  {
    niveau: "basis",
    woord: "ecosysteem",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een gemeenschap van organismen samen met hun omgeving, waarin ze allemaal op elkaar inwerken.",
    voorbeeldzin: "De Waddenzee is een uniek ecosysteem.",
    herkomst: "Grieks oikos (huis) + systema (geheel).",
    beeld: "Een afgesloten glazen pot waarin planten, slakjes, water en licht samen een klein wereldje vormen.",
    emoji: "🫙🐌",
  },
  {
    niveau: "basis",
    woord: "metabolisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Stofwisseling: alle chemische processen waarmee een organisme energie en bouwstoffen verkrijgt en verwerkt.",
    voorbeeldzin: "Kolibries hebben een extreem snel metabolisme.",
    herkomst: "Grieks metabolè (verandering).",
    beeld: "Een drukke fabriek in je buik waar voedsel binnenkomt en energie in batterijen de deur uit gaat.",
    emoji: "🏭🔋",
  },
  {
    niveau: "gevorderd",
    woord: "homeostase",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het vermogen van een organisme om zijn interne omstandigheden, zoals temperatuur en bloedsuiker, stabiel te houden.",
    voorbeeldzin: "Zweten is een manier waarop het lichaam de homeostase van de lichaamstemperatuur bewaart.",
    herkomst: "Grieks homoios (gelijk) + stasis (stilstand).",
    beeld: "Een thermostaat in je hoofd die de verwarming aan- en uitzet om precies 37 graden te houden.",
    emoji: "🌡️🧠",
  },
  {
    niveau: "gevorderd",
    woord: "endemisch",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Alleen van nature voorkomend in één bepaald gebied.",
    voorbeeldzin: "De dodo was endemisch op Mauritius.",
    herkomst: "Grieks endèmos (inheems), van en (in) + dèmos (volk).",
    beeld: "Een schildpad met een paspoort waarin staat: 'Mag dit eiland nooit verlaten'.",
    emoji: "🐢🏝️",
  },
  {
    niveau: "gevorderd",
    woord: "enzym",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een eiwit dat een chemische reactie in een organisme versnelt zonder zelf te worden verbruikt.",
    voorbeeldzin: "Het enzym amylase in speeksel begint al in je mond met het afbreken van zetmeel.",
    herkomst: "Grieks en (in) + zymè (zuurdesem, gist).",
    beeld: "Een klein schaartje dat razendsnel lange kettingen doorknipt en daarna onbeschadigd verdergaat met de volgende.",
    emoji: "✂️⛓️",
  },
  {
    niveau: "gevorderd",
    woord: "fenotype",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De waarneembare eigenschappen van een organisme, zoals uiterlijk en gedrag, als resultaat van genen en omgeving.",
    voorbeeldzin: "Eeneiige tweelingen hebben dezelfde genen, maar hun fenotype kan door hun leefstijl verschillen.",
    herkomst: "Grieks phainein (tonen) + typos (vorm).",
    beeld: "Twee identieke fietsen uit dezelfde fabriek: de een glanst in de schuur, de ander roest na jaren in de regen.",
    emoji: "🚲🌧️",
  },
  {
    niveau: "gevorderd",
    woord: "mitochondrium",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een onderdeel van de cel dat via de celademhaling energie (ATP) produceert.",
    voorbeeldzin: "Mitochondriën hebben hun eigen DNA, dat je alleen van je moeder erft.",
    herkomst: "Grieks mitos (draad) + chondrion (korreltje).",
    beeld: "Kleine energiecentrales in de vorm van boontjes die in elke cel staan te zoemen.",
    emoji: "⚡🫘",
  },
  {
    niveau: "expert",
    woord: "apoptose",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Geprogrammeerde celdood: het gecontroleerd opruimen van cellen die beschadigd zijn of niet meer nodig zijn.",
    voorbeeldzin: "Bij een embryo zorgt apoptose ervoor dat de vliezen tussen de vingers verdwijnen.",
    herkomst: "Grieks apoptosis (het afvallen, zoals bladeren van een boom).",
    beeld: "Herfstbladeren die keurig één voor één loslaten, zodat de boom gezond de winter in gaat.",
    emoji: "🍂🌳",
  },
  {
    niveau: "expert",
    woord: "epigenetica",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De studie van erfelijke veranderingen in genactiviteit die niet berusten op veranderingen in de DNA-volgorde zelf.",
    voorbeeldzin: "Onderzoek naar kinderen van moeders uit de Hongerwinter laat zien hoe epigenetica de gezondheid kan beïnvloeden.",
    herkomst: "Grieks epi (bovenop) + genetica.",
    beeld: "Een pianopartituur (het DNA) waarop met potlood staat welke passages zacht of helemaal niet gespeeld worden.",
    emoji: "🎹✏️",
  },
  {
    niveau: "expert",
    woord: "allopatrisch",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Gezegd van soortvorming die ontstaat doordat populaties geografisch van elkaar gescheiden raken.",
    voorbeeldzin: "Wanneer een bergketen een populatie in tweeën splitst, kan allopatrische soortvorming optreden.",
    herkomst: "Grieks allos (ander) + patris (vaderland).",
    beeld: "Een groep muizen die door een nieuwe rivier in tweeën wordt gesplitst en aan beide oevers anders evolueert.",
    emoji: "🐭🌊",
  },
  {
    niveau: "expert",
    woord: "trofisch niveau",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De positie van een organisme in een voedselketen, zoals producent, planteneter of roofdier.",
    voorbeeldzin: "Bij elke stap naar een hoger trofisch niveau gaat ongeveer negentig procent van de energie verloren.",
    herkomst: "Grieks trophè (voeding).",
    beeld: "Een piramide met etages: gras onderin, konijnen daarboven en een vos helemaal bovenop.",
    emoji: "🌾🐇🦊",
  },
  {
    niveau: "expert",
    woord: "convergente evolutie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het onafhankelijk ontstaan van vergelijkbare eigenschappen bij niet-verwante soorten die zich aan vergelijkbare omstandigheden aanpassen.",
    voorbeeldzin: "De vleugels van vleermuizen en vogels zijn een voorbeeld van convergente evolutie.",
    herkomst: "Latijn convergere (naar elkaar toe buigen, samenkomen).",
    beeld: "Een haai en een dolfijn die geen familie zijn, maar toch in hetzelfde gestroomlijnde pak op een feest verschijnen.",
    emoji: "🦈🐬",
  },
  {
    niveau: "basis",
    woord: "natuurlijke selectie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het proces waarbij organismen met eigenschappen die beter bij hun omgeving passen meer nakomelingen krijgen, zodat die eigenschappen vaker voorkomen.",
    voorbeeldzin: "Door natuurlijke selectie werden donkere berkenspanners algemener in gebieden vol roet.",
    herkomst: "Begrip uitgewerkt door Charles Darwin (1859).",
    beeld: "Een bos met donkere bomen, waar lichte motten opvallen en worden opgegeten en donkere motten overleven.",
    emoji: "🦋🌳",
  },
  {
    niveau: "basis",
    woord: "chromosoom",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een draadvormige structuur in de celkern die DNA met erfelijke informatie bevat; mensen hebben er normaal 46.",
    voorbeeldzin: "Mensen met het syndroom van Down hebben een extra kopie van chromosoom 21.",
    herkomst: "Grieks chroma (kleur) + soma (lichaam), omdat ze goed kleuren onder de microscoop.",
    beeld: "Een rij opgerolde boekdelen in een bibliotheek, elk vol bouwinstructies voor het lichaam.",
    emoji: "📚🧬",
  },
  {
    niveau: "basis",
    woord: "biodiversiteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De verscheidenheid aan leven op aarde of in een gebied: soorten, genen en ecosystemen.",
    voorbeeldzin: "Het tropisch regenwoud heeft een enorme biodiversiteit.",
    herkomst: "Grieks bios (leven) + Latijn diversitas (verscheidenheid).",
    beeld: "Een regenwoud vol kikkers, papegaaien, orchideeën en insecten in alle kleuren.",
    emoji: "🦜🐸",
  },
  {
    niveau: "gevorderd",
    woord: "homoloog",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Gezegd van lichaamsdelen bij verschillende soorten die dezelfde evolutionaire oorsprong hebben, ook al hebben ze nu een andere functie.",
    voorbeeldzin: "De arm van een mens en de vleugel van een vleermuis zijn homologe organen.",
    herkomst: "Grieks homologos (overeenstemmend).",
    beeld: "Hetzelfde bouwpakket botjes dat bij de ene soort een hand wordt, bij de andere een vin en bij een derde een vleugel.",
    emoji: "🦴🦇",
  },
  {
    niveau: "gevorderd",
    woord: "microbioom",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het geheel van micro-organismen, zoals bacteriën, dat in en op een lichaam leeft, bijvoorbeeld in de darmen.",
    voorbeeldzin: "Onderzoekers vinden steeds meer verbanden tussen het darmmicrobioom en onze gezondheid.",
    herkomst: "Grieks mikros (klein) + bios (leven).",
    beeld: "Een drukke stad van miljarden bacteriën in je darmen, met eigen wijken en bewoners.",
    emoji: "🦠🏙️",
  },
  {
    niveau: "expert",
    woord: "CRISPR",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een techniek waarmee wetenschappers DNA heel precies kunnen knippen en aanpassen, als een moleculaire schaar.",
    voorbeeldzin: "Met CRISPR kunnen onderzoekers genen uitschakelen om hun functie te bestuderen.",
    herkomst: "Engelse afkorting (Clustered Regularly Interspaced Short Palindromic Repeats); oorspronkelijk een afweersysteem van bacteriën.",
    beeld: "Een tekstverwerker die met zoeken-en-vervangen één letter in het boek van het leven verandert.",
    emoji: "✂️🧬",
  },
];
