import type { BankWoord } from "../woordenbank.ts";

export const economie: BankWoord[] = [
  {
    niveau: "basis",
    woord: "inflatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een algemene stijging van het prijsniveau, waardoor je met hetzelfde geld minder kunt kopen.",
    voorbeeldzin: "Door de hoge inflatie werden de boodschappen in één jaar flink duurder.",
    herkomst: "Latijn inflare (opblazen).",
    beeld: "Een ballon met een bankbiljet erop die steeds groter wordt, terwijl het biljet steeds minder waard lijkt.",
    emoji: "🎈💶",
  },
  {
    niveau: "basis",
    woord: "recessie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een periode waarin de economie krimpt; vaak gedefinieerd als twee opeenvolgende kwartalen met een dalende productie.",
    voorbeeldzin: "Tijdens de recessie verloren veel mensen hun baan.",
    herkomst: "Latijn recedere (terugwijken).",
    beeld: "Een rivier die langzaam droogvalt, zodat de bootjes een voor een vast komen te liggen.",
    emoji: "🏞️⛵",
  },
  {
    niveau: "basis",
    woord: "monopolie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een situatie waarin één aanbieder de hele markt voor een product of dienst beheerst.",
    voorbeeldzin: "Omdat het bedrijf een monopolie had, kon het de prijzen naar believen verhogen.",
    herkomst: "Grieks monos (alleen) + pōlein (verkopen).",
    beeld: "Eén kraam op een verder lege markt, met een lange rij klanten en een verkoper die de prijzen steeds hoger zet.",
    emoji: "🏪📈",
  },
  {
    niveau: "basis",
    woord: "bruto binnenlands product",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De totale waarde van alle goederen en diensten die in een land in een jaar worden geproduceerd; afgekort bbp.",
    voorbeeldzin: "Economen gebruiken het bruto binnenlands product om de omvang van economieën te vergelijken.",
    herkomst: "Bruto (zonder aftrek) + binnenlands + product.",
    beeld: "Een reusachtige kassabon waarop alles staat wat een land in een jaar maakt, van kaas tot software.",
    emoji: "🧾🌍",
  },
  {
    niveau: "basis",
    woord: "dividend",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het deel van de winst dat een bedrijf uitkeert aan zijn aandeelhouders.",
    voorbeeldzin: "Het bedrijf keerde dit jaar een hoger dividend uit dan verwacht.",
    herkomst: "Latijn dividendum (wat verdeeld moet worden).",
    beeld: "Een taart, de winst, waarvan elke aandeelhouder een punt krijgt.",
    emoji: "🥧🍰",
  },
  {
    niveau: "basis",
    woord: "koopkracht",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De hoeveelheid goederen en diensten die je met je inkomen kunt kopen.",
    voorbeeldzin: "Doordat de lonen minder stegen dan de prijzen, daalde de koopkracht.",
    herkomst: "Samenstelling van kopen en kracht.",
    beeld: "Een portemonnee met spierballen die steeds slapper worden naarmate de prijzen stijgen.",
    emoji: "👛💪",
  },
  {
    niveau: "gevorderd",
    woord: "deflatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een algemene daling van het prijsniveau over een langere periode.",
    voorbeeldzin: "Deflatie klinkt gunstig, maar kan ertoe leiden dat mensen aankopen uitstellen en de economie stilvalt.",
    herkomst: "Latijn deflare (wegblazen).",
    beeld: "Een ballon die langzaam leegloopt, terwijl mensen wachten tot hij nog kleiner wordt.",
    emoji: "🎈⬇️",
  },
  {
    niveau: "gevorderd",
    woord: "schaalvoordeel",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het kostenvoordeel doordat de kosten per product dalen naarmate je grotere hoeveelheden produceert.",
    voorbeeldzin: "Grote supermarktketens profiteren van schaalvoordelen bij hun inkoop.",
    herkomst: "Samenstelling van schaal (omvang) en voordeel.",
    beeld: "Een bakker die de oven voor één taart net zo lang moet opwarmen als voor honderd taarten.",
    emoji: "🍰🔥",
  },
  {
    niveau: "gevorderd",
    woord: "prijselasticiteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De mate waarin de gevraagde hoeveelheid van een product verandert als de prijs verandert.",
    voorbeeldzin: "Omdat de prijselasticiteit van brood laag is, kopen mensen na een prijsstijging bijna evenveel brood.",
    herkomst: "Samenstelling van prijs en elasticiteit (Grieks elastos: rekbaar).",
    beeld: "Een elastiekje dat bij het ene product ver uitrekt als de prijs verandert en bij het andere nauwelijks beweegt.",
    emoji: "📏🍞",
  },
  {
    niveau: "gevorderd",
    woord: "opportuniteitskosten",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De waarde van het beste alternatief dat je opgeeft wanneer je een keuze maakt.",
    voorbeeldzin: "De opportuniteitskosten van studeren zijn onder meer het salaris dat je in die jaren had kunnen verdienen.",
    herkomst: "Vertaling van het Engelse opportunity cost.",
    beeld: "Een kind met één euro dat een ijsje kiest en weemoedig naar de zak snoep kijkt die het nu misloopt.",
    emoji: "🍦🍬",
  },
  {
    niveau: "gevorderd",
    woord: "kartel",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een verboden afspraak tussen bedrijven om prijzen, productie of markten onderling te regelen en zo de concurrentie te beperken.",
    voorbeeldzin: "De bouwbedrijven kregen een hoge boete omdat ze een kartel hadden gevormd.",
    herkomst: "Via Duits Kartell van Italiaans cartello (briefje, schriftelijke afspraak).",
    beeld: "Drie kraamhouders die achter de markt fluisterend afspreken dat niemand zijn appels goedkoper verkoopt.",
    emoji: "🍎🤫",
  },
  {
    niveau: "gevorderd",
    woord: "staatsschuld",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het totale bedrag dat de overheid van een land heeft geleend en nog moet terugbetalen.",
    voorbeeldzin: "Door de crisis steeg de staatsschuld tot boven de zestig procent van het bbp.",
    herkomst: "Samenstelling van staat en schuld.",
    beeld: "Een reusachtige rekening aan de muur van het ministerie die elk jaar een stukje langer wordt.",
    emoji: "🧾🏛️",
  },
  {
    niveau: "gevorderd",
    woord: "externaliteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een effect van een economische activiteit op anderen dat niet in de prijs is verwerkt, zoals vervuiling.",
    voorbeeldzin: "De luchtvervuiling door vliegverkeer is een negatieve externaliteit.",
    herkomst: "Latijn externus (uitwendig).",
    beeld: "Een fabriek die goedkope schoenen maakt, terwijl de rook over de tuinen van de buren waait.",
    emoji: "🏭💨",
  },
  {
    niveau: "expert",
    woord: "kwantitatieve verruiming",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een maatregel waarbij een centrale bank op grote schaal obligaties opkoopt om geld in de economie te pompen en de rente laag te houden.",
    voorbeeldzin: "Vanaf 2015 zette de Europese Centrale Bank kwantitatieve verruiming in om de economie te stimuleren.",
    herkomst: "Vertaling van het Engelse quantitative easing.",
    beeld: "Een brandweerwagen die geld in plaats van water over een uitgedroogde economie spuit.",
    emoji: "🚒💶",
  },
  {
    niveau: "expert",
    woord: "stagflatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een combinatie van economische stilstand, hoge werkloosheid en hoge inflatie.",
    voorbeeldzin: "Na de oliecrisis van de jaren zeventig kampten veel westerse landen met stagflatie.",
    herkomst: "Samentrekking van stagnatie en inflatie.",
    beeld: "Een auto die stilstaat in de file, terwijl de benzineprijs op het bord blijft stijgen.",
    emoji: "🚗⛽",
  },
  {
    niveau: "expert",
    woord: "moral hazard",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het risico dat iemand zich roekelozer gaat gedragen omdat een ander de gevolgen draagt.",
    voorbeeldzin: "Als banken weten dat de overheid ze altijd redt, ontstaat moral hazard.",
    herkomst: "Engels: moreel risico; oorspronkelijk een term uit de verzekeringswereld.",
    beeld: "Iemand met een allriskverzekering die zijn fiets ineens nergens meer op slot zet.",
    emoji: "🚲🔓",
  },
  {
    niveau: "expert",
    woord: "grensnut",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het extra nut of plezier dat je haalt uit één extra eenheid van een product.",
    voorbeeldzin: "Het grensnut van het vijfde stuk taart is een stuk lager dan dat van het eerste.",
    herkomst: "Samenstelling van grens (marge) en nut; vertaling van het Engelse marginal utility.",
    beeld: "Het eerste glas water na een woestijntocht voelt als goud; het tiende laat je staan.",
    emoji: "💧🏜️",
  },
  {
    niveau: "expert",
    woord: "arbitrage",
    woordsoort: "zelfstandig naamwoord",
    definitie: "In de economie: profiteren van prijsverschillen door iets op de ene markt goedkoop te kopen en tegelijk op een andere duurder te verkopen.",
    voorbeeldzin: "Handelaars gebruiken computers om binnen milliseconden aan arbitrage tussen beurzen te doen.",
    herkomst: "Frans arbitrage, van arbitre (scheidsrechter); in het recht betekent het ook geschilbeslechting door een scheidsrechter.",
    beeld: "Iemand die in het ene dorp appels koopt voor een euro en ze in het buurdorp meteen voor twee euro verkoopt.",
    emoji: "🍎🔁",
  },
  {
    niveau: "expert",
    woord: "keynesianisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De economische theorie van John Maynard Keynes dat de overheid in tijden van crisis de economie moet stimuleren door extra uit te geven.",
    voorbeeldzin: "Het grote investeringsprogramma tijdens de crisis was puur keynesianisme.",
    herkomst: "Naar de Britse econoom John Maynard Keynes (1883-1946).",
    beeld: "Een overheid die in slechte tijden zelf bouwvakkers inhuurt om bruggen te bouwen.",
    emoji: "🌉👷",
  },
];
