import type { BankWoord } from "../woordenbank.ts";

export const filosofie: BankWoord[] = [
  {
    niveau: "basis",
    woord: "paradigma",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een algemeen aanvaard denkkader of model dat bepaalt hoe een groep, bijvoorbeeld wetenschappers, naar de werkelijkheid kijkt.",
    voorbeeldzin: "Het inzicht dat de aarde om de zon draait, zorgde voor een paradigmaverschuiving in de sterrenkunde.",
    voorbeelden: [
      "Binnen het oude paradigma werd ziekte gezien als straf, niet als gevolg van bacteriën.",
      "Thuiswerken zorgde voor een nieuw paradigma in hoe we over kantoren denken.",
    ],
    herkomst: "Grieks paradeigma (voorbeeld, model); populair geworden door de wetenschapsfilosoof Thomas Kuhn.",
    beeld: "Een zaal waarin iedereen dezelfde gekleurde bril draagt, tot iemand hem afzet en de wereld ineens in andere kleuren ziet.",
  },
  {
    niveau: "basis",
    woord: "determinisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De opvatting dat alles wat gebeurt, ook menselijke keuzes, volledig wordt bepaald door voorafgaande oorzaken.",
    voorbeeldzin: "Als het determinisme klopt, is het de vraag of we eigenlijk wel een vrije wil hebben.",
    voorbeelden: [
      "Het genetisch determinisme stelt dat onze genen bepalen wie we worden.",
      "Zijn boek verzette zich tegen elke vorm van determinisme: volgens hem hebben we altijd een keuze.",
    ],
    herkomst: "Latijn determinare (begrenzen, vastleggen).",
    beeld: "Een biljarttafel waarop je, als je alle krachten kent, precies kunt voorspellen waar elke bal eindigt.",
  },
  {
    niveau: "basis",
    woord: "hedonisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De levensopvatting dat het streven naar genot en het vermijden van pijn het hoogste doel is.",
    voorbeeldzin: "Zijn vakantie van uitslapen, lekker eten en niets moeten was puur hedonisme.",
    voorbeelden: [
      "Epicurus wordt vaak met hedonisme verbonden, al pleitte hij juist voor eenvoudig genieten.",
      "Critici zien in de consumptiemaatschappij een vorm van hedonisme.",
    ],
    herkomst: "Grieks hèdonè (genot).",
    beeld: "Iemand in een hangmat met een ijsje in de ene hand en een zonnebril op, die nergens anders aan denkt.",
  },
  {
    niveau: "basis",
    woord: "ethiek",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De tak van de filosofie die nadenkt over goed en kwaad en over hoe je behoort te handelen.",
    voorbeeldzin: "Bij de ontwikkeling van zelfrijdende auto's spelen ook vragen uit de ethiek een rol.",
    voorbeelden: [
      "De ethiek van dierproeven blijft een onderwerp van felle discussie.",
      "Artsen leren in hun opleiding ook over medische ethiek.",
    ],
    herkomst: "Grieks èthos (gewoonte, karakter).",
    beeld: "Een weegschaal met een engeltje op de ene schaal en een duiveltje op de andere.",
  },
  {
    niveau: "basis",
    woord: "dilemma",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een lastige keuze tussen twee mogelijkheden die allebei nadelen hebben.",
    voorbeeldzin: "Ze stond voor een dilemma: de goedbetaalde baan of het werk dat ze echt leuk vond.",
    voorbeelden: [
      "Artsen staan soms voor het dilemma of ze een patiënt de volle waarheid moeten vertellen.",
      "Het bekende trolleyprobleem is een moreel dilemma.",
    ],
    herkomst: "Grieks di (twee) + lèmma (aanname).",
    beeld: "Een wandelaar bij een splitsing: links een modderpad, rechts een pad vol brandnetels.",
  },
  {
    niveau: "gevorderd",
    woord: "adequatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het passend of toereikend zijn voor een doel; in de filosofie: de overeenstemming tussen een gedachte of uitspraak en de werkelijkheid.",
    voorbeeldzin: "Volgens de klassieke waarheidstheorie is waarheid de adequatie van het verstand aan de dingen.",
    voorbeelden: [
      "De commissie twijfelde aan de adequatie van de maatregelen voor zo'n grote crisis.",
      "Filosofen discussiëren al eeuwen over de adequatie van taal aan de werkelijkheid.",
    ],
    herkomst: "Latijn adaequatio (gelijkmaking), van ad (naar) + aequus (gelijk); verwant aan adequaat.",
    beeld: "Een sleutel die precies in het slot past en soepel omdraait.",
  },
  {
    niveau: "gevorderd",
    woord: "empirisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De opvatting dat kennis voortkomt uit zintuiglijke ervaring en waarneming.",
    voorbeeldzin: "Volgens het empirisme van John Locke is de geest bij de geboorte een onbeschreven blad.",
    voorbeelden: [
      "De moderne wetenschap is sterk beïnvloed door het empirisme: eerst meten, dan concluderen.",
      "Aanhangers van het empirisme wantrouwen kennis die niet op waarneming berust.",
    ],
    herkomst: "Grieks empeiria (ervaring).",
    beeld: "Een onderzoeker die niets gelooft tot ze het zelf heeft gezien, geroken en aangeraakt.",
  },
  {
    niveau: "gevorderd",
    woord: "rationalisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De opvatting dat het verstand, en niet de zintuiglijke ervaring, de belangrijkste bron van kennis is.",
    voorbeeldzin: "Descartes' uitspraak 'Ik denk, dus ik ben' is een schoolvoorbeeld van rationalisme.",
    voorbeelden: [
      "Het rationalisme stelt dat je wiskundige waarheden kunt kennen zonder ze te meten.",
      "Spinoza en Leibniz behoren tot de grote denkers van het rationalisme.",
    ],
    herkomst: "Latijn ratio (rede, verstand).",
    beeld: "Een denker in een donkere kamer met de ogen dicht, die met alleen zijn verstand een hele wereld uitrekent.",
  },
  {
    niveau: "gevorderd",
    woord: "nihilisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De opvatting dat het leven geen objectieve zin, waarde of betekenis heeft.",
    voorbeeldzin: "In zijn somberste periode neigde de schrijver naar nihilisme: niets leek er nog toe te doen.",
    voorbeelden: [
      "Nietzsche waarschuwde dat het wegvallen van oude zekerheden tot nihilisme kon leiden.",
      "Het personage in de roman zweeft tussen humor en nihilisme.",
    ],
    herkomst: "Latijn nihil (niets).",
    beeld: "Iemand die voor een prachtig schilderij staat en schouderophalend zegt: 'Het zijn maar vlekken verf.'",
  },
  {
    niveau: "gevorderd",
    woord: "utilitarisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De ethische opvatting dat een handeling goed is als ze het grootste geluk voor het grootste aantal mensen oplevert.",
    voorbeeldzin: "Volgens het utilitarisme zou je kunnen verdedigen dat je één persoon opoffert om er vijf te redden.",
    voorbeelden: [
      "Het utilitarisme speelt mee wanneer overheden kosten en baten van beleid tegen elkaar afwegen.",
      "Critici van het utilitarisme vinden dat de rechten van het individu erdoor in het gedrang komen.",
    ],
    herkomst: "Latijn utilitas (nut); uitgewerkt door Jeremy Bentham en John Stuart Mill.",
    beeld: "Een rekenmachine die bij elke keuze optelt hoeveel mensen er gelukkiger van worden.",
  },
  {
    niveau: "gevorderd",
    woord: "dialectiek",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een manier van denken waarin tegenstellingen (these en antithese) botsen en samen tot een nieuw inzicht (synthese) leiden.",
    voorbeeldzin: "De dialectiek van Hegel had grote invloed op het denken van Karl Marx.",
    voorbeelden: [
      "In de dialectiek ontstaat vooruitgang doordat tegengestelde ideeën met elkaar botsen.",
      "Een goed debat heeft iets van dialectiek: uit twee standpunten groeit een beter derde.",
    ],
    herkomst: "Grieks dialektikè (de kunst van het gesprek).",
    beeld: "Twee rivieren die tegen elkaar in stromen en samen een nieuw meer vormen.",
  },
  {
    niveau: "gevorderd",
    woord: "existentialisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een filosofische stroming die stelt dat de mens zonder vooraf gegeven doel bestaat en zelf betekenis moet geven aan zijn leven door vrije keuzes.",
    voorbeeldzin: "Sartres uitspraak dat de mens 'veroordeeld is tot vrijheid' is een kernidee van het existentialisme.",
    voorbeelden: [
      "Het existentialisme stelt dat je zelf verantwoordelijk bent voor wie je wordt.",
      "Na de Tweede Wereldoorlog werd het existentialisme populair in de cafés van Parijs.",
    ],
    herkomst: "Latijn existentia (bestaan).",
    beeld: "Iemand die een leeg notitieboek krijgt met op de eerste bladzijde: 'Schrijf zelf je doel op.'",
  },
  {
    niveau: "gevorderd",
    woord: "stoïcisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een filosofische stroming uit de oudheid die leert dat je rust vindt door je te richten op wat je zelf kunt beïnvloeden en de rest gelaten te aanvaarden.",
    voorbeeldzin: "De Romeinse keizer Marcus Aurelius schreef zijn stoïcijnse gedachten op in een persoonlijk dagboek.",
    voorbeelden: [
      "Het stoïcisme leert je onderscheid te maken tussen wat je wel en niet in de hand hebt.",
      "Veel moderne zelfhulpboeken putten uit het stoïcisme.",
    ],
    herkomst: "Grieks stoa (zuilengang), naar de zuilenhal in Athene waar Zeno lesgaf.",
    beeld: "Iemand die rustig zijn thee drinkt terwijl buiten een storm raast.",
  },
  {
    niveau: "expert",
    woord: "ontologie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het deel van de filosofie dat onderzoekt wat er bestaat en wat 'zijn' eigenlijk is.",
    voorbeeldzin: "Of getallen echt bestaan of alleen in ons hoofd, is een vraag uit de ontologie.",
    voorbeelden: [
      "De vraag of een bedrijf echt 'bestaat' of alleen een afspraak is, raakt aan de ontologie.",
      "In de ontologie wordt onderzocht wat de basisbouwstenen van de werkelijkheid zijn.",
    ],
    herkomst: "Grieks on (zijnde) + logos (leer).",
    beeld: "Een filosoof die op een tafel klopt en vraagt: 'Maar bestáá je eigenlijk wel?'",
  },
  {
    niveau: "expert",
    woord: "fenomenologie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een filosofische methode die de ervaring beschrijft zoals die zich aan het bewustzijn voordoet, zonder vooraf aannames te doen.",
    voorbeeldzin: "In de fenomenologie van Edmund Husserl staat de beleefde ervaring centraal.",
    voorbeelden: [
      "De fenomenologie vraagt niet wat pijn is in het lichaam, maar hoe pijn wordt beleefd.",
      "Architecten gebruiken ideeën uit de fenomenologie om te begrijpen hoe mensen een ruimte ervaren.",
    ],
    herkomst: "Grieks phainomenon (wat zich vertoont) + logos (leer).",
    beeld: "Iemand die een aardbei eet en alleen beschrijft hoe die voelt, ruikt en smaakt, zonder te vragen waar hij vandaan komt.",
  },
  {
    niveau: "expert",
    woord: "categorische imperatief",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het morele principe van Kant: handel alleen volgens een regel waarvan je zou willen dat iedereen die altijd volgt.",
    voorbeeldzin: "Volgens de categorische imperatief mag je niet liegen, ook niet als het je goed uitkomt.",
    voorbeelden: [
      "Volgens de categorische imperatief mag je een ander nooit alleen als middel gebruiken.",
      "De categorische imperatief vraagt je te handelen alsof je regel een wet voor iedereen zou worden.",
    ],
    herkomst: "Latijn imperativus (bevelend); geformuleerd door Immanuel Kant in 1785.",
    beeld: "Iemand die voor elke keuze eerst vraagt: 'En als de hele wereld dit nou deed?'",
  },
  {
    niveau: "expert",
    woord: "a priori",
    woordsoort: "bijwoord",
    definitie: "Voorafgaand aan en onafhankelijk van ervaring; alleen met het verstand te weten.",
    voorbeeldzin: "Dat een vrijgezel ongetrouwd is, weet je a priori: daarvoor hoef je niemand te onderzoeken.",
    voorbeelden: [
      "Dat twee plus twee vier is, weet je a priori.",
      "Wiskundige stellingen worden vaak gezien als kennis die a priori geldt.",
    ],
    herkomst: "Latijn: 'vanuit het eerdere'.",
    beeld: "Iemand met een blinddoek om die zonder rond te kijken zeker weet dat een driehoek drie hoeken heeft.",
  },
  {
    niveau: "expert",
    woord: "solipsisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De opvatting dat alleen je eigen geest zeker bestaat en dat al het andere misschien alleen in je voorstelling bestaat.",
    voorbeeldzin: "Een consequente solipsist zou zelfs twijfelen of zijn gesprekspartner wel echt bestaat.",
    voorbeelden: [
      "Het solipsisme is filosofisch lastig te weerleggen, maar vrijwel niemand gelooft er echt in.",
      "In het gesprek met hem proefde ze iets van solipsisme: alleen zijn eigen belevingswereld leek te bestaan.",
    ],
    herkomst: "Latijn solus (alleen) + ipse (zelf).",
    beeld: "Iemand alleen in een bioscoopzaal die zich afvraagt of de film, de stoelen en de zaal niet allemaal door hemzelf worden bedacht.",
  },
  {
    niveau: "expert",
    woord: "scheermes van Ockham",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het principe dat je, als verklaringen even goed passen, de voorkeur geeft aan de verklaring met de minste aannames.",
    voorbeeldzin: "Volgens het scheermes van Ockham is een tochtig raam een betere verklaring voor de klapperende deur dan een spook.",
    voorbeelden: [
      "Artsen passen het scheermes van Ockham toe door eerst naar de eenvoudigste diagnose te kijken.",
      "Het scheermes van Ockham is een vuistregel, geen bewijs.",
    ],
    herkomst: "Naar de Engelse monnik en filosoof Willem van Ockham (14e eeuw).",
    beeld: "Een scheermes dat alle overbodige haren van een theorie afschraapt, tot alleen het nodige overblijft.",
  },
  {
    niveau: "expert",
    woord: "falsifieerbaarheid",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De eigenschap van een bewering dat ze in principe door waarneming weerlegd kan worden; volgens Karl Popper een kenmerk van wetenschap.",
    voorbeeldzin: "'Alle zwanen zijn wit' voldoet aan falsifieerbaarheid: één zwarte zwaan kan de bewering weerleggen.",
    voorbeelden: [
      "Volgens Popper ontbreekt het de astrologie aan falsifieerbaarheid.",
      "Een goede hypothese heeft falsifieerbaarheid: je kunt aangeven wat haar zou weerleggen.",
    ],
    herkomst: "Latijn falsus (onwaar) + facere (maken).",
    beeld: "Een zwarte zwaan die triomfantelijk tussen honderd witte zwanen zwemt.",
  },
];
