import type { BankWoord } from "../woordenbank.ts";

export const maatschappij: BankWoord[] = [
  {
    niveau: "basis",
    woord: "anonimiteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het onbekend zijn van iemands naam of identiteit.",
    voorbeeldzin: "Op internet voelen sommige mensen zich door hun anonimiteit vrij om grof te reageren.",
    herkomst: "Grieks anōnymos (naamloos), van an (zonder) + onoma (naam).",
    beeld: "Iemand met een masker in een grote menigte, waar niemand zijn gezicht kent.",
  },
  {
    niveau: "basis",
    woord: "individualisering",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het proces waarbij mensen steeds meer hun eigen keuzes maken, los van tradities, kerk of familie.",
    voorbeeldzin: "Door de individualisering bepalen mensen zelf of ze trouwen, en met wie.",
    herkomst: "Latijn individuum (het ondeelbare).",
    beeld: "Een koor waarvan de zangers een voor een uit de rij stappen om hun eigen lied te zingen.",
  },
  {
    niveau: "basis",
    woord: "stigma",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een negatief etiket dat de samenleving op een persoon of groep plakt, waardoor die wordt afgewezen of achtergesteld.",
    voorbeeldzin: "Door het stigma rond psychische klachten zoeken veel mensen pas laat hulp.",
    herkomst: "Grieks stigma (brandmerk).",
    beeld: "Iemand met een rode stempel op zijn voorhoofd in een zaal waar iedereen wegkijkt.",
  },
  {
    niveau: "basis",
    woord: "segregatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De gedwongen of vrijwillige scheiding van bevolkingsgroepen, bijvoorbeeld in wijken of op scholen.",
    voorbeeldzin: "In sommige steden zie je segregatie tussen scholen: kinderen met verschillende achtergronden komen elkaar nauwelijks tegen.",
    herkomst: "Latijn segregare (afzonderen van de kudde).",
    beeld: "Een schoolplein met een onzichtbare lijn waar de kinderen van de ene groep nooit overheen lopen.",
  },
  {
    niveau: "gevorderd",
    woord: "anomie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een toestand van normloosheid, waarin gedeelde regels en waarden in een samenleving hun houvast verliezen.",
    voorbeeldzin: "Volgens de socioloog Émile Durkheim kan snelle maatschappelijke verandering tot anomie leiden.",
    herkomst: "Grieks anomia (wetteloosheid), van a (zonder) + nomos (wet).",
    beeld: "Een voetbalwedstrijd zonder scheidsrechter, lijnen of regels, waar iedereen maar wat doet.",
  },
  {
    niveau: "gevorderd",
    woord: "socialisatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het proces waarin iemand de normen, waarden en gewoonten van zijn samenleving aanleert.",
    voorbeeldzin: "Ouders, school en vrienden spelen een grote rol in de socialisatie van kinderen.",
    herkomst: "Latijn socius (makker, bondgenoot).",
    beeld: "Een jong katje dat van de oudere katten in de straat leert hoe het hoort.",
  },
  {
    niveau: "gevorderd",
    woord: "sociale cohesie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De mate van onderlinge verbondenheid en solidariteit tussen mensen in een groep of samenleving.",
    voorbeeldzin: "Een buurtfeest kan de sociale cohesie in de wijk versterken.",
    herkomst: "Latijn cohaerere (samenhangen).",
    beeld: "Een web van touwtjes tussen de huizen in een straat, waar alle bewoners aan meetrekken.",
  },
  {
    niveau: "gevorderd",
    woord: "sociale mobiliteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De mate waarin mensen in opleiding, inkomen of beroep kunnen stijgen of dalen ten opzichte van hun ouders.",
    voorbeeldzin: "Gratis onderwijs wordt vaak gezien als een motor van sociale mobiliteit.",
    herkomst: "Latijn mobilis (beweeglijk).",
    beeld: "Een lift in een flatgebouw waarmee kinderen hoger of lager uitstappen dan waar hun ouders wonen.",
  },
  {
    niveau: "gevorderd",
    woord: "secularisatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het proces waarbij religie en kerk minder invloed krijgen op de samenleving en op het leven van mensen.",
    voorbeeldzin: "Door de secularisatie zijn veel kerken in Nederland omgebouwd tot woningen of boekhandels.",
    herkomst: "Latijn saeculum (tijdperk, wereld), als tegenstelling tot het geestelijke.",
    beeld: "Een kerk waarin nu boekenkasten en een koffiebar staan.",
  },
  {
    niveau: "gevorderd",
    woord: "meritocratie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een samenleving waarin posities en beloningen worden verdeeld op basis van talent en prestatie in plaats van afkomst.",
    voorbeeldzin: "Critici stellen dat een meritocratie mensen zonder diploma het gevoel geeft dat ze tekortschieten.",
    herkomst: "Latijn meritum (verdienste) + Grieks kratos (macht).",
    beeld: "Een ladder waarop je alleen hoger komt door een examen te halen, ongeacht wie je ouders zijn.",
  },
  {
    niveau: "expert",
    woord: "verzuiling",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De indeling van de Nederlandse samenleving (ongeveer 1900-1960) in levensbeschouwelijke groepen met eigen partijen, scholen, omroepen en verenigingen.",
    voorbeeldzin: "Door de verzuiling ging een katholiek gezin naar een katholieke school, voetbalclub en omroep.",
    herkomst: "Van zuil: elke groep vormde een zuil die samen met de andere het dak van de staat droeg.",
    beeld: "Een tempeltje met vier zuilen, katholiek, protestants, socialistisch en liberaal, die samen één dak dragen.",
  },
  {
    niveau: "expert",
    woord: "gentrificatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het proces waarbij een arme stadswijk wordt opgeknapt en duurder wordt, waardoor oorspronkelijke bewoners vaak vertrekken.",
    voorbeeldzin: "Door gentrificatie zijn de huizenprijzen in de oude arbeiderswijk verdubbeld.",
    herkomst: "Engels gentry (lage adel, welgestelde burgerij).",
    beeld: "Een oud buurtcafé dat plaatsmaakt voor een koffiebar met havermelk voor zes euro.",
  },
  {
    niveau: "expert",
    woord: "participatiesamenleving",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een samenleving waarin van burgers wordt verwacht dat ze meer zelf verantwoordelijkheid nemen voor elkaar, in plaats van te leunen op de overheid.",
    voorbeeldzin: "In de troonrede van 2013 werd de participatiesamenleving aangekondigd.",
    herkomst: "Latijn participare (deelnemen).",
    beeld: "Een buurman die het gras van een zieke buurvrouw maait, omdat de gemeente dat niet meer doet.",
  },
];
