import type { BankWoord } from "../woordenbank.ts";

export const natuurkunde: BankWoord[] = [
  {
    niveau: "basis",
    woord: "inertie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Traagheid: de neiging van een voorwerp om in rust of in beweging te blijven zolang er geen kracht op werkt.",
    voorbeeldzin: "Door inertie schiet je naar voren als de bus plotseling remt.",
    herkomst: "Latijn iners (traag, inactief).",
    beeld: "Een ijshockeypuck die over het ijs blijft glijden en weigert te stoppen.",
    emoji: "🏒🧊",
  },
  {
    niveau: "basis",
    woord: "frequentie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het aantal trillingen of herhalingen per seconde, uitgedrukt in hertz.",
    voorbeeldzin: "Een geluid met een hogere frequentie hoor je als een hogere toon.",
    herkomst: "Latijn frequens (talrijk, vaak voorkomend).",
    beeld: "Een kolibrie die zo vaak per seconde met zijn vleugels slaat dat ze zoemen.",
    emoji: "🐦〰️",
  },
  {
    niveau: "basis",
    woord: "condensatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De overgang van een gas naar een vloeistof, bijvoorbeeld als waterdamp afkoelt.",
    voorbeeldzin: "Door condensatie verschijnen er druppels op de buitenkant van een koud glas.",
    herkomst: "Latijn condensare (verdichten).",
    beeld: "Een badkamerspiegel die na een warme douche langzaam beslaat.",
    emoji: "🚿🪞",
  },
  {
    niveau: "basis",
    woord: "geleider",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een materiaal waar elektrische stroom of warmte gemakkelijk doorheen kan.",
    voorbeeldzin: "Koper is een goede geleider en wordt daarom in elektriciteitskabels gebruikt.",
    herkomst: "Van het werkwoord geleiden (doorvoeren, leiden).",
    beeld: "Een brede snelweg waarover elektronen zonder file voortrazen.",
    emoji: "🛣️⚡",
  },
  {
    niveau: "basis",
    woord: "brandpunt",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het punt waar evenwijdige lichtstralen samenkomen nadat ze door een lens zijn gebroken of door een holle spiegel zijn teruggekaatst.",
    voorbeeldzin: "Met een vergrootglas kun je zonlicht in het brandpunt zo sterk bundelen dat papier gaat smeulen.",
    herkomst: "Letterlijk: het punt waar het brandt.",
    beeld: "Een vergrootglas dat een felle stip zonlicht op een blad papier laat roken.",
    emoji: "🔍🔥",
  },
  {
    niveau: "gevorderd",
    woord: "entropie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een maat voor de wanorde van een systeem; in een afgesloten systeem neemt ze nooit af.",
    voorbeeldzin: "Dat een gebroken kopje nooit vanzelf weer heel wordt, heeft te maken met entropie.",
    herkomst: "Grieks en (in) + tropè (verandering); bedacht door de Duitse natuurkundige Rudolf Clausius.",
    beeld: "Een opgeruimde kamer die zonder dat iemand iets doet steeds rommeliger lijkt te worden.",
    emoji: "🧹🌀",
  },
  {
    niveau: "gevorderd",
    woord: "impuls",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De hoeveelheid beweging van een voorwerp: massa maal snelheid.",
    voorbeeldzin: "Bij een botsing blijft de totale impuls van de biljartballen behouden.",
    herkomst: "Latijn impellere (voortstuwen).",
    beeld: "Een zware vrachtwagen en een razendsnelle tennisbal die allebei lastig te stoppen zijn.",
    emoji: "🚚🎾",
  },
  {
    niveau: "gevorderd",
    woord: "halfwaardetijd",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De tijd waarin de helft van een hoeveelheid radioactieve atoomkernen vervalt.",
    voorbeeldzin: "Koolstof-14 heeft een halfwaardetijd van ongeveer 5730 jaar.",
    herkomst: "Samenstelling van half, waarde en tijd.",
    beeld: "Een zak snoep waaruit elke vijf minuten de helft verdwijnt, maar die nooit helemaal leeg raakt.",
    emoji: "🍬⏳",
  },
  {
    niveau: "gevorderd",
    woord: "interferentie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het verschijnsel dat golven elkaar versterken of uitdoven wanneer ze samenkomen.",
    voorbeeldzin: "De kleuren op een zeepbel ontstaan door interferentie van licht.",
    herkomst: "Latijn inter (tussen) + ferire (slaan).",
    beeld: "Twee stenen in een vijver waarvan de kringen elkaar kruisen, zodat het water op sommige plekken hoger en op andere vlak wordt.",
    emoji: "🪨💧",
  },
  {
    niveau: "gevorderd",
    woord: "supergeleiding",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het verschijnsel dat sommige materialen bij zeer lage temperatuur stroom geleiden zonder enige weerstand.",
    voorbeeldzin: "MRI-scanners gebruiken supergeleidende magneten die met vloeibaar helium worden gekoeld.",
    herkomst: "Ontdekt in 1911 door de Nederlandse natuurkundige Heike Kamerlingh Onnes in Leiden.",
    beeld: "Een ijskoude glijbaan waarop elektronen eindeloos doorglijden zonder ooit af te remmen.",
    emoji: "🛝❄️",
  },
  {
    niveau: "expert",
    woord: "kwantumverstrengeling",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een verschijnsel waarbij deeltjes zo verbonden zijn dat hun toestanden niet los van elkaar te beschrijven zijn, ongeacht de afstand.",
    voorbeeldzin: "Onderzoekers in Delft toonden in 2015 kwantumverstrengeling aan tussen deeltjes die ruim een kilometer uit elkaar lagen.",
    herkomst: "Vertaling van het Duitse Verschränkung, een term van Erwin Schrödinger.",
    beeld: "Twee dobbelstenen in verschillende steden die, als je ze gooit, altijd bij elkaar passende uitkomsten geven.",
    emoji: "🎲🎲",
  },
  {
    niveau: "expert",
    woord: "golf-deeltjedualiteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het inzicht dat licht en materie zich, afhankelijk van het experiment, als golf of als deeltje gedragen.",
    voorbeeldzin: "Het dubbelspleetexperiment met elektronen laat de golf-deeltjedualiteit zien.",
    herkomst: "Latijn dualis (tweeledig).",
    beeld: "Een kameleon die de ene keer als rimpeling door het water gaat en de andere keer als knikker over de vloer rolt.",
    emoji: "🦎〰️",
  },
  {
    niveau: "expert",
    woord: "tijddilatatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het effect uit de relativiteitstheorie dat tijd langzamer verstrijkt bij hoge snelheid of sterke zwaartekracht, gezien door een andere waarnemer.",
    voorbeeldzin: "Gps-satellieten moeten corrigeren voor tijddilatatie, anders wordt de plaatsbepaling snel onnauwkeurig.",
    herkomst: "Latijn dilatare (uitrekken).",
    beeld: "Een astronaut die na een razendsnelle ruimtereis terugkomt en jonger is dan zijn tweelingbroer.",
    emoji: "🚀👴",
  },
  {
    niveau: "expert",
    woord: "lagrangepunt",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een punt in de ruimte waar een klein object door de zwaartekracht van twee grote hemellichamen op een vaste plek ten opzichte van beide kan blijven.",
    voorbeeldzin: "De James Webb-ruimtetelescoop draait rond het tweede lagrangepunt van de zon en de aarde.",
    herkomst: "Naar de wiskundige Joseph-Louis Lagrange (18e eeuw).",
    beeld: "Een ballon die precies tussen twee magneten blijft zweven.",
    emoji: "🎈🧲",
  },
  {
    niveau: "expert",
    woord: "neutrino",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een elektrisch neutraal elementair deeltje met een extreem kleine massa, dat bijna nergens mee reageert.",
    voorbeeldzin: "Elke seconde gaan er miljarden neutrino's van de zon dwars door je lichaam heen.",
    herkomst: "Italiaans voor 'klein neutraaltje'; de naam komt van Enrico Fermi.",
    beeld: "Een onzichtbaar spookje dat dwars door muren, mensen en zelfs de hele aarde heen vliegt.",
    emoji: "👻🌍",
  },
  {
    niveau: "basis",
    woord: "zwaartepunt",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het punt waarin je je de hele massa van een voorwerp geconcentreerd kunt denken; ondersteun je het daar, dan blijft het in evenwicht.",
    voorbeeldzin: "Een koorddanser houdt zijn zwaartepunt precies boven het touw.",
    herkomst: "Samenstelling van zwaarte en punt.",
    beeld: "Een bord dat op de punt van één vinger balanceert.",
    emoji: "🍽️☝️",
  },
  {
    niveau: "basis",
    woord: "aggregatietoestand",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De vorm waarin een stof voorkomt: vast, vloeibaar of gas.",
    voorbeeldzin: "Water kan in drie aggregatietoestanden voorkomen: ijs, water en waterdamp.",
    herkomst: "Latijn aggregare (samenvoegen, tot een kudde bijeenbrengen).",
    beeld: "Een ijsblokje, een glas water en een wolkje stoom die als drie familieleden naast elkaar staan.",
    emoji: "🧊💧",
  },
  {
    niveau: "gevorderd",
    woord: "elektromagnetische straling",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Energie die zich voortplant als golven van elektrische en magnetische velden, zoals licht, radiogolven en röntgenstraling.",
    voorbeeldzin: "Een magnetron verwarmt eten met elektromagnetische straling.",
    herkomst: "Grieks èlektron (barnsteen) + magnès (magneetsteen).",
    beeld: "Een regenboog die aan beide kanten doorloopt in onzichtbare kleuren, van radiogolven tot röntgenstraling.",
    emoji: "🌈📡",
  },
  {
    niveau: "gevorderd",
    woord: "kernfusie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het samensmelten van lichte atoomkernen tot een zwaardere kern, waarbij enorm veel energie vrijkomt.",
    voorbeeldzin: "De zon haalt haar energie uit kernfusie van waterstof tot helium.",
    herkomst: "Latijn fusio (het smelten).",
    beeld: "Twee druppels die met een lichtflits tegen elkaar botsen en één grotere druppel worden.",
    emoji: "💥☀️",
  },
  {
    niveau: "expert",
    woord: "waarnemingshorizon",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De grens rond een zwart gat waarachter niets, zelfs geen licht, nog kan ontsnappen.",
    voorbeeldzin: "Wat eenmaal de waarnemingshorizon passeert, is voor de buitenwereld voorgoed onzichtbaar.",
    herkomst: "Samenstelling van waarneming en horizon (Grieks horizōn: begrenzend).",
    beeld: "De rand van een reusachtige waterval waarachter geen enkele boot ooit nog terug stroomopwaarts kan.",
    emoji: "🕳️🌊",
  },
];
