import type { BankWoord } from "../woordenbank.ts";

// Woorden uit het leerpad "Een korte geschiedenis van de tijd" (Stephen Hawking).
// Ze horen bij het vakgebied Natuurkunde en komen daar ook gewoon voor in de gewone rondes.
export const natuurkundeHawking: BankWoord[] = [
  {
    niveau: "gevorderd",
    woord: "ruimtetijd",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De drie richtingen van de ruimte en de tijd samen gezien als één vierdimensionaal geheel, dat kan krommen.",
    voorbeeldzin: "Volgens Einstein buigt een zware ster de ruimtetijd om zich heen.",
    voorbeelden: [
      "Een gebeurtenis heeft in de ruimtetijd een plek én een moment.",
      "Zwaartekrachtsgolven zijn rimpelingen in de ruimtetijd.",
    ],
    herkomst: "Samenstelling van ruimte en tijd; vertaling van het Duitse Raumzeit.",
    beeld: "Een strak gespannen trampoline waarop een bowlingbal een kuil maakt waar knikkers in rollen.",
  },
  {
    niveau: "gevorderd",
    woord: "relativiteitstheorie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Einsteins theorie dat afstanden en tijdsduur afhangen van de beweging van de waarnemer, en dat zwaartekracht een kromming van ruimte en tijd is.",
    voorbeeldzin: "Zonder de relativiteitstheorie zou je navigatie in de auto flink de weg kwijtraken.",
    voorbeelden: [
      "De relativiteitstheorie voorspelde dat licht afbuigt langs de zon.",
      "Einstein publiceerde de algemene relativiteitstheorie in 1915.",
    ],
    herkomst: "Latijn relativus (in verhouding tot iets) + Grieks theōria (beschouwing).",
    beeld: "Twee reizigers in verschillende treinen die het oneens zijn over hoe laat het is, en allebei gelijk hebben.",
  },
  {
    niveau: "basis",
    woord: "lichtsnelheid",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De snelheid waarmee licht zich in vacuüm voortbeweegt, ongeveer 300.000 kilometer per seconde; niets gaat sneller.",
    voorbeeldzin: "Zelfs met de lichtsnelheid doe je er ruim acht minuten over om van de zon naar de aarde te reizen.",
    voorbeelden: [
      "Geen ruimteschip kan ooit de lichtsnelheid bereiken.",
      "De lichtsnelheid is voor elke waarnemer hetzelfde, hoe snel die zelf ook gaat.",
    ],
    herkomst: "Samenstelling van licht en snelheid.",
    beeld: "Een lichtstraal die in één seconde zeven keer rond de aarde flitst.",
  },
  {
    niveau: "expert",
    woord: "lichtkegel",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het deel van ruimte en tijd dat een gebeurtenis kan beïnvloeden of erdoor beïnvloed kan worden, begrensd door de weg die een lichtflits aflegt.",
    voorbeeldzin: "Een ster die buiten onze lichtkegel ontploft, kan ons op dit moment nog niet raken.",
    voorbeelden: [
      "Hawking tekent de toekomst van een gebeurtenis als een lichtkegel die zich naar boven opent.",
      "Alles wat oorzaak kan zijn van jouw heden, ligt in je verleden-lichtkegel.",
    ],
    herkomst: "Samenstelling van licht en kegel.",
    beeld: "Een steen in een vijver: de kring die zich uitbreidt, maar dan als een ijshoorntje door de tijd getekend.",
  },
  {
    niveau: "basis",
    woord: "zwaartekracht",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De kracht waarmee voorwerpen met massa elkaar aantrekken; zij houdt planeten in hun baan en jou op de grond.",
    voorbeeldzin: "Door de zwaartekracht valt een appel naar beneden en niet omhoog.",
    voorbeelden: [
      "Op de maan is de zwaartekracht zes keer zwakker dan op aarde.",
      "De zwaartekracht van de maan veroorzaakt eb en vloed.",
    ],
    herkomst: "Samenstelling van zwaarte en kracht; Newton beschreef haar als eerste wiskundig.",
    beeld: "Een onzichtbaar elastiekje tussen de aarde en elke appel aan de boom.",
  },
  {
    niveau: "basis",
    woord: "oerknal",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het begin van het heelal, ongeveer 13,8 miljard jaar geleden, toen alles extreem heet en dicht op elkaar zat en begon uit te dijen.",
    voorbeeldzin: "Kort na de oerknal bestond het heelal alleen uit een gloeiend hete soep van deeltjes.",
    voorbeelden: [
      "Volgens de theorie van de oerknal was er daarvoor geen 'daarvoor'.",
      "De eerste atomen ontstonden pas honderdduizenden jaren na de oerknal.",
    ],
    herkomst: "Vertaling van het Engelse Big Bang, een spotnaam van Fred Hoyle uit 1949.",
    beeld: "Een rozijnenbrood dat in de oven begint te rijzen, waarbij de rozijnen van elkaar weg schuiven.",
  },
  {
    niveau: "gevorderd",
    woord: "roodverschuiving",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het verschuiven van licht naar langere golflengtes als de bron zich van ons af beweegt, waardoor het roder lijkt.",
    voorbeeldzin: "Uit de roodverschuiving van verre sterrenstelsels bleek dat het heelal uitdijt.",
    voorbeelden: [
      "Hoe verder een sterrenstelsel staat, hoe groter zijn roodverschuiving.",
      "Hubble mat de roodverschuiving van tientallen nevels.",
    ],
    herkomst: "Samenstelling van rood en verschuiving; vergelijk het Engelse redshift.",
    beeld: "De sirene van een ambulance die lager klinkt zodra hij voorbij is, maar dan met kleur in plaats van geluid.",
  },
  {
    niveau: "expert",
    woord: "kosmische achtergrondstraling",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Zwakke microgolfstraling die uit alle richtingen komt: het afgekoelde nagloeien van het jonge, hete heelal.",
    voorbeeldzin: "De ontdekking van de kosmische achtergrondstraling in 1965 was een sterk bewijs voor de oerknal.",
    voorbeelden: [
      "Een deel van de ruis op een oude analoge tv kwam van de kosmische achtergrondstraling.",
      "Satellieten brachten de kosmische achtergrondstraling tot in detail in kaart.",
    ],
    herkomst: "Grieks kosmos (wereldorde) + achtergrond + straling.",
    beeld: "De warmte die nog uit een oven komt, uren nadat het brood eruit is gehaald.",
  },
  {
    niveau: "gevorderd",
    woord: "uitdijing",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het groter worden van het heelal, waardoor sterrenstelsels steeds verder van elkaar af komen te staan.",
    voorbeeldzin: "De uitdijing van het heelal lijkt de laatste miljarden jaren zelfs te versnellen.",
    voorbeelden: [
      "Hubble ontdekte in 1929 de uitdijing van het heelal.",
      "Door de uitdijing wordt het licht van verre stelsels uitgerekt.",
    ],
    herkomst: "Van het werkwoord uitdijen (zwellen, groter worden).",
    beeld: "Een ballon met stippen erop die je opblaast: elke stip ziet alle andere van zich af bewegen.",
  },
  {
    niveau: "expert",
    woord: "singulariteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een punt waar dichtheid en kromming oneindig groot worden en de bekende natuurwetten niet meer werken.",
    voorbeeldzin: "Hawking en Penrose lieten zien dat het heelal volgens de relativiteitstheorie met een singulariteit moet zijn begonnen.",
    voorbeelden: [
      "In het midden van een zwart gat zit volgens de theorie een singulariteit.",
      "Bij een singulariteit breken de formules van de natuurkunde af.",
    ],
    herkomst: "Latijn singularis (enkelvoudig, uniek).",
    beeld: "Een landkaart met een gat erin waar de kaartenmaker 'hier houdt alles op' heeft geschreven.",
  },
  {
    niveau: "basis",
    woord: "sterrenstelsel",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een enorme verzameling van miljarden sterren, gas en stof die door de zwaartekracht bij elkaar wordt gehouden.",
    voorbeeldzin: "Onze zon is een van de honderden miljarden sterren in het sterrenstelsel de Melkweg.",
    voorbeelden: [
      "Het dichtstbijzijnde grote sterrenstelsel is de Andromedanevel.",
      "Met een telescoop zie je dat een sterrenstelsel vaak een spiraalvorm heeft.",
    ],
    herkomst: "Samenstelling van sterren en stelsel (samenhangend geheel).",
    beeld: "Een draaikolk van glitters in een glazen bol die je net hebt geschud.",
  },
  {
    niveau: "basis",
    woord: "zwart gat",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een gebied in de ruimte waar de zwaartekracht zo sterk is dat niets, zelfs geen licht, eruit kan ontsnappen.",
    voorbeeldzin: "In het centrum van de Melkweg zit een zwart gat dat miljoenen keren zwaarder is dan de zon.",
    voorbeelden: [
      "In 2019 werd voor het eerst een foto gemaakt van de schaduw van een zwart gat.",
      "Een zwart gat ontstaat als een zware ster onder zijn eigen gewicht ineenstort.",
    ],
    herkomst: "Vertaling van black hole, een term die John Wheeler in 1967 populair maakte.",
    beeld: "Een afvoerputje in een badkuip waar alles in verdwijnt en niets meer uit terugkomt.",
  },
  {
    niveau: "expert",
    woord: "hawkingstraling",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De zwakke straling die zwarte gaten volgens kwantumeffecten uitzenden, waardoor ze heel langzaam verdampen.",
    voorbeeldzin: "Door hawkingstraling zou zelfs een zwart gat na onvoorstelbaar lange tijd verdwijnen.",
    voorbeelden: [
      "Hawkingstraling is zo zwak dat niemand haar ooit rechtstreeks heeft gemeten.",
      "Met de hawkingstraling bracht Hawking de relativiteitstheorie en de kwantummechanica samen.",
    ],
    herkomst: "Naar Stephen Hawking, die haar in 1974 voorspelde.",
    beeld: "Een ijsblok in een diepvries dat toch, druppel voor druppel, heel langzaam wegsmelt.",
  },
  {
    niveau: "gevorderd",
    woord: "neutronenster",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het extreem dichte overblijfsel van een zware ster die is ontploft, bijna helemaal opgebouwd uit neutronen.",
    voorbeeldzin: "Een theelepel materiaal van een neutronenster zou op aarde miljarden kilo's wegen.",
    voorbeelden: [
      "Een neutronenster is niet groter dan een stad, maar zwaarder dan de zon.",
      "Sommige neutronensterren draaien honderden keren per seconde rond.",
    ],
    herkomst: "Samenstelling van neutron (Latijn neuter: geen van beide) en ster.",
    beeld: "De hele zon samengeperst tot een bal zo groot als Amsterdam.",
  },
  {
    niveau: "gevorderd",
    woord: "witte dwerg",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De kleine, hete kern die overblijft als een ster zoals de zon aan het eind van haar leven haar buitenlagen afstoot.",
    voorbeeldzin: "Over miljarden jaren eindigt onze zon als een witte dwerg.",
    voorbeelden: [
      "Een witte dwerg is ongeveer zo groot als de aarde maar veel zwaarder.",
      "Een witte dwerg koelt heel langzaam af en straalt steeds zwakker.",
    ],
    herkomst: "Naar de witte kleur en het kleine formaat; vertaling van het Engelse white dwarf.",
    beeld: "Het laatste gloeiende kooltje in een kampvuur nadat de vlammen gedoofd zijn.",
  },
  {
    niveau: "basis",
    woord: "supernova",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De enorme explosie van een zware ster aan het eind van haar leven, die tijdelijk feller schijnt dan een heel sterrenstelsel.",
    voorbeeldzin: "In 1054 zagen Chinese sterrenkundigen een supernova die zelfs overdag zichtbaar was.",
    voorbeelden: [
      "Het ijzer in je bloed is ooit gemaakt in een supernova.",
      "Na een supernova blijft soms een neutronenster achter.",
    ],
    herkomst: "Latijn super (boven) + nova (nieuw), omdat het leek alsof er een nieuwe ster verscheen.",
    beeld: "Een vuurwerkbom die het hele nachtelijke plein even in daglicht zet.",
  },
  {
    niveau: "gevorderd",
    woord: "kwantummechanica",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De natuurkundige theorie die het gedrag van de allerkleinste deeltjes beschrijft, waarin uitkomsten alleen als kansen te voorspellen zijn.",
    voorbeeldzin: "Zonder kwantummechanica zouden we geen lasers, chips of mri-scanners hebben.",
    voorbeelden: [
      "Einstein had moeite met de kansrekening in de kwantummechanica.",
      "Volgens de kwantummechanica kan een deeltje op meerdere plekken tegelijk lijken te zijn.",
    ],
    herkomst: "Latijn quantum (hoeveel) + Grieks mèchanè (werktuig).",
    beeld: "Een dobbelsteen die pas besluit welk getal hij toont op het moment dat je kijkt.",
  },
  {
    niveau: "expert",
    woord: "onzekerheidsprincipe",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De regel dat je van een deeltje niet tegelijk de plaats en de snelheid precies kunt kennen: hoe beter het een, hoe vager het ander.",
    voorbeeldzin: "Door het onzekerheidsprincipe kun je de toekomst van een deeltje nooit helemaal precies voorspellen.",
    voorbeelden: [
      "Heisenberg formuleerde het onzekerheidsprincipe in 1927.",
      "Het onzekerheidsprincipe ligt niet aan slechte meetapparatuur, maar aan de natuur zelf.",
    ],
    herkomst: "Vertaling van het Duitse Unschärferelation van Werner Heisenberg.",
    beeld: "Een foto van een rennende hond: of scherp maar zonder beweging, of bewogen maar zonder scherpe plek.",
  },
  {
    niveau: "expert",
    woord: "virtuele deeltjes",
    woordsoort: "zelfstandig naamwoord (meervoud)",
    definitie: "Paren van deeltjes en antideeltjes die volgens de kwantumtheorie heel even uit het niets opduiken en elkaar weer opheffen.",
    voorbeeldzin: "Hawking legde zijn straling uit met virtuele deeltjes die vlak bij een zwart gat ontstaan.",
    voorbeelden: [
      "Lege ruimte is volgens natuurkundigen vol virtuele deeltjes.",
      "Virtuele deeltjes bestaan te kort om rechtstreeks te zien.",
    ],
    herkomst: "Latijn virtualis (in aanleg aanwezig) + deeltje.",
    beeld: "Bubbeltjes in een glas spuitwater die opploppen en meteen weer verdwijnen.",
  },
  {
    niveau: "gevorderd",
    woord: "theorie van alles",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een nog niet gevonden theorie die alle natuurkrachten en deeltjes in één samenhangende beschrijving vangt.",
    voorbeeldzin: "Hawking hoopte dat een theorie van alles ons zou vertellen waarom het heelal bestaat.",
    voorbeelden: [
      "Snaartheorie is een kandidaat voor een theorie van alles.",
      "Een theorie van alles moet de relativiteitstheorie en de kwantummechanica verenigen.",
    ],
    herkomst: "Vertaling van het Engelse theory of everything.",
    beeld: "Eén sleutel die op elke deur van een enorm kasteel past.",
  },
  {
    niveau: "gevorderd",
    woord: "antimaterie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Materie opgebouwd uit deeltjes met dezelfde massa als gewone deeltjes maar een tegengestelde lading; bij contact vernietigen ze elkaar.",
    voorbeeldzin: "Als antimaterie gewone materie raakt, verdwijnen ze allebei in een flits van energie.",
    voorbeelden: [
      "Het is een raadsel waarom er na de oerknal meer materie dan antimaterie overbleef.",
      "In het CERN maken onderzoekers kleine hoeveelheden antimaterie.",
    ],
    herkomst: "Grieks anti (tegen) + Latijn materia (stof).",
    beeld: "Een spiegelbeeld dat uit de spiegel stapt en bij een handdruk met jou in licht opgaat.",
  },
];
