import type { BankWoord } from "../woordenbank.ts";

export const politiekeStromingen: BankWoord[] = [
  {
    niveau: "basis",
    woord: "ideologie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een samenhangend geheel van ideeën en waarden over hoe de samenleving eruit zou moeten zien.",
    voorbeeldzin: "Liberalisme, socialisme en conservatisme worden vaak de drie klassieke politieke ideologieën genoemd.",
    herkomst: "Grieks idea (denkbeeld) + logos (leer).",
    beeld: "Een bouwtekening die laat zien hoe het huis van de samenleving eruit moet komen te zien.",
    emoji: "📐🏠",
  },
  {
    niveau: "basis",
    woord: "liberalisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een politieke stroming die individuele vrijheid, gelijke rechten en een beperkte rol van de overheid vooropstelt.",
    voorbeeldzin: "Vrijheid van meningsuiting en een vrije markt zijn kernwaarden van het liberalisme.",
    herkomst: "Latijn liber (vrij).",
    beeld: "Een open vogelkooi waaruit vogels vrij hun eigen kant op vliegen.",
    emoji: "🕊️🔓",
  },
  {
    niveau: "basis",
    woord: "conservatisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een politieke stroming die hecht aan bestaande tradities en instituties en alleen geleidelijke, voorzichtige verandering wil.",
    voorbeeldzin: "Het conservatisme wantrouwt snelle, radicale hervormingen.",
    herkomst: "Latijn conservare (bewaren).",
    beeld: "Een tuinman die een eeuwenoude eik zorgvuldig snoeit in plaats van hem om te hakken.",
    emoji: "🌳✂️",
  },
  {
    niveau: "basis",
    woord: "socialisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een politieke stroming die streeft naar gelijkheid en solidariteit, bijvoorbeeld via herverdeling, een sterke overheid en gemeenschappelijk eigendom.",
    voorbeeldzin: "De opkomst van het socialisme in de 19e eeuw hing samen met de slechte omstandigheden van fabrieksarbeiders.",
    herkomst: "Latijn socius (makker, bondgenoot).",
    beeld: "Een grote pan soep waaruit iedereen een even grote kom krijgt.",
    emoji: "🍲🥣",
  },
  {
    niveau: "basis",
    woord: "communisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een ideologie, gebaseerd op het werk van Karl Marx, die streeft naar een klasseloze samenleving waarin de productiemiddelen gemeenschappelijk bezit zijn.",
    voorbeeldzin: "In de 20e eeuw werd het communisme de staatsideologie van onder meer de Sovjet-Unie en China.",
    herkomst: "Latijn communis (gemeenschappelijk).",
    beeld: "Een fabriek met boven de poort een bordje: 'Van ons allemaal'.",
    emoji: "🏭⚒️",
  },
  {
    niveau: "basis",
    woord: "fascisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een extreemrechtse, autoritaire ideologie die de natie verheerlijkt, draait om een sterke leider en oppositie en democratie onderdrukt.",
    voorbeeldzin: "Het fascisme kwam in 1922 in Italië aan de macht onder Benito Mussolini.",
    herkomst: "Italiaans fascio (bundel), naar de Romeinse fasces: een bundel roeden als symbool van gezag.",
    beeld: "Een bundel stokken die samengebonden onbreekbaar is, vastgehouden door één man die alle touwtjes in handen heeft.",
    emoji: "🪵👊",
  },
  {
    niveau: "basis",
    woord: "nationalisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een stroming die de eigen natie centraal stelt en streeft naar de eenheid, zelfstandigheid en belangen van dat volk.",
    voorbeeldzin: "Het nationalisme speelde een grote rol bij het uiteenvallen van Joegoslavië.",
    herkomst: "Latijn natio (volk, geboorte).",
    beeld: "Een menigte die alleen vlaggen van het eigen land zwaait, terwijl de grenzen met hekken worden afgebakend.",
    emoji: "🚩🧱",
  },
  {
    niveau: "basis",
    woord: "progressief",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Gericht op vooruitgang en maatschappelijke hervorming, vaak op het gebied van gelijkheid, milieu of individuele rechten.",
    voorbeeldzin: "De progressieve partijen pleitten al vroeg voor het openstellen van het huwelijk voor paren van hetzelfde geslacht.",
    herkomst: "Latijn progredi (voortschrijden).",
    beeld: "Een groep mensen die een oude muur afbreekt en er een brug voor in de plaats bouwt.",
    emoji: "🧱🌉",
  },
  {
    niveau: "gevorderd",
    woord: "anarchisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een politieke stroming die elke vorm van opgelegd gezag, zoals de staat, wil afschaffen ten gunste van vrijwillige samenwerking.",
    voorbeeldzin: "Anarchisme wordt vaak verward met chaos, maar veel anarchisten streven juist naar georganiseerd zelfbestuur.",
    herkomst: "Grieks an (zonder) + archè (heerschappij).",
    beeld: "Een dorp zonder burgemeester of politie, waar de bewoners samen aan één lange tafel beslissen.",
    emoji: "🏘️🪑",
  },
  {
    niveau: "gevorderd",
    woord: "sociaaldemocratie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een stroming die sociale gelijkheid nastreeft binnen een democratie en een markteconomie, onder meer via een verzorgingsstaat.",
    voorbeeldzin: "De Scandinavische landen gelden vaak als voorbeeld van sociaaldemocratie.",
    herkomst: "Samenstelling van sociaal en democratie.",
    beeld: "Een marktplein vol kraampjes, waar de gemeente ervoor zorgt dat niemand zonder boodschappen naar huis gaat.",
    emoji: "🏪🛟",
  },
  {
    niveau: "gevorderd",
    woord: "christendemocratie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een politieke stroming die haar beleid baseert op christelijke waarden, zoals rentmeesterschap, solidariteit en de rol van gezin en maatschappelijke organisaties.",
    voorbeeldzin: "Het CDA is de bekendste partij van de christendemocratie in Nederland.",
    herkomst: "Samenstelling van christelijk en democratie.",
    beeld: "Een huis waarvan gezinnen, verenigingen en kerken samen de dragende muren vormen.",
    emoji: "🏠✝️",
  },
  {
    niveau: "gevorderd",
    woord: "kapitalisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een economisch systeem waarin productiemiddelen privébezit zijn en prijzen en productie grotendeels via de vrije markt tot stand komen.",
    voorbeeldzin: "In het kapitalisme bepaalt de concurrentie tussen bedrijven grotendeels wat er geproduceerd wordt.",
    herkomst: "Via kapitaal (vermogen), van Latijn capitalis (hoofd-).",
    beeld: "Een drukke markt waar iedereen zijn eigen kraam heeft en de klanten bepalen wie blijft.",
    emoji: "🏪💶",
  },
  {
    niveau: "gevorderd",
    woord: "autoritarisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een bestuursvorm waarin de macht bij één leider of een kleine groep ligt, met weinig ruimte voor oppositie, vrije pers of eerlijke verkiezingen.",
    voorbeeldzin: "Na de staatsgreep gleed het land steeds verder af richting autoritarisme.",
    herkomst: "Latijn auctoritas (gezag).",
    beeld: "Een klaslokaal waar alleen de leraar mag praten en elke vraag verboden is.",
    emoji: "🏫🤐",
  },
  {
    niveau: "gevorderd",
    woord: "totalitarisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een uiterste vorm van dictatuur waarin de staat vrijwel alle aspecten van het leven wil beheersen, ook het denken van burgers.",
    voorbeeldzin: "George Orwells roman 1984 beschrijft een totalitaire staat.",
    herkomst: "Italiaans totalitario, van Latijn totus (geheel).",
    beeld: "Een camera in elke kamer en een luidspreker die voorschrijft wat je moet denken.",
    emoji: "📹📢",
  },
  {
    niveau: "gevorderd",
    woord: "reactionair",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Strevend naar het terugdraaien van maatschappelijke veranderingen en het herstel van een vroegere toestand.",
    voorbeeldzin: "Na de revolutie probeerden reactionaire krachten de oude monarchie te herstellen.",
    herkomst: "Frans réaction (terugwerking).",
    beeld: "Iemand die met beide handen de wijzers van de klok terugdraait.",
    emoji: "🕰️↩️",
  },
  {
    niveau: "expert",
    woord: "libertarisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een stroming die maximale individuele vrijheid nastreeft en de overheid wil beperken tot een minimum, zoals politie, rechtspraak en defensie.",
    voorbeeldzin: "Veel aanhangers van het libertarisme zien belastingen als een inbreuk op het eigendomsrecht.",
    herkomst: "Engels libertarian, van Latijn libertas (vrijheid).",
    beeld: "Een nachtwaker die alleen rondloopt om inbrekers te weren en zich verder nergens mee bemoeit.",
    emoji: "🔦🌙",
  },
  {
    niveau: "expert",
    woord: "neoliberalisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een stroming vanaf de jaren zeventig die inzet op vrije markten, privatisering, deregulering en een kleinere rol van de overheid in de economie.",
    voorbeeldzin: "Het beleid van Thatcher en Reagan wordt vaak als neoliberalisme omschreven.",
    herkomst: "Grieks neos (nieuw) + liberalisme.",
    beeld: "Een overheid die de sleutels van het spoor, de post en de energiebedrijven overhandigt aan private ondernemers.",
    emoji: "🔑🚆",
  },
  {
    niveau: "expert",
    woord: "marxisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De theorie van Karl Marx en Friedrich Engels die de geschiedenis verklaart als een strijd tussen sociale klassen en het kapitalisme bekritiseert.",
    voorbeeldzin: "Het marxisme ziet de tegenstelling tussen arbeiders en kapitaalbezitters als drijvende kracht van de geschiedenis.",
    herkomst: "Naar Karl Marx (1818-1883).",
    beeld: "Een touwtrekwedstrijd die door de eeuwen heen doorgaat, tussen fabriekseigenaren en arbeiders.",
    emoji: "🪢⚒️",
  },
  {
    niveau: "expert",
    woord: "pluralisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het uitgangspunt dat verschillende groepen, opvattingen en belangen naast elkaar bestaan en allemaal ruimte krijgen in samenleving en politiek.",
    voorbeeldzin: "Een vrije pers met kranten van links tot rechts is een teken van pluralisme.",
    herkomst: "Latijn pluralis (meervoudig).",
    beeld: "Een tuin met honderden verschillende bloemen die allemaal evenveel zon krijgen.",
    emoji: "🌷🌻",
  },
];
