import type { BankWoord } from "../woordenbank.ts";

export const politiek: BankWoord[] = [
  {
    niveau: "basis",
    woord: "coalitie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een samenwerkingsverband van meerdere politieke partijen die samen een regering vormen of steunen.",
    voorbeeldzin: "Na de verkiezingen duurde het maanden voordat er een coalitie was gevormd.",
    herkomst: "Latijn coalescere (samengroeien).",
    beeld: "Vier roeiers in verschillend gekleurde shirts die in één bootje proberen dezelfde kant op te roeien.",
  },
  {
    niveau: "basis",
    woord: "motie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een voorstel van Kamerleden waarin de Kamer een wens of oordeel uitspreekt, bijvoorbeeld een verzoek aan de regering.",
    voorbeeldzin: "De Kamer nam een motie aan die het kabinet vraagt de huurverhoging te bevriezen.",
    herkomst: "Latijn motio (beweging).",
    beeld: "Een Kamerlid dat een papieren vliegtuigje met 'Graag regelen!' erop naar de ministers gooit.",
  },
  {
    niveau: "basis",
    woord: "populisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een politieke stroming die 'het gewone volk' tegenover een als corrupt voorgestelde elite plaatst.",
    voorbeeldzin: "Politicologen discussiëren over de vraag of populisme een ideologie is of vooral een stijl.",
    herkomst: "Latijn populus (volk).",
    beeld: "Een spreker op een zeepkist die met zijn vinger naar een glazen paleis vol mensen in pakken wijst.",
  },
  {
    niveau: "basis",
    woord: "soevereiniteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het hoogste gezag van een staat: de onafhankelijke zeggenschap over het eigen grondgebied en de eigen zaken.",
    voorbeeldzin: "Critici vinden dat Europese regels de nationale soevereiniteit aantasten.",
    herkomst: "Oudfrans souverain, van Latijn super (boven).",
    beeld: "Een kasteel met een ophaalbrug waarvan alleen de eigen koning de hendel mag bedienen.",
  },
  {
    niveau: "basis",
    woord: "lobby",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het beïnvloeden van politici en beleidsmakers door belangengroepen, of de groep die dat doet.",
    voorbeeldzin: "De tabakslobby probeerde jarenlang strengere regels tegen te houden.",
    herkomst: "Engels lobby (hal), naar de hal van het parlement waar belangenbehartigers politici aanspraken.",
    beeld: "Een drukke hal waar mensen met aktetassen Kamerleden bij hun mouw grijpen.",
  },
  {
    niveau: "gevorderd",
    woord: "polarisatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het proces waarbij groepen in de samenleving steeds scherper tegenover elkaar komen te staan.",
    voorbeeldzin: "Sociale media worden vaak genoemd als oorzaak van de toenemende polarisatie.",
    herkomst: "Latijn polus (pool), zoals de twee tegenovergestelde polen van een magneet.",
    beeld: "Twee groepen mensen op ijsschotsen die steeds verder van elkaar af drijven.",
  },
  {
    niveau: "gevorderd",
    woord: "demissionair",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Gezegd van een kabinet dat zijn ontslag heeft aangeboden en alleen nog de lopende zaken afhandelt.",
    voorbeeldzin: "Een demissionair kabinet neemt doorgaans geen omstreden besluiten.",
    herkomst: "Frans démission (ontslag).",
    beeld: "Een minister met een verhuisdoos op het bureau, die alleen nog de post afhandelt.",
  },
  {
    niveau: "gevorderd",
    woord: "subsidiariteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het beginsel dat taken worden uitgevoerd op het laagste bestuursniveau waar dat nog goed kan.",
    voorbeeldzin: "Volgens het subsidiariteitsbeginsel moet de EU zich niet bemoeien met wat lidstaten zelf goed kunnen regelen.",
    herkomst: "Latijn subsidium (hulp, reserve).",
    beeld: "Een reus die pas komt helpen als het kleine dorpje het echt niet zelf kan.",
  },
  {
    niveau: "gevorderd",
    woord: "technocratie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Bestuur door deskundigen en specialisten in plaats van door gekozen politici.",
    voorbeeldzin: "Critici noemden het kabinet van experts een vorm van technocratie.",
    herkomst: "Grieks technè (vakmanschap) + kratos (macht).",
    beeld: "Een parlement vol mensen in witte laboratoriumjassen met rekenmachines in plaats van stembiljetten.",
  },
  {
    niveau: "gevorderd",
    woord: "trias politica",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De scheiding van de staatsmacht in een wetgevende, een uitvoerende en een rechterlijke macht.",
    voorbeeldzin: "Volgens de trias politica mag een minister zich niet met lopende rechtszaken bemoeien.",
    herkomst: "Latijn voor 'politieke driedeling'; bekend geworden door de Franse filosoof Montesquieu.",
    beeld: "Een krukje met drie poten: haal er één weg en alles valt om.",
  },
  {
    niveau: "expert",
    woord: "hegemonie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De overheersende positie of invloed van één staat of groep over anderen, ook op cultureel en ideologisch gebied.",
    voorbeeldzin: "Na de Koude Oorlog spraken velen van de Amerikaanse hegemonie.",
    herkomst: "Grieks hègemonia (leiderschap).",
    beeld: "Eén reusachtige boom waarvan de kruin alle kleinere bomen in de schaduw zet.",
  },
  {
    niveau: "expert",
    woord: "realpolitik",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Politiek die zich laat leiden door praktische belangen en machtsverhoudingen in plaats van door idealen of moraal.",
    voorbeeldzin: "Uit realpolitik bleef het land handel drijven met het regime, ondanks de mensenrechtenschendingen.",
    herkomst: "Duits, 19e eeuw; vaak verbonden met het beleid van de Pruisische staatsman Bismarck.",
    beeld: "Een diplomaat die met één hand een vredesduif vasthoudt en met de andere een oliecontract tekent.",
  },
  {
    niveau: "expert",
    woord: "filibuster",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het extreem lang aan het woord blijven om een stemming te vertragen of te blokkeren.",
    voorbeeldzin: "Een Amerikaanse senator hield in 1957 een filibuster van meer dan 24 uur.",
    herkomst: "Via het Spaanse filibustero (vrijbuiter, piraat).",
    beeld: "Een piraat achter het spreekgestoelte die urenlang blijft voorlezen uit het telefoonboek.",
  },
  {
    niveau: "expert",
    woord: "gerrymandering",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het zo indelen van kiesdistricten dat één partij er voordeel van heeft.",
    voorbeeldzin: "Door gerrymandering kon de partij met minder stemmen toch de meeste zetels winnen.",
    herkomst: "Naar de Amerikaanse gouverneur Elbridge Gerry (1812), wiens nieuwe kiesdistrict op een salamander leek.",
    beeld: "Een landkaart waarop een kiesdistrict als een kronkelende salamander is ingetekend.",
  },
  {
    niveau: "expert",
    woord: "cordon sanitaire",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De afspraak van partijen om niet samen te werken met een bepaalde, vaak extreme, partij.",
    voorbeeldzin: "In België houden de meeste partijen al sinds 1989 een cordon sanitaire in stand rond extreemrechts.",
    herkomst: "Frans: 'hygiënische afzetting'; oorspronkelijk een quarantainegordel tegen besmettelijke ziektes.",
    beeld: "Een partij binnen een kring van rood-wit afzetlint, terwijl iedereen op veilige afstand blijft.",
  },
  {
    niveau: "basis",
    woord: "referendum",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een stemming waarbij kiezers rechtstreeks over een bepaald voorstel beslissen of hun mening geven.",
    voorbeeldzin: "In 2005 stemde een meerderheid van de Nederlanders in een referendum tegen de Europese grondwet.",
    herkomst: "Latijn referre (terugbrengen, voorleggen).",
    beeld: "Een hele stad die met een groene of rode kaart in de lucht één vraag beantwoordt.",
  },
  {
    niveau: "basis",
    woord: "oppositie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De partijen in het parlement die de regering niet steunen en haar kritisch controleren.",
    voorbeeldzin: "De oppositie diende een motie van wantrouwen in tegen de minister.",
    herkomst: "Latijn opponere (tegenover stellen).",
    beeld: "Een groep mensen aan de overkant van de tafel die elk plan van de regering met rode pen nakijkt.",
  },
  {
    niveau: "basis",
    woord: "kabinetsformatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De periode na verkiezingen waarin partijen onderhandelen over een nieuwe regering en een regeerakkoord.",
    voorbeeldzin: "De kabinetsformatie van 2021 duurde 299 dagen, een Nederlands record.",
    herkomst: "Latijn formare (vormen).",
    beeld: "Partijleiders die met puzzelstukjes schuiven tot er eindelijk een plaatje past.",
  },
  {
    niveau: "gevorderd",
    woord: "motie van wantrouwen",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een motie waarin de Kamer uitspreekt geen vertrouwen meer te hebben in een minister of het kabinet, wat meestal tot aftreden leidt.",
    voorbeeldzin: "Toen de motie van wantrouwen een meerderheid kreeg, trad de minister af.",
    herkomst: "Samenstelling van motie en wantrouwen.",
    beeld: "Een Kamerlid dat een rode kaart omhooghoudt naar de ministersbank.",
  },
  {
    niveau: "expert",
    woord: "parlementaire enquête",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het zwaarste onderzoeksmiddel van de Tweede Kamer, waarbij getuigen onder ede verhoord kunnen worden.",
    voorbeeldzin: "De parlementaire enquête naar de gaswinning in Groningen verhoorde tientallen getuigen onder ede.",
    herkomst: "Frans enquête (onderzoek).",
    beeld: "Een lange tafel met Kamerleden tegenover een getuige die met opgestoken hand de eed aflegt.",
  },
];
