import type { BankWoord } from "../woordenbank.ts";

// Woorden uit het leerpad over de DSM-5, het classificatiesysteem voor psychische stoornissen.
// Ze horen bij het vakgebied Psychologie. Bedoeld om de taal te leren, niet om jezelf of anderen te diagnosticeren.
export const psychologieDsm: BankWoord[] = [
  {
    niveau: "basis",
    woord: "classificatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het indelen van dingen in groepen of categorieën op grond van gedeelde kenmerken.",
    voorbeeldzin: "De DSM-5 is een classificatie van psychische stoornissen, geen verklaring van hoe ze ontstaan.",
    voorbeelden: [
      "Een bibliotheek werkt met een classificatie van boeken per onderwerp.",
      "Over de classificatie van sommige stoornissen verschillen deskundigen van mening.",
    ],
    herkomst: "Latijn classis (klasse, groep) + facere (maken).",
    beeld: "Een ladekast met etiketjes, waarin elk sokje in het juiste vakje belandt.",
  },
  {
    niveau: "basis",
    woord: "criterium",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een vaste maatstaf of voorwaarde waaraan je iets toetst; het meervoud is criteria.",
    voorbeeldzin: "Voor een diagnose moet iemand aan een bepaald aantal criteria voldoen, niet aan één losse klacht.",
    voorbeelden: [
      "Het belangrijkste criterium bij de sollicitatie was ervaring.",
      "Elk criterium in de DSM beschrijft een concreet kenmerk of gedrag.",
    ],
    herkomst: "Grieks kritèrion (middel om te oordelen), van krinein (scheiden, oordelen).",
    beeld: "Een zeef met gaatjes van precies de juiste maat: wat erdoor valt, voldoet niet.",
  },
  {
    niveau: "gevorderd",
    woord: "prevalentie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Hoe vaak een ziekte of aandoening op een bepaald moment voorkomt in een bevolking, meestal als percentage.",
    voorbeeldzin: "De prevalentie van depressie is bij vrouwen hoger dan bij mannen.",
    voorbeelden: [
      "Onderzoekers schatten de prevalentie van ADHD bij volwassenen op enkele procenten.",
      "Door betere herkenning lijkt de prevalentie soms te stijgen.",
    ],
    herkomst: "Latijn praevalere (de overhand hebben, vaker voorkomen).",
    beeld: "Een stadion vol mensen waarin een deel een gekleurde pet draagt: dat deel is de maat.",
  },
  {
    niveau: "expert",
    woord: "comorbiditeit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het tegelijk voorkomen van twee of meer aandoeningen bij dezelfde persoon.",
    voorbeeldzin: "Bij angst en depressie is comorbiditeit eerder regel dan uitzondering.",
    voorbeelden: [
      "Door comorbiditeit is de behandeling vaak ingewikkelder.",
      "De arts vroeg ook naar andere klachten om comorbiditeit uit te sluiten.",
    ],
    herkomst: "Latijn co- (samen) + morbus (ziekte).",
    beeld: "Twee gasten die altijd samen op een feestje verschijnen en elkaars jas vasthouden.",
  },
  {
    niveau: "expert",
    woord: "differentiaaldiagnose",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het rijtje aandoeningen dat de klachten ook zou kunnen verklaren, en het afwegen daartussen om de juiste te vinden.",
    voorbeeldzin: "Bij concentratieproblemen staan ADHD, slaaptekort en depressie allemaal op de differentiaaldiagnose.",
    voorbeelden: [
      "Een goede differentiaaldiagnose voorkomt dat je de verkeerde behandeling start.",
      "De psychiater besprak de differentiaaldiagnose voordat ze een conclusie trok.",
    ],
    herkomst: "Latijn differentia (verschil) + Grieks diagnōsis (onderscheiding).",
    beeld: "Een detective met een prikbord vol verdachten, die er één voor één een streep door zet.",
  },
  {
    niveau: "expert",
    woord: "etiologie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De leer van de oorzaken van ziekten en aandoeningen, of die oorzaken zelf.",
    voorbeeldzin: "De DSM-5 beschrijft symptomen, maar zegt bewust weinig over de etiologie.",
    voorbeelden: [
      "Over de etiologie van schizofrenie is nog veel onbekend.",
      "Erfelijkheid en omgeving spelen allebei een rol in de etiologie.",
    ],
    herkomst: "Grieks aitia (oorzaak) + logos (leer).",
    beeld: "Een tuinman die niet naar het verwelkte blad kijkt, maar de wortels uitgraaft.",
  },
  {
    niveau: "basis",
    woord: "depressieve stoornis",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een aandoening met langer dan twee weken een sombere stemming of verlies van interesse, vaak met moeheid, slaapproblemen en schuldgevoel.",
    voorbeeldzin: "Een depressieve stoornis is meer dan een paar dagen verdrietig zijn.",
    voorbeelden: [
      "Een depressieve stoornis is goed te behandelen met therapie, soms samen met medicatie.",
      "Bij een depressieve stoornis kost zelfs opstaan veel energie.",
    ],
    herkomst: "Latijn deprimere (neerdrukken) + stoornis.",
    beeld: "Een grijze deken die over alles heen ligt, zodat zelfs je favoriete muziek dof klinkt.",
  },
  {
    niveau: "gevorderd",
    woord: "bipolaire stoornis",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een aandoening waarbij iemand perioden heeft van extreem opgewekte of prikkelbare stemming (manie) en vaak ook perioden van depressie.",
    voorbeeldzin: "Iemand met een bipolaire stoornis kan in een manische periode dagen bijna niet slapen.",
    voorbeelden: [
      "Vroeger heette de bipolaire stoornis manisch-depressieve stoornis.",
      "Met medicatie blijft de stemming bij een bipolaire stoornis vaak stabieler.",
    ],
    herkomst: "Latijn bi- (twee) + polus (pool): twee uitersten.",
    beeld: "Een schommel die niet rustig heen en weer gaat, maar telkens tot de hoogste punten doorslaat.",
  },
  {
    niveau: "gevorderd",
    woord: "gegeneraliseerde angststoornis",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een aandoening waarbij iemand maandenlang, bijna elke dag, overmatig piekert over allerlei gewone dingen en dat moeilijk kan stoppen.",
    voorbeeldzin: "Bij een gegeneraliseerde angststoornis gaat het piekeren niet over één ding, maar over alles.",
    voorbeelden: [
      "Een gegeneraliseerde angststoornis gaat vaak samen met spierspanning en slecht slapen.",
      "Cognitieve gedragstherapie helpt veel mensen met een gegeneraliseerde angststoornis.",
    ],
    herkomst: "Latijn generalis (algemeen) + angst + stoornis.",
    beeld: "Een radio die op de achtergrond steeds 'en wat als…?' blijft uitzenden.",
  },
  {
    niveau: "basis",
    woord: "paniekstoornis",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een aandoening met terugkerende, onverwachte aanvallen van hevige angst met hartkloppingen en benauwdheid, en de voortdurende vrees voor een nieuwe aanval.",
    voorbeeldzin: "Door haar paniekstoornis vermeed ze de trein, uit angst daar een aanval te krijgen.",
    voorbeelden: [
      "Bij een paniekstoornis denken mensen tijdens een aanval soms dat ze een hartaanval hebben.",
      "Een paniekstoornis is met therapie meestal goed te behandelen.",
    ],
    herkomst: "Naar de Griekse god Pan, die volgens de mythe mensen plotseling angst aanjoeg.",
    beeld: "Een brandalarm dat midden in een rustige kamer afgaat zonder dat er rook is.",
  },
  {
    niveau: "basis",
    woord: "fobie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een hevige, onredelijke angst voor een bepaald ding of een bepaalde situatie, die je daardoor gaat vermijden.",
    voorbeeldzin: "Door zijn fobie voor spinnen durft hij de zolder niet meer op.",
    voorbeelden: [
      "Hoogtevrees is een veelvoorkomende fobie.",
      "Met stapsgewijze blootstelling kun je een fobie vaak afleren.",
    ],
    herkomst: "Grieks phobos (vrees).",
    beeld: "Iemand die een straat omloopt omdat er een ongevaarlijk hondje op de stoep ligt.",
  },
  {
    niveau: "gevorderd",
    woord: "dwangstoornis",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een aandoening met steeds terugkerende, ongewilde gedachten (obsessies) en handelingen die iemand zich gedwongen voelt te herhalen (compulsies).",
    voorbeeldzin: "Door haar dwangstoornis controleerde ze wel twintig keer of het gas uit was.",
    voorbeelden: [
      "Een dwangstoornis wordt ook wel obsessief-compulsieve stoornis of OCS genoemd.",
      "Iemand met een dwangstoornis weet vaak dat de gedachten overdreven zijn, maar kan ze niet stoppen.",
    ],
    herkomst: "Samenstelling van dwang en stoornis.",
    beeld: "Een lichtknopje dat je telkens weer moet aan- en uitdoen voordat je de deur uit mag.",
  },
  {
    niveau: "basis",
    woord: "ADHD",
    woordsoort: "zelfstandig naamwoord (afkorting)",
    definitie: "Een ontwikkelingsstoornis met blijvende problemen met aandacht, en vaak ook met impulsiviteit en hyperactiviteit.",
    voorbeeldzin: "Door zijn ADHD raakt hij in vergaderingen snel de draad kwijt.",
    voorbeelden: [
      "ADHD begint in de kindertijd, maar houdt bij veel mensen aan tot in de volwassenheid.",
      "Structuur en korte taken helpen veel mensen met ADHD.",
    ],
    herkomst: "Engelse afkorting van attention-deficit/hyperactivity disorder.",
    beeld: "Een radio waarvan de zoekknop steeds vanzelf naar een andere zender springt.",
  },
  {
    niveau: "gevorderd",
    woord: "autismespectrumstoornis",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een ontwikkelingsstoornis met blijvende verschillen in sociale communicatie en contact, en met beperkte, herhaalde patronen in gedrag of interesses.",
    voorbeeldzin: "Bij een autismespectrumstoornis kunnen drukke, onvoorspelbare situaties erg vermoeiend zijn.",
    voorbeelden: [
      "Het woord spectrum in autismespectrumstoornis laat zien dat het bij iedereen anders is.",
      "Sinds de DSM-5 valt het vroegere syndroom van Asperger onder de autismespectrumstoornis.",
    ],
    herkomst: "Grieks autos (zelf) + Latijn spectrum (beeld, reeks) + stoornis.",
    beeld: "Een mengpaneel met veel schuifjes, die bij iedereen op een andere stand staan.",
  },
  {
    niveau: "gevorderd",
    woord: "persoonlijkheidsstoornis",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een blijvend, star patroon van denken, voelen en omgaan met anderen dat sterk afwijkt van wat gebruikelijk is en tot lijden of problemen leidt.",
    voorbeeldzin: "Van een persoonlijkheidsstoornis spreek je pas als het patroon al jaren in veel situaties terugkomt.",
    voorbeelden: [
      "De DSM-5 onderscheidt tien soorten persoonlijkheidsstoornis.",
      "Een persoonlijkheidsstoornis zegt niets over hoe waardevol iemand is.",
    ],
    herkomst: "Latijn persona (masker, rol) + stoornis.",
    beeld: "Een bril met gekleurde glazen die iemand nooit afzet, waardoor alles steeds dezelfde tint krijgt.",
  },
  {
    niveau: "gevorderd",
    woord: "borderline",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een persoonlijkheidsstoornis met heftige, snel wisselende emoties, een wankel zelfbeeld, impulsiviteit en instabiele relaties.",
    voorbeeldzin: "Iemand met borderline kan van het ene op het andere moment van intense liefde naar woede schieten.",
    voorbeelden: [
      "Dialectische gedragstherapie werd speciaal voor borderline ontwikkeld.",
      "Bij borderline speelt angst om verlaten te worden vaak een grote rol.",
    ],
    herkomst: "Engels: grenslijn; men dacht vroeger dat het op de grens van neurose en psychose lag.",
    beeld: "Een zee waarop de golven zonder waarschuwing van spiegelglad naar storm gaan.",
  },
  {
    niveau: "gevorderd",
    woord: "narcisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een patroon van grootheidsgevoelens, een sterke behoefte aan bewondering en weinig inlevingsvermogen in anderen.",
    voorbeeldzin: "Zijn narcisme bleek toen hij elke vergadering weer over zijn eigen successen begon.",
    voorbeelden: [
      "In het dagelijks leven wordt narcistisch vaak te snel gebruikt als scheldwoord.",
      "Achter narcisme zit volgens sommige psychologen juist een kwetsbaar zelfbeeld.",
    ],
    herkomst: "Naar Narcissus, die in de Griekse mythe verliefd werd op zijn eigen spiegelbeeld.",
    beeld: "Een jongen die bij een vijver ligt en alleen maar naar zijn eigen weerspiegeling staart.",
  },
  {
    niveau: "gevorderd",
    woord: "neurodiversiteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het idee dat verschillen in hoe hersenen werken, zoals bij autisme of ADHD, natuurlijke variatie zijn in plaats van alleen tekorten.",
    voorbeeldzin: "Bedrijven die neurodiversiteit omarmen, passen hun werkplekken aan voor verschillende soorten denkers.",
    voorbeelden: [
      "Neurodiversiteit is geen diagnose, maar een manier van kijken.",
      "De beweging voor neurodiversiteit ontstond eind jaren negentig.",
    ],
    herkomst: "Grieks neuron (zenuw) + Latijn diversitas (verscheidenheid).",
    beeld: "Een bos met allerlei soorten bomen, waar geen enkele boom de 'normale' is.",
  },
  {
    niveau: "basis",
    woord: "psychose",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een toestand waarin iemand het contact met de werkelijkheid kwijtraakt, bijvoorbeeld door dingen te zien of te horen die er niet zijn.",
    voorbeeldzin: "Tijdens een psychose kan iemand heilig overtuigd zijn van dingen die niet kloppen.",
    voorbeelden: [
      "Een psychose kan ontstaan door ernstig slaaptekort, drugs of een psychische aandoening.",
      "Na een eerste psychose herstellen veel mensen goed.",
    ],
    herkomst: "Grieks psychè (ziel, geest) + -osis (toestand, aandoening).",
    beeld: "Een film waarin de ondertiteling ineens een heel ander verhaal vertelt dan het beeld.",
  },
  {
    niveau: "gevorderd",
    woord: "schizofrenie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een ernstige psychische aandoening met terugkerende psychosen en vaak ook minder motivatie, vlakke emoties en problemen met denken.",
    voorbeeldzin: "Schizofrenie heeft niets te maken met een 'gespleten persoonlijkheid', al denken veel mensen dat.",
    voorbeelden: [
      "Schizofrenie begint meestal tussen het vijftiende en dertigste levensjaar.",
      "Met behandeling en begeleiding kunnen veel mensen met schizofrenie zelfstandig leven.",
    ],
    herkomst: "Grieks schizein (splijten) + phrèn (geest); bedoeld was een splitsing tussen denken en voelen.",
    beeld: "Een orkest waarin de muzikanten elk een ander stuk spelen, zodat de melodie uiteenvalt.",
  },
  {
    niveau: "basis",
    woord: "hallucinatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een waarneming zonder prikkel van buiten: iets zien, horen, ruiken of voelen dat er niet is.",
    voorbeeldzin: "Stemmen horen die niemand anders hoort, is de bekendste hallucinatie.",
    voorbeelden: [
      "Na dagen zonder slaap kreeg hij een hallucinatie van kruipende beestjes.",
      "Een hallucinatie voelt voor de persoon zelf net zo echt als een gewone waarneming.",
    ],
    herkomst: "Latijn (h)allucinari (dwalen in de geest, dromen).",
    beeld: "Een telefoon die in je zak lijkt te trillen, terwijl hij op tafel ligt.",
  },
  {
    niveau: "gevorderd",
    woord: "waan",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een vaste overtuiging die duidelijk niet klopt en die iemand vasthoudt, ook als alle bewijs ertegen spreekt.",
    voorbeeldzin: "In zijn waan was hij ervan overtuigd dat de buren hem via de verwarming afluisterden.",
    voorbeelden: [
      "Een achtervolgingswaan is de meest voorkomende vorm.",
      "Met argumenten kun je iemand niet uit een waan praten.",
    ],
    herkomst: "Middelnederlands waen (vermoeden, verwachting).",
    beeld: "Een kompas waarvan de naald op het verkeerde noorden staat vastgeroest.",
  },
  {
    niveau: "basis",
    woord: "PTSS",
    woordsoort: "zelfstandig naamwoord (afkorting)",
    definitie: "Posttraumatische stressstoornis: een aandoening na een schokkende gebeurtenis, met herbelevingen, vermijding en voortdurende waakzaamheid.",
    voorbeeldzin: "Bij PTSS kan een harde knal iemand ineens terugwerpen naar het moment van de aanslag.",
    voorbeelden: [
      "Veel hulpverleners en veteranen krijgen te maken met PTSS.",
      "EMDR is een bekende behandeling voor PTSS.",
    ],
    herkomst: "Afkorting van posttraumatische stressstoornis; Grieks trauma (wond).",
    beeld: "Een alarm dat na een inbraak jarenlang blijft afgaan bij elke dichtslaande deur.",
  },
  {
    niveau: "expert",
    woord: "dissociatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het tijdelijk losraken van je eigen gedachten, gevoelens, herinneringen of lichaam, vaak als reactie op overweldigende stress.",
    voorbeeldzin: "Door dissociatie voelde het ongeluk alsof ze naar een film over iemand anders keek.",
    voorbeelden: [
      "Lichte dissociatie kent iedereen, bijvoorbeeld als je 'wegdroomt' tijdens het autorijden.",
      "Bij ernstig trauma kan dissociatie een manier zijn om het te overleven.",
    ],
    herkomst: "Latijn dissociare (scheiden, uit elkaar halen).",
    beeld: "Een ballon die aan een lang touw boven je hoofd zweeft, terwijl jij beneden blijft staan.",
  },
];
