import type { BankWoord } from "../woordenbank.ts";

export const psychologie: BankWoord[] = [
  {
    niveau: "basis",
    woord: "empathie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het vermogen om je in te leven in de gevoelens en gedachten van een ander.",
    voorbeeldzin: "Een goede huisarts toont empathie voor de zorgen van haar patiënten.",
    voorbeelden: [
      "Door haar empathie voelde ze aan dat haar vriendin iets dwarszat.",
      "Empathie is niet hetzelfde als het met iemand eens zijn.",
    ],
    herkomst: "Grieks en (in) + pathos (gevoel).",
    beeld: "Iemand die zelf een traan laat terwijl een vriend verdrietig nieuws vertelt.",
  },
  {
    niveau: "basis",
    woord: "introvert",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Naar binnen gericht; energie halend uit alleen zijn en sociale drukte snel vermoeiend vindend.",
    voorbeeldzin: "Als introvert kind las ze liever een boek dan dat ze op het schoolplein speelde.",
    voorbeelden: [
      "Een introvert persoon kan prima spreken in het openbaar, maar heeft daarna rust nodig.",
      "Op kantoor koos de introverte programmeur liever voor een stille werkplek.",
    ],
    herkomst: "Latijn intro (naar binnen) + vertere (keren).",
    beeld: "Iemand die na een druk feest opgelucht met een deken en een boek op de bank ploft.",
  },
  {
    niveau: "basis",
    woord: "placebo-effect",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het verschijnsel dat mensen zich beter voelen door een behandeling zonder werkzame stof, puur omdat ze verwachten dat die helpt.",
    voorbeeldzin: "In medicijnonderzoek krijgt een controlegroep nepmedicijnen om rekening te houden met het placebo-effect.",
    voorbeelden: [
      "Het placebo-effect is soms zo sterk dat patiënten echt minder pijn ervaren.",
      "Dure pillen lijken beter te werken dan goedkope, onder meer door het placebo-effect.",
    ],
    herkomst: "Latijn placebo (ik zal behagen).",
    beeld: "Een suikerpilletje, verkleed als medicijn, dat de hoofdpijn laat verdwijnen.",
  },
  {
    niveau: "basis",
    woord: "trauma",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een diepe psychische wond door een ingrijpende, schokkende gebeurtenis, die lang kan doorwerken.",
    voorbeeldzin: "Na het ongeluk had hij een trauma en durfde hij niet meer in een auto te stappen.",
    voorbeelden: [
      "Veel militairen houden een trauma over aan hun uitzending.",
      "Een trauma verwerken kost tijd en soms professionele hulp.",
    ],
    herkomst: "Grieks trauma (wond).",
    beeld: "Een barst in een vaas die je jaren later nog ziet, ook al is hij gelijmd.",
  },
  {
    niveau: "basis",
    woord: "stereotype",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een vereenvoudigd en vaak vooringenomen beeld van een groep mensen.",
    voorbeeldzin: "Het idee dat alle Nederlanders gierig zijn is een stereotype.",
    voorbeelden: [
      "Het stereotype van de verstrooide professor klopt zelden.",
      "Reclames bevestigen soms een stereotype over mannen en vrouwen.",
    ],
    herkomst: "Grieks stereos (vast, stijf) + typos (afdruk); oorspronkelijk een vaste drukplaat.",
    beeld: "Een koekjesvorm die van elk stuk deeg precies hetzelfde koekje maakt.",
  },
  {
    niveau: "gevorderd",
    woord: "affiliatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Verbondenheid met of aansluiting bij een groep of organisatie; in de psychologie: de behoefte om bij anderen te horen en contact te hebben.",
    voorbeeldzin: "Door een sterke behoefte aan affiliatie werken sommige mensen liever in een team dan alleen.",
    voorbeelden: [
      "Sociale media spelen handig in op onze behoefte aan affiliatie.",
      "Op het congres werd bij elke spreker de affiliatie met een universiteit vermeld.",
    ],
    herkomst: "Latijn affiliare (als zoon aannemen), van filius (zoon).",
    beeld: "Een nieuwkomer die een clubjasje krijgt en door de hele groep met een high five wordt ontvangen.",
  },
  {
    niveau: "gevorderd",
    woord: "cognitieve dissonantie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het ongemakkelijke gevoel dat ontstaat als je gedrag en je overtuigingen met elkaar in strijd zijn.",
    voorbeeldzin: "Een roker die weet dat roken ongezond is, ervaart cognitieve dissonantie.",
    voorbeelden: [
      "Om cognitieve dissonantie te verminderen, praten mensen hun keuzes achteraf vaak goed.",
      "Iemand die tegen vliegen is maar toch op vakantie vliegt, kan cognitieve dissonantie voelen.",
    ],
    herkomst: "Latijn cognitio (kennis) + dissonantia (wanklank); theorie van Leon Festinger (1957).",
    beeld: "Twee orkesten die tegelijk een ander lied spelen in je hoofd.",
  },
  {
    niveau: "gevorderd",
    woord: "bevestigingsbias",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De neiging om vooral informatie te zoeken, op te merken en te onthouden die je bestaande overtuiging bevestigt.",
    voorbeeldzin: "Door bevestigingsbias lezen mensen vooral nieuws dat hun eigen mening ondersteunt.",
    voorbeelden: [
      "Bevestigingsbias maakt dat we tegenargumenten sneller wegwuiven.",
      "Onderzoekers werken met controlegroepen om bevestigingsbias te beperken.",
    ],
    herkomst: "Vertaling van het Engelse confirmation bias; bias betekent vooringenomenheid.",
    beeld: "Iemand die met een zaklamp alleen de plekken in een donkere kamer beschijnt waar hij al iets verwacht.",
  },
  {
    niveau: "gevorderd",
    woord: "conformisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het aanpassen van je gedrag of mening aan die van de groep, vaak om erbij te horen.",
    voorbeeldzin: "In de bekende experimenten van Solomon Asch gaven proefpersonen door conformisme soms bewust een fout antwoord.",
    voorbeelden: [
      "Op de middelbare school is de druk tot conformisme vaak groot.",
      "Conformisme kan ertoe leiden dat niemand ingrijpt als er iets misgaat.",
    ],
    herkomst: "Latijn conformare (gelijkvormig maken).",
    beeld: "Een school vissen die tegelijk dezelfde kant op draait, ook de vis die eigenlijk links wilde.",
  },
  {
    niveau: "gevorderd",
    woord: "projectie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een afweermechanisme waarbij je je eigen ongewenste gevoelens of eigenschappen toeschrijft aan een ander.",
    voorbeeldzin: "Dat hij zijn collega steeds jaloers noemde, was misschien projectie van zijn eigen jaloezie.",
    voorbeelden: [
      "Projectie is een van de afweermechanismen die in de psychoanalyse zijn beschreven.",
      "Toen ze haar partner onzeker noemde, was dat deels projectie.",
    ],
    herkomst: "Latijn proicere (vooruitwerpen).",
    beeld: "Een diaprojector die jouw eigen gezicht op het hoofd van iemand anders projecteert.",
  },
  {
    niveau: "gevorderd",
    woord: "neuroplasticiteit",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het vermogen van de hersenen om zich aan te passen door nieuwe verbindingen te vormen, bijvoorbeeld bij leren of na hersenletsel.",
    voorbeeldzin: "Dankzij neuroplasticiteit kunnen patiënten na een beroerte soms weer leren praten.",
    voorbeelden: [
      "Door neuroplasticiteit kun je ook op latere leeftijd nog een taal leren.",
      "Neuroplasticiteit verklaart waarom oefenen je hersenen letterlijk verandert.",
    ],
    herkomst: "Grieks neuron (zenuw) + plastikos (vormbaar).",
    beeld: "Een bospad dat ontstaat doordat mensen er steeds opnieuw overheen lopen.",
  },
  {
    niveau: "gevorderd",
    woord: "conditionering",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een leerproces waarbij gedrag of reacties gekoppeld raken aan prikkels, beloningen of straffen.",
    voorbeeldzin: "Door conditionering begonnen de honden van Pavlov al te kwijlen bij het signaal dat eten aankondigde.",
    voorbeelden: [
      "Door conditionering koppelen veel mensen het geluid van een melding aan een klein beloningsgevoel.",
      "Dierentrainers gebruiken conditionering om honden nieuwe commando's te leren.",
    ],
    herkomst: "Latijn condicio (voorwaarde).",
    beeld: "Een hond die al begint te kwijlen zodra hij het geluid van de blikopener hoort.",
  },
  {
    niveau: "gevorderd",
    woord: "selffulfilling prophecy",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een verwachting die uitkomt juist doordat mensen ernaar gaan handelen.",
    voorbeeldzin: "Als iedereen verwacht dat een bank omvalt en zijn geld opneemt, wordt dat een selffulfilling prophecy.",
    voorbeelden: [
      "Een leraar die weinig van een leerling verwacht, kan zo een selffulfilling prophecy veroorzaken.",
      "Zijn angst om te falen werd een selffulfilling prophecy.",
    ],
    herkomst: "Engels: zichzelf vervullende voorspelling; term van socioloog Robert K. Merton (1948).",
    beeld: "Iemand die denkt dat hij gaat struikelen, zo nerveus naar zijn voeten kijkt en daardoor struikelt.",
  },
  {
    niveau: "gevorderd",
    woord: "prosociaal",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Gericht op het helpen van en zorgen voor anderen.",
    voorbeeldzin: "Vrijwilligerswerk is een vorm van prosociaal gedrag.",
    voorbeelden: [
      "Kinderen leren prosociaal gedrag onder meer van het voorbeeld van hun ouders.",
      "Onderzoek laat zien dat prosociaal gedrag ook de helper zelf gelukkiger maakt.",
    ],
    herkomst: "Latijn pro (voor) + socialis (maatschappelijk).",
    beeld: "Iemand die bij de bushalte zijn paraplu deelt met een onbekende.",
  },
  {
    niveau: "gevorderd",
    woord: "hechting",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De emotionele band die een kind opbouwt met zijn verzorgers, en die invloed heeft op latere relaties.",
    voorbeeldzin: "Een veilige hechting in de eerste levensjaren helpt kinderen om vertrouwen in anderen te ontwikkelen.",
    voorbeelden: [
      "Problemen in de hechting kunnen later doorwerken in relaties.",
      "De psychiater John Bowlby legde de basis voor de theorie over hechting.",
    ],
    herkomst: "Van hechten (vastmaken).",
    beeld: "Een bootje dat met een stevig touw aan de steiger ligt en daardoor rustig het water op durft.",
  },
  {
    niveau: "expert",
    woord: "Dunning-Krugereffect",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het verschijnsel dat mensen met weinig kennis van een onderwerp hun eigen kunde vaak overschatten.",
    voorbeeldzin: "Door het Dunning-Krugereffect denken beginnende schakers soms dat ze het spel al goed beheersen.",
    voorbeelden: [
      "Het Dunning-Krugereffect verklaart waarom leken soms zelfverzekerder klinken dan experts.",
      "Na een paar weken les leek hij last te hebben van het Dunning-Krugereffect.",
    ],
    herkomst: "Naar de psychologen David Dunning en Justin Kruger (1999).",
    beeld: "Iemand die na één kookvideo denkt dat hij een sterrenrestaurant kan runnen.",
  },
  {
    niveau: "expert",
    woord: "metacognitie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het nadenken over je eigen denken: inzicht in hoe jij leert, onthoudt en problemen oplost.",
    voorbeeldzin: "Deze app traint ook je metacognitie: je ontdekt hoe jij het beste leert.",
    voorbeelden: [
      "Goede studenten hebben vaak een sterke metacognitie: ze merken wanneer ze iets nog niet snappen.",
      "Leraren stimuleren metacognitie door leerlingen te laten nadenken over hun aanpak.",
    ],
    herkomst: "Grieks meta (over, boven) + Latijn cognitio (kennis).",
    beeld: "Een klein mannetje op je schouder dat meekijkt terwijl je studeert en aantekeningen maakt over hoe het gaat.",
  },
  {
    niveau: "expert",
    woord: "amygdala",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een amandelvormige kern diep in de hersenen die een centrale rol speelt bij emoties, vooral bij angst.",
    voorbeeldzin: "Bij een plotselinge schrik reageert de amygdala al voordat je bewust begrijpt wat er gebeurt.",
    voorbeelden: [
      "Bij mensen met een angststoornis reageert de amygdala vaak sterker op dreiging.",
      "De amygdala helpt verklaren waarom emotionele gebeurtenissen beter worden onthouden.",
    ],
    herkomst: "Grieks amygdalè (amandel).",
    beeld: "Een amandel met grote ogen die bij elk geritsel in de bosjes alarm slaat.",
  },
  {
    niveau: "expert",
    woord: "fundamentele attributiefout",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De neiging om het gedrag van anderen te verklaren uit hun karakter en de invloed van de situatie te onderschatten.",
    voorbeeldzin: "Denken dat een collega lui is omdat hij te laat komt, zonder aan de file te denken, is de fundamentele attributiefout.",
    voorbeelden: [
      "Door de fundamentele attributiefout oordelen we harder over anderen dan over onszelf.",
      "Wie de fundamentele attributiefout kent, vraagt eerst naar de omstandigheden.",
    ],
    herkomst: "Latijn attribuere (toekennen).",
    beeld: "Iemand die een automobilist uitscheldt voor wegpiraat, terwijl die met spoed naar het ziekenhuis rijdt.",
  },
];
