import type { BankWoord } from "../woordenbank.ts";

export const recht: BankWoord[] = [
  {
    niveau: "basis",
    woord: "dagvaarding",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een officieel document waarmee iemand wordt opgeroepen om voor de rechter te verschijnen.",
    voorbeeldzin: "De verdachte ontving een dagvaarding om over drie weken voor de rechtbank te verschijnen.",
    herkomst: "Middelnederlands dachvaerden: een dag vaststellen voor een zitting.",
    beeld: "Een brief met een grote rode stempel en een datum erop die door de brievenbus valt.",
  },
  {
    niveau: "basis",
    woord: "vonnis",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De uitspraak van een rechter aan het einde van een rechtszaak.",
    voorbeeldzin: "Het vonnis wordt over twee weken uitgesproken.",
    herkomst: "Middelnederlands vonnesse, verwant aan vinden in de betekenis 'oordelen'.",
    beeld: "Een rechter die met een hamer op tafel slaat, terwijl iedereen in de zaal de adem inhoudt.",
  },
  {
    niveau: "basis",
    woord: "alibi",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het bewijs dat een verdachte ten tijde van het misdrijf ergens anders was.",
    voorbeeldzin: "Zijn alibi was sterk: op het moment van de inbraak zat hij in het vliegtuig.",
    herkomst: "Latijn alibi (elders).",
    beeld: "Een vliegticket en een strandfoto die naast de plaats van het misdrijf op tafel worden gelegd.",
  },
  {
    niveau: "basis",
    woord: "aansprakelijk",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Wettelijk verantwoordelijk voor schade en verplicht die te vergoeden.",
    voorbeeldzin: "De eigenaar van de hond is aansprakelijk voor de schade aan de fiets.",
    herkomst: "Van aanspreken: iemand ergens op kunnen aanspreken.",
    beeld: "Een voetballer die een ruit kapotschiet en door de buurman bij zijn kraag wordt gegrepen: 'Jij betaalt!'",
  },
  {
    niveau: "basis",
    woord: "voorwaardelijke straf",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een straf die niet wordt uitgevoerd, tenzij de veroordeelde zich tijdens een proeftijd niet aan de voorwaarden houdt.",
    voorbeeldzin: "Hij kreeg drie maanden voorwaardelijk met een proeftijd van twee jaar.",
    herkomst: "Samenstelling van voorwaarde en straf.",
    beeld: "Een zwaard dat aan een dun draadje boven iemands hoofd hangt en pas valt als hij de fout ingaat.",
  },
  {
    niveau: "basis",
    woord: "hoger beroep",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het opnieuw laten behandelen van een zaak, inclusief de feiten, door een hogere rechter, omdat je het niet eens bent met de uitspraak.",
    voorbeeldzin: "Het Openbaar Ministerie ging in hoger beroep tegen de vrijspraak.",
    herkomst: "Van zich beroepen op: zich richten tot een hogere instantie.",
    beeld: "Een speler die het oneens is met de scheidsrechter en zijn zaak voorlegt aan de voetbalbond.",
  },
  {
    niveau: "gevorderd",
    woord: "legitimeren",
    woordsoort: "werkwoord",
    definitie: "Rechtvaardigen of als rechtmatig laten erkennen; ook: je identiteit aantonen met een geldig document.",
    voorbeeldzin: "De regering probeerde de noodmaatregelen te legitimeren met een beroep op de volksgezondheid.",
    herkomst: "Latijn legitimus (wettig), van lex (wet).",
    beeld: "Een koning die eerst een stempel van goedkeuring van het volk krijgt voordat hij zijn kroon mag opzetten.",
  },
  {
    niveau: "gevorderd",
    woord: "cassatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het rechtsmiddel waarbij de Hoge Raad alleen beoordeelt of het recht juist is toegepast, niet of de feiten kloppen.",
    voorbeeldzin: "De advocaat ging in cassatie omdat het hof de wet volgens hem verkeerd had uitgelegd.",
    herkomst: "Frans casser (breken, vernietigen).",
    beeld: "Een hoge rechter die niet naar de getuigen kijkt, maar alleen met een vergrootglas het wetboek naleest.",
  },
  {
    niveau: "gevorderd",
    woord: "jurisprudentie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het geheel van eerdere rechterlijke uitspraken dat als richtlijn dient voor latere zaken.",
    voorbeeldzin: "De advocaat verwees naar jurisprudentie van de Hoge Raad om zijn standpunt te onderbouwen.",
    herkomst: "Latijn iuris prudentia (kennis van het recht).",
    beeld: "Een dikke stapel oude vonnissen waar elke nieuwe rechter eerst doorheen bladert.",
  },
  {
    niveau: "gevorderd",
    woord: "onrechtmatige daad",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een handeling of nalaten die in strijd is met de wet of met wat maatschappelijk betamelijk is, waardoor een ander schade lijdt.",
    voorbeeldzin: "De rechter oordeelde dat het plaatsen van de valse recensies een onrechtmatige daad was.",
    herkomst: "Juridisch begrip uit artikel 6:162 van het Burgerlijk Wetboek.",
    beeld: "Iemand die de schutting van de buren omverrijdt en daarna de rekening krijgt.",
  },
  {
    niveau: "gevorderd",
    woord: "wanprestatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het niet, niet op tijd of niet goed nakomen van een verplichting uit een overeenkomst.",
    voorbeeldzin: "Omdat de aannemer de verbouwing niet afmaakte, sprak de klant hem aan op wanprestatie.",
    herkomst: "Wan- (slecht, verkeerd) + prestatie.",
    beeld: "Een bakker die een bruidstaart belooft en op de trouwdag met een pak beschuit aan komt zetten.",
  },
  {
    niveau: "gevorderd",
    woord: "presumptie van onschuld",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het beginsel dat iemand als onschuldig geldt totdat zijn schuld door een rechter is bewezen.",
    voorbeeldzin: "Vanwege de presumptie van onschuld moeten media voorzichtig zijn met het neerzetten van een verdachte als dader.",
    herkomst: "Latijn praesumptio (vermoeden).",
    beeld: "Een weegschaal die bij het begin van elke rechtszaak al naar 'onschuldig' doorslaat.",
  },
  {
    niveau: "gevorderd",
    woord: "verjaring",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het vervallen van het recht om iemand te vervolgen of een vordering in te stellen nadat een bepaalde termijn is verstreken.",
    voorbeeldzin: "Omdat de diefstal meer dan twaalf jaar geleden was gepleegd, was het feit verjaard.",
    herkomst: "Ver- + jaar: jaren laten verstrijken.",
    beeld: "Een opsporingsbericht aan de muur dat langzaam vergeelt tot het er vanzelf afvalt.",
  },
  {
    niveau: "gevorderd",
    woord: "rechtspersoon",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een organisatie, zoals een bv, vereniging of stichting, die juridisch als zelfstandige drager van rechten en plichten wordt behandeld.",
    voorbeeldzin: "Een stichting is een rechtspersoon en kan dus zelf contracten sluiten.",
    herkomst: "Samenstelling van recht en persoon.",
    beeld: "Een kantoorgebouw met een eigen handtekening, een eigen bankrekening en een eigen advocaat.",
  },
  {
    niveau: "expert",
    woord: "ne bis in idem",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het rechtsbeginsel dat niemand twee keer voor hetzelfde feit mag worden vervolgd of bestraft.",
    voorbeeldzin: "Omdat hij al was vrijgesproken, kon hij op grond van ne bis in idem niet opnieuw worden vervolgd.",
    herkomst: "Latijn: 'niet tweemaal over hetzelfde'.",
    beeld: "Een scheidsrechter die weigert dezelfde overtreding twee keer te bestraffen.",
  },
  {
    niveau: "expert",
    woord: "legaliteitsbeginsel",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het beginsel dat niemand gestraft kan worden voor een feit dat op het moment van handelen niet strafbaar was volgens de wet.",
    voorbeeldzin: "Het legaliteitsbeginsel staat in het eerste artikel van het Wetboek van Strafrecht.",
    herkomst: "Latijn legalis (wettelijk); ook bekend als nullum crimen sine lege: geen misdrijf zonder wet.",
    beeld: "Een agent die iemand wil bekeuren, door het wetboek bladert en ontdekt dat er nog geen regel voor bestaat.",
  },
  {
    niveau: "expert",
    woord: "opportuniteitsbeginsel",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het beginsel dat het Openbaar Ministerie mag afzien van vervolging als dat in het algemeen belang is.",
    voorbeeldzin: "Het Nederlandse gedoogbeleid voor softdrugs steunt op het opportuniteitsbeginsel.",
    herkomst: "Latijn opportunitas (gunstige gelegenheid).",
    beeld: "Een officier van justitie met een stapel dossiers die sommige mapjes bewust in de la laat liggen.",
  },
  {
    niveau: "expert",
    woord: "habeas corpus",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het recht van een gevangene om door een rechter te laten toetsen of zijn vrijheidsberoving rechtmatig is.",
    voorbeeldzin: "Het habeas corpus beschermt burgers tegen willekeurige opsluiting door de staat.",
    herkomst: "Latijn: 'dat je het lichaam hebt', de beginwoorden van een middeleeuws Engels bevelschrift.",
    beeld: "Een rechter die eist: 'Breng de gevangene hier, en laat zien waarom hij vastzit!'",
  },
  {
    niveau: "expert",
    woord: "sepot",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De beslissing van het Openbaar Ministerie om een zaak niet te vervolgen.",
    voorbeeldzin: "De zaak eindigde in een sepot wegens gebrek aan bewijs.",
    herkomst: "Van seponeren, Latijn seponere (terzijde leggen).",
    beeld: "Een dossier dat met een zucht achter in de archiefkast wordt geschoven.",
  },
];
