import type { BankWoord } from "../woordenbank.ts";

export const taalEnRetorica: BankWoord[] = [
  {
    niveau: "basis",
    woord: "retorica",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De kunst van het overtuigend spreken en schrijven.",
    voorbeeldzin: "De advocaat stond bekend om zijn indrukwekkende retorica.",
    voorbeelden: [
      "Achter de mooie retorica van de campagne zat weinig concreet beleid.",
      "In de klassieke oudheid was retorica een vast onderdeel van de opleiding.",
    ],
    herkomst: "Grieks rhètorikè (technè): de kunst van de redenaar.",
    beeld: "Een spreker op een podium die met één handgebaar een hele zaal laat knikken.",
  },
  {
    niveau: "basis",
    woord: "pedant",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Betweterig en belerend; op een schoolmeesterachtige, verwaande manier laten merken dat je veel weet.",
    voorbeeldzin: "Hij verbeterde op pedante toon elke taalfout in de mails van zijn collega's.",
    voorbeelden: [
      "Ze vond hem wat pedant, omdat hij in elk gesprek zijn kennis moest etaleren.",
      "Het is pedant om iemand midden in een verhaal op zijn grammatica te wijzen.",
    ],
    herkomst: "Via Frans pédant van Italiaans pedante (schoolmeester).",
    beeld: "Iemand die op een verjaardag met opgeheven wijsvinger een lezing geeft over de juiste uitspraak van 'croissant'.",
  },
  {
    niveau: "basis",
    woord: "drogreden",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een redenering die overtuigend lijkt, maar niet klopt.",
    voorbeeldzin: "'Iedereen doet het, dus het is goed' is een bekende drogreden.",
    voorbeelden: [
      "Iemands argument afwijzen omdat hij jong is, is een drogreden.",
      "Het debat stond vol drogredenen, van persoonlijke aanvallen tot valse tegenstellingen.",
    ],
    herkomst: "Nederlands drog (bedrog, schijn) + reden.",
    beeld: "Een brug van karton die er stevig uitziet, maar instort zodra je erop stapt.",
  },
  {
    niveau: "basis",
    woord: "metafoor",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Beeldspraak waarbij je iets aanduidt met een woord voor iets anders dat erop lijkt, zonder 'als' of 'zoals'.",
    voorbeeldzin: "In 'Zij is het zonnetje in huis' is 'zonnetje' een metafoor.",
    voorbeelden: [
      "'Tijd is geld' is een metafoor die veel zegt over onze cultuur.",
      "De dichter gebruikte de zee als metafoor voor verdriet.",
    ],
    herkomst: "Grieks metaphora (overdracht).",
    beeld: "Een zonnetje met armpjes en beentjes dat door de woonkamer huppelt.",
  },
  {
    niveau: "basis",
    woord: "hyperbool",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een stijlfiguur waarbij je bewust overdrijft om iets te benadrukken.",
    voorbeeldzin: "'Ik heb je al duizend keer gezegd dat je je jas moet ophangen' is een hyperbool.",
    voorbeelden: [
      "'Ik sterf van de honger' is een hyperbool die niemand letterlijk neemt.",
      "Reclame staat vol hyperbolen, zoals 'het lekkerste ijs ter wereld'.",
    ],
    herkomst: "Grieks hyperbolè (het voorbijschieten).",
    beeld: "Een visser die met zijn armen steeds wijder aangeeft hoe groot zijn vis was, tot hij er bijna zelf van omvalt.",
  },
  {
    niveau: "basis",
    woord: "retorische vraag",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een vraag die je niet stelt om een antwoord te krijgen, maar om iets te benadrukken.",
    voorbeeldzin: "'Wie wil er nou niet gezond oud worden?' is een retorische vraag.",
    voorbeelden: [
      "'Is dit nu het land dat we willen zijn?' vroeg de spreker: een retorische vraag.",
      "Op een retorische vraag hoef je geen antwoord te geven.",
    ],
    herkomst: "Grieks rhètorikos (van de redenaar).",
    beeld: "Een quizmaster die een vraag stelt en meteen de zoemers van tafel haalt.",
  },
  {
    niveau: "gevorderd",
    woord: "logos",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Overtuigen met logische argumenten, feiten en bewijs.",
    voorbeeldzin: "Met cijfers over de dalende criminaliteit deed de burgemeester een beroep op logos.",
    voorbeelden: [
      "Een advocaat die het bewijs stap voor stap op een rij zet, gebruikt vooral logos.",
      "Wetenschappelijke artikelen leunen bijna volledig op logos.",
    ],
    herkomst: "Grieks logos (woord, rede); een van de drie overtuigingsmiddelen van Aristoteles.",
    beeld: "Een spreker die een grafiek aanwijst en zegt: 'Kijk maar naar de cijfers.'",
  },
  {
    niveau: "gevorderd",
    woord: "ethos",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Overtuigen door je eigen betrouwbaarheid, deskundigheid en karakter te laten zien.",
    voorbeeldzin: "De arts begon haar betoog met haar dertig jaar ervaring: een duidelijk beroep op ethos.",
    voorbeelden: [
      "Een reclame waarin een tandarts een tandpasta aanraadt, speelt in op ethos.",
      "Door eerlijk een fout toe te geven, versterkte de minister juist haar ethos.",
    ],
    herkomst: "Grieks èthos (karakter, gewoonte); een van de drie overtuigingsmiddelen van Aristoteles.",
    beeld: "Een spreker in een witte doktersjas die zijn diploma's omhooghoudt.",
  },
  {
    niveau: "gevorderd",
    woord: "pathos",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Overtuigen door in te spelen op de gevoelens van het publiek.",
    voorbeeldzin: "Het goede doel toonde een foto van een hongerig kind: een sterk beroep op pathos.",
    voorbeelden: [
      "Met het persoonlijke verhaal van een slachtoffer koos de spreker bewust voor pathos.",
      "Te veel pathos kan een toespraak ongeloofwaardig maken.",
    ],
    herkomst: "Grieks pathos (lijden, emotie); een van de drie overtuigingsmiddelen van Aristoteles.",
    beeld: "Een spreker die een traan wegpinkt terwijl de hele zaal naar de zakdoekjes grijpt.",
  },
  {
    niveau: "gevorderd",
    woord: "ad hominem",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een drogreden waarbij je de persoon aanvalt in plaats van zijn argument.",
    voorbeeldzin: "'Jij hebt geen verstand van klimaat, je hebt niet eens gestudeerd' is een argument ad hominem.",
    voorbeelden: [
      "In plaats van op de inhoud in te gaan, koos de debater voor een aanval ad hominem.",
      "Een argument ad hominem zegt iets over de spreker, maar niets over de vraag of hij gelijk heeft.",
    ],
    herkomst: "Latijn: 'tegen de mens'.",
    beeld: "Een debat waarin iemand in plaats van te antwoorden de das van zijn tegenstander belachelijk maakt.",
  },
  {
    niveau: "gevorderd",
    woord: "stropopredenering",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een drogreden waarbij je het standpunt van de ander verdraait of overdrijft, zodat het makkelijker aan te vallen is.",
    voorbeeldzin: "'Jij wilt minder vlees eten? Dus jij wilt alle boeren failliet laten gaan!' is een stropopredenering.",
    voorbeelden: [
      "Door een stropopredenering leek het alsof de oppositie alle belastingen wilde afschaffen.",
      "Wie een stropopredenering herkent, kan het echte standpunt terugbrengen in het debat.",
    ],
    herkomst: "Vertaling van het Engelse straw man (stropop).",
    beeld: "Iemand die triomfantelijk een zelfgemaakte stropop omverduwt in plaats van zijn echte tegenstander.",
  },
  {
    niveau: "gevorderd",
    woord: "oxymoron",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een stijlfiguur waarin twee woorden die elkaar tegenspreken worden gecombineerd.",
    voorbeeldzin: "'Oorverdovende stilte' is een bekend oxymoron.",
    voorbeelden: [
      "'Bittere zoetheid' en 'levende dode' zijn voorbeelden van een oxymoron.",
      "Sommige mensen noemen 'georganiseerde chaos' een mooi oxymoron.",
    ],
    herkomst: "Grieks oxys (scherp) + mōros (dom): 'scherpzinnig-dom', zelf ook een oxymoron.",
    beeld: "Een ijskoude vlam die vrolijk in de open haard knettert.",
  },
  {
    niveau: "gevorderd",
    woord: "connotatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De bijbetekenis of gevoelswaarde die een woord naast zijn letterlijke betekenis oproept.",
    voorbeeldzin: "'Goedkoop' en 'voordelig' betekenen ongeveer hetzelfde, maar hebben een andere connotatie.",
    voorbeelden: [
      "Het woord 'bureaucraat' heeft een negatieve connotatie.",
      "'Slank' en 'mager' beschrijven hetzelfde, maar 'mager' heeft een minder positieve connotatie.",
    ],
    herkomst: "Latijn con (mee) + notare (aanduiden).",
    beeld: "Twee identieke cadeautjes: het ene verpakt in krantenpapier, het andere in goudfolie.",
  },
  {
    niveau: "gevorderd",
    woord: "anekdotisch bewijs",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Bewijs dat gebaseerd is op persoonlijke verhalen of losse voorbeelden, in plaats van op systematisch onderzoek.",
    voorbeeldzin: "'Mijn opa rookte en werd 95' is anekdotisch bewijs dat niets zegt over de risico's van roken.",
    voorbeelden: [
      "Eén vriend die rijk werd met crypto is anekdotisch bewijs, geen beleggingsadvies.",
      "Onderzoekers waarschuwen dat anekdotisch bewijs vaak overtuigender voelt dan cijfers.",
    ],
    herkomst: "Grieks anekdota (niet uitgegeven), via het Franse anecdote.",
    beeld: "Iemand die met één zonnige vakantiefoto probeert te bewijzen dat het in Schotland altijd mooi weer is.",
  },
  {
    niveau: "expert",
    woord: "syllogisme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een redenering in drie stappen waarbij uit twee premissen een conclusie volgt.",
    voorbeeldzin: "'Alle mensen zijn sterfelijk; Socrates is een mens; dus Socrates is sterfelijk' is het bekendste syllogisme.",
    voorbeelden: [
      "Een syllogisme kan logisch kloppen en toch tot een onware conclusie leiden als een premisse niet klopt.",
      "In de filosofieles moesten we zelf een syllogisme opstellen.",
    ],
    herkomst: "Grieks syllogismos (samenrekening); uitgewerkt door Aristoteles.",
    beeld: "Een trap met drie treden: de eerste twee leiden onvermijdelijk naar de derde.",
  },
  {
    niveau: "expert",
    woord: "litotes",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een stijlfiguur waarin je iets benadrukt door het tegendeel te ontkennen, zoals 'niet slecht' voor 'goed'.",
    voorbeeldzin: "'Dat was geen kleine prestatie' is een litotes.",
    voorbeelden: [
      "'Hij is niet de slimste' is een litotes voor 'hij is dom'.",
      "Nederlanders gebruiken graag een litotes, zoals 'dat valt niet tegen'.",
    ],
    herkomst: "Grieks litotès (eenvoud, soberheid).",
    beeld: "Iemand die net de loterij heeft gewonnen en droog zegt: 'Nou, het is niet verkeerd.'",
  },
  {
    niveau: "expert",
    woord: "pleonasme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een overbodige herhaling waarbij een woord iets toevoegt wat al in een ander woord zit, zoals 'witte sneeuw'.",
    voorbeeldzin: "'Een ronde cirkel' is een pleonasme.",
    voorbeelden: [
      "'Zwart roet' en 'een oude grijsaard' zijn voorbeelden van een pleonasme.",
      "In een zakelijke tekst is een pleonasme als 'vooruit plannen' overbodig.",
    ],
    herkomst: "Grieks pleonasmos (overdaad).",
    beeld: "Een natte vis die in een natte plas nat water zwemt.",
  },
];
