import type { BankWoord } from "../woordenbank.ts";

export const tech: BankWoord[] = [
  {
    niveau: "basis",
    woord: "algoritme",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een reeks duidelijke stappen of instructies om een probleem op te lossen of een taak uit te voeren.",
    voorbeeldzin: "Het algoritme van de streamingdienst bepaalt welke series je te zien krijgt.",
    herkomst: "Naar de Perzische wiskundige al-Chwarizmi (9e eeuw).",
    beeld: "Een kok die stap voor stap een recept volgt zonder ook maar één regel over te slaan.",
  },
  {
    niveau: "basis",
    woord: "encryptie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het versleutelen van gegevens, zodat alleen wie de juiste sleutel heeft ze kan lezen.",
    voorbeeldzin: "Dankzij end-to-end-encryptie kan zelfs de chatdienst je berichten niet lezen.",
    herkomst: "Grieks kryptos (verborgen).",
    beeld: "Een brief die in een kluisje gaat waarvan alleen de ontvanger de code kent.",
  },
  {
    niveau: "basis",
    woord: "bandbreedte",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De hoeveelheid data die per seconde over een verbinding kan worden verstuurd.",
    voorbeeldzin: "Als het hele gezin tegelijk video's streamt, raakt de bandbreedte op.",
    herkomst: "Oorspronkelijk uit de radiotechniek: de breedte van een frequentieband.",
    beeld: "Een snelweg waarvan het aantal rijstroken bepaalt hoeveel auto's er tegelijk doorheen kunnen.",
  },
  {
    niveau: "basis",
    woord: "open source",
    woordsoort: "bijvoeglijk naamwoord",
    definitie: "Gezegd van software waarvan de broncode openbaar is en die iedereen mag bekijken, aanpassen en verspreiden.",
    voorbeeldzin: "Firefox en Linux zijn bekende voorbeelden van open source software.",
    herkomst: "Engels: open bron(code).",
    beeld: "Een restaurant waar het recept naast de kassa hangt en iedereen het mag meenemen en verbeteren.",
  },
  {
    niveau: "basis",
    woord: "phishing",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Oplichting waarbij criminelen zich voordoen als een betrouwbare partij om wachtwoorden of bankgegevens te ontfutselen.",
    voorbeeldzin: "De mail van 'de bank' die vroeg om je pincode te bevestigen, was phishing.",
    herkomst: "Engels, afgeleid van fishing (vissen), met de 'ph' uit hackerjargon.",
    beeld: "Een hengel met een nep-bankpas als aas die in je inbox bungelt.",
  },
  {
    niveau: "gevorderd",
    woord: "latentie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De vertraging tussen het versturen van een signaal of verzoek en het moment waarop het aankomt of er antwoord komt.",
    voorbeeldzin: "Bij online gamen is een lage latentie belangrijker dan een hoge downloadsnelheid.",
    herkomst: "Latijn latere (verborgen zijn).",
    beeld: "Een echo in de bergen: je roept, en pas even later hoor je antwoord.",
  },
  {
    niveau: "gevorderd",
    woord: "API",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een vastgelegde manier waarop softwareprogramma's met elkaar communiceren en gegevens uitwisselen.",
    voorbeeldzin: "De weer-app haalt zijn voorspellingen op via de API van een weerdienst.",
    herkomst: "Afkorting van het Engelse Application Programming Interface.",
    beeld: "Een ober die bestellingen van de gasten naar de keuken brengt en de gerechten weer terugbrengt.",
  },
  {
    niveau: "gevorderd",
    woord: "cloud computing",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het via internet gebruiken van rekenkracht, opslag en software op servers van een externe aanbieder.",
    voorbeeldzin: "Door cloud computing hoeft een start-up geen eigen serverruimte meer te bouwen.",
    herkomst: "Engels; een wolk was het gebruikelijke symbool voor internet in netwerkschema's.",
    beeld: "Een computer die als wolk boven de stad hangt, waar iedereen met een draadje op kan inpluggen.",
  },
  {
    niveau: "gevorderd",
    woord: "machine learning",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een vorm van kunstmatige intelligentie waarbij computers patronen leren uit voorbeelden, in plaats van dat elke regel wordt voorgeprogrammeerd.",
    voorbeeldzin: "Spamfilters gebruiken machine learning om nieuwe soorten ongewenste mail te herkennen.",
    herkomst: "Engels: machinaal leren.",
    beeld: "Een robot die na het bekijken van duizenden foto's zelf het verschil tussen katten en honden leert zien.",
  },
  {
    niveau: "gevorderd",
    woord: "tweefactorauthenticatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een inlogmethode waarbij je naast je wachtwoord nog een tweede bewijs nodig hebt, zoals een code op je telefoon.",
    voorbeeldzin: "Zet tweefactorauthenticatie aan, zodat een gestolen wachtwoord alleen niet genoeg is.",
    herkomst: "Grieks authentikos (echt, betrouwbaar).",
    beeld: "Een voordeur met twee sloten: de sleutel zit in je zak, de code staat op je telefoon.",
  },
  {
    niveau: "expert",
    woord: "blockchain",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een gedeeld, decentraal register waarin transacties in aan elkaar gekoppelde blokken worden vastgelegd die achteraf vrijwel niet te wijzigen zijn.",
    voorbeeldzin: "Bitcoin gebruikt een blockchain om alle transacties bij te houden.",
    herkomst: "Engels block (blok) + chain (ketting).",
    beeld: "Een ketting van glazen kluisjes waarin elk kluisje een afdruk van het vorige bevat, zodat knoeien meteen opvalt.",
  },
  {
    niveau: "expert",
    woord: "containerisatie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Het verpakken van software samen met alles wat ze nodig heeft, zodat ze op elke computer op dezelfde manier draait.",
    voorbeeldzin: "Dankzij containerisatie werkt de applicatie op de server precies zoals op de laptop van de ontwikkelaar.",
    herkomst: "Naar de zeecontainer, die goederenvervoer wereldwijd standaardiseerde.",
    beeld: "Een zeecontainer met een complete keuken erin, die je op elk schip kunt zetten en overal meteen kunt koken.",
  },
  {
    niveau: "expert",
    woord: "zero-day",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een beveiligingslek in software dat nog niet bekend is bij de maker, zodat er nog geen oplossing voor bestaat.",
    voorbeeldzin: "Criminelen betalen soms grote bedragen voor een zero-day in een populaire browser.",
    herkomst: "Engels: de maker heeft 'nul dagen' gehad om het lek te dichten.",
    beeld: "Een inbreker die een geheime achterdeur vindt waarvan de bewoners niet eens weten dat die bestaat.",
  },
  {
    niveau: "expert",
    woord: "technische schuld",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De extra kosten en moeite die later ontstaan doordat je in software nu kiest voor een snelle maar minder goede oplossing.",
    voorbeeldzin: "Na jaren van haastwerk was de technische schuld zo groot dat elke kleine aanpassing weken kostte.",
    herkomst: "Vertaling van technical debt, een term van programmeur Ward Cunningham.",
    beeld: "Een stapel afwas die je steeds laat staan, tot je geen schoon bord meer hebt.",
  },
  {
    niveau: "expert",
    woord: "taalmodel",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een AI-model dat getraind is op grote hoeveelheden tekst en daardoor tekst kan voorspellen, begrijpen en genereren.",
    voorbeeldzin: "Moderne chatbots zijn gebaseerd op een groot taalmodel.",
    herkomst: "Vertaling van het Engelse language model.",
    beeld: "Een reusachtige bibliotheek met een stem die elke zin die je begint kan afmaken.",
  },
  {
    niveau: "basis",
    woord: "cookie",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een klein bestandje dat een website op je apparaat opslaat om bijvoorbeeld je voorkeuren of inlog te onthouden, of je surfgedrag te volgen.",
    voorbeeldzin: "Door cookies te weigeren krijg je minder gepersonaliseerde advertenties.",
    herkomst: "Engels: koekje; afgeleid van het programmeursbegrip 'magic cookie'.",
    beeld: "Een koekje dat een kruimelspoor achterlaat van alle websites die je hebt bezocht.",
  },
  {
    niveau: "basis",
    woord: "malware",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Verzamelnaam voor schadelijke software, zoals virussen, spyware en ransomware.",
    voorbeeldzin: "Via een besmette bijlage kwam er malware op de computers van het bedrijf.",
    herkomst: "Engels malicious (kwaadaardig) + software.",
    beeld: "Een Trojaans paard vol kleine digitale inbrekers dat door de poort van je laptop rolt.",
  },
  {
    niveau: "gevorderd",
    woord: "ransomware",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Schadelijke software die bestanden versleutelt of blokkeert en losgeld eist om ze weer vrij te geven.",
    voorbeeldzin: "De universiteit betaalde losgeld nadat ransomware alle systemen had platgelegd.",
    herkomst: "Engels ransom (losgeld) + software.",
    beeld: "Een hangslot op al je fotoalbums met een briefje: 'Betaal, of je ziet ze nooit meer terug.'",
  },
  {
    niveau: "gevorderd",
    woord: "digitale kloof",
    woordsoort: "zelfstandig naamwoord",
    definitie: "De ongelijkheid tussen mensen die wel en niet goed toegang hebben tot internet en digitale vaardigheden.",
    voorbeeldzin: "Nu veel overheidszaken online gaan, groeit de zorg over de digitale kloof bij ouderen.",
    herkomst: "Samenstelling van digitaal en kloof.",
    beeld: "Een diepe kloof met aan de ene kant mensen met smartphones en aan de andere kant mensen die niet weten hoe ze moeten oversteken.",
  },
  {
    niveau: "expert",
    woord: "quantumcomputer",
    woordsoort: "zelfstandig naamwoord",
    definitie: "Een computer die rekent met qubits, die dankzij kwantumeffecten meerdere toestanden tegelijk kunnen aannemen, waardoor sommige berekeningen veel sneller gaan.",
    voorbeeldzin: "Een krachtige quantumcomputer zou de huidige versleuteling van internetverkeer kunnen kraken.",
    herkomst: "Latijn quantum (hoeveel), via de kwantummechanica.",
    beeld: "Een munt die tijdens het draaien tegelijk kop én munt is, en zo alle mogelijkheden in één keer probeert.",
  },
];
