// De ingebouwde woordenlijst. Nieuwe woorden of vakgebieden toevoegen? Kopieer een bestaand blok en pas het aan.
// Let bij de afleiders op: drie foute maar geloofwaardige betekenissen, even lang en in dezelfde stijl als de echte.

import type { Niveau, Woord } from "./types.ts";

export type BankWoord = Omit<Woord, "id" | "domein">;

export const WOORDENBANK: Record<string, BankWoord[]> = {
  "Algemene kennis": [
    {
      niveau: "basis",
      woord: "anachronisme",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Iets wat niet past in de tijd waarin het geplaatst wordt, zoals een voorwerp of gewoonte uit een andere periode.",
      voorbeeldzin: "Het polshorloge van de Romeinse soldaat in de film was een opvallend anachronisme.",
      herkomst: "Grieks ana (tegen, terug) + chronos (tijd).",
      beeld: "Een ridder in harnas die midden op het slagveld een selfie maakt met zijn smartphone.",
      emoji: "🏰📱",
      afleiders: [
        "Een woord dat van achter naar voren gelezen hetzelfde blijft.",
        "Een tijdrekening die op de stand van de maan is gebaseerd.",
        "Een gebeurtenis die precies tegelijk met een andere plaatsvindt.",
      ],
    },
    {
      niveau: "basis",
      woord: "paradox",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een uitspraak of situatie die tegenstrijdig lijkt, maar bij nader inzien toch waar of zinvol kan zijn.",
      voorbeeldzin: "Het is een paradox dat meer keuze mensen soms juist ongelukkiger maakt.",
      herkomst: "Grieks para (tegen) + doxa (mening): tegen de verwachting in.",
      beeld: "Een bordje met de tekst 'Negeer dit bordje', waar iedereen verward naar blijft staren.",
      emoji: "🪧🤔",
      afleiders: [
        "Een overdreven voorstelling van zaken om iets belachelijk te maken.",
        "Een voorbeeld dat als model dient voor anderen.",
        "De herhaling van hetzelfde woord aan het begin van opeenvolgende zinnen.",
      ],
    },
    {
      niveau: "basis",
      woord: "pragmatisch",
      woordsoort: "bijvoeglijk naamwoord",
      definitie: "Gericht op wat in de praktijk werkt, in plaats van op theorie of principes.",
      voorbeeldzin: "In plaats van eindeloos te vergaderen, koos de directeur voor een pragmatische oplossing.",
      herkomst: "Grieks pragma (handeling, zaak).",
      beeld: "Iemand die een wiebelende tafel niet repareert, maar er gewoon een bierviltje onder schuift.",
      emoji: "🪑🍺",
      afleiders: [
        "Streng vasthoudend aan regels en voorschriften.",
        "Geneigd om alles somber in te zien.",
        "Met veel omhaal van woorden en weinig inhoud.",
      ],
    },
    {
      niveau: "basis",
      woord: "euvel",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een gebrek, probleem of kwaal.",
      voorbeeldzin: "De nieuwe versie van de app verhelpt het euvel met de batterij.",
      herkomst: "Middelnederlands evel (kwaad), verwant aan het Engelse evil.",
      beeld: "Een klein grijs duiveltje dat in je fietsketting zit te knagen.",
      emoji: "🚲😈",
      afleiders: [
        "Een plechtige belofte tegenover een rechter.",
        "Een voordeel dat je onverwacht krijgt.",
        "Een dun laagje nevel boven het water.",
      ],
    },
    {
      niveau: "basis",
      woord: "cynisch",
      woordsoort: "bijvoeglijk naamwoord",
      definitie: "Wantrouwend over de goede bedoelingen van mensen; ervan uitgaand dat iedereen uit eigenbelang handelt.",
      voorbeeldzin: "Na jaren van gebroken beloftes keek ze cynisch naar elke nieuwe verkiezingscampagne.",
      herkomst: "Grieks kynikos (hondachtig), naar Oudgriekse filosofen die maatschappelijke normen minachtten.",
      beeld: "Een hond die met opgetrokken wenkbrauw naar een glimlachende verkoper kijkt.",
      emoji: "🐕🤨",
      afleiders: [
        "Steeds terugkerend in een vaste kringloop.",
        "Overdreven gevoelig en snel ontroerd.",
        "Streng en sober levend uit religieuze overtuiging.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "eufemisme",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een verzachtende omschrijving voor iets onaangenaams of pijnlijks.",
      voorbeeldzin: "'Heengaan' is een eufemisme voor sterven.",
      herkomst: "Grieks eu (goed) + phèmi (spreken).",
      beeld: "Een ontslagbrief verpakt in roze cadeaupapier met een strik erom.",
      emoji: "🎁📄",
      afleiders: [
        "Een overdrijving om iets extra te benadrukken.",
        "Een woord dat klinkt als het geluid dat het beschrijft.",
        "Een grappige verspreking die een onbewuste gedachte verraadt.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "ambivalent",
      woordsoort: "bijvoeglijk naamwoord",
      definitie: "Tegelijk tegenstrijdige gevoelens of houdingen hebbend tegenover iets.",
      voorbeeldzin: "Ik sta ambivalent tegenover de verhuizing: ik heb er zin in, maar zie er ook tegen op.",
      herkomst: "Latijn ambo (beide) + valere (waard zijn, gelden).",
      beeld: "Iemand die met één voet in een warm bad en met de andere in een emmer ijswater staat.",
      emoji: "🛁🧊",
      afleiders: [
        "Met beide handen even handig.",
        "Vaag en voor meerdere uitleg vatbaar.",
        "Onverschillig en zonder enige mening.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "precedent",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een eerder geval dat als voorbeeld of rechtvaardiging dient voor latere beslissingen.",
      voorbeeldzin: "Als we deze uitzondering toestaan, scheppen we een precedent.",
      herkomst: "Latijn praecedere (voorafgaan).",
      beeld: "Eén schaap springt over een hek, en de hele kudde springt er daarna achteraan.",
      emoji: "🐑🐑",
      afleiders: [
        "Een voorlopige schatting van de kosten.",
        "Iemand die een vergadering voorzit en leidt.",
        "Een formele waarschuwing voorafgaand aan een straf.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "dichotomie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een tweedeling in twee scherp tegengestelde delen of groepen.",
      voorbeeldzin: "De dichotomie tussen stad en platteland speelde een grote rol in de verkiezingen.",
      herkomst: "Grieks dicha (in tweeën) + temnein (snijden).",
      beeld: "Een taart die met één messnede in een zwarte en een witte helft wordt verdeeld.",
      emoji: "🎂🔪",
      afleiders: [
        "Een langdurige onenigheid binnen een familie.",
        "Een bestuur dat door twee personen tegelijk wordt geleid.",
        "Een reeks van twee boeken die bij elkaar horen.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "zeitgeist",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De heersende denkbeelden, smaak en stemming van een bepaalde periode.",
      voorbeeldzin: "De punkmuziek van eind jaren zeventig paste perfect bij de zeitgeist.",
      herkomst: "Duits Zeit (tijd) + Geist (geest).",
      beeld: "Een doorzichtige geest in een tijdmachine die bij elk decennium de mode van dat moment aantrekt.",
      emoji: "👻⏳",
      afleiders: [
        "Een overdreven verlangen naar vroeger.",
        "De tijd die nodig is om een gewoonte te veranderen.",
        "Het idee dat de geschiedenis zich steeds herhaalt.",
      ],
    },
    {
      niveau: "expert",
      woord: "epistemologie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het deel van de filosofie dat onderzoekt wat kennis is en hoe we iets kunnen weten.",
      voorbeeldzin: "In de epistemologie is de vraag of zintuiglijke waarneming betrouwbaar is een klassiek probleem.",
      herkomst: "Grieks epistèmè (kennis) + logos (leer).",
      beeld: "Een filosoof die met een vergrootglas naar zijn eigen hersenen tuurt en zich afvraagt: 'Weet ik dit echt?'",
      emoji: "🔍🧠",
      afleiders: [
        "De leer van de juiste manier van leven en handelen.",
        "De studie van de herkomst van woorden.",
        "De leer van het zijn en van wat er bestaat.",
      ],
    },
    {
      niveau: "expert",
      woord: "hermeneutiek",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De leer van het interpreteren en begrijpen van teksten, oorspronkelijk vooral religieuze en juridische teksten.",
      voorbeeldzin: "Wie een grondwetsartikel uitlegt, bedrijft eigenlijk hermeneutiek.",
      herkomst: "Grieks hermèneuein (uitleggen, vertalen), vaak in verband gebracht met Hermes, de boodschapper van de goden.",
      beeld: "Hermes met gevleugelde sandalen die gebogen zit over een oude perkamentrol om die te ontcijferen.",
      emoji: "📜🪽",
      afleiders: [
        "De kunst van het overtuigend spreken in het openbaar.",
        "De leer van geheime, magische kennis.",
        "Het vergelijken van handschriften om de oudste versie van een tekst te vinden.",
      ],
    },
    {
      niveau: "expert",
      woord: "teleologisch",
      woordsoort: "bijvoeglijk naamwoord",
      definitie: "Iets verklarend vanuit het doel waarnaar het streeft, in plaats van vanuit de oorzaak.",
      voorbeeldzin: "'De giraf heeft een lange nek om bij de bladeren te kunnen' is een teleologische verklaring.",
      herkomst: "Grieks telos (doel, einde) + logos (leer).",
      beeld: "Een pijl die al in de roos steekt en tevreden terugkijkt naar de boog.",
      emoji: "🎯🏹",
      afleiders: [
        "Betrekking hebbend op communicatie over grote afstand.",
        "Iets verklarend vanuit de oorzaak die eraan voorafging.",
        "Gericht op de mening van de meerderheid.",
      ],
    },
    {
      niveau: "expert",
      woord: "apocrief",
      woordsoort: "bijvoeglijk naamwoord",
      definitie: "Van twijfelachtige echtheid of herkomst; oorspronkelijk: niet opgenomen in de officiële bijbel.",
      voorbeeldzin: "Het verhaal dat Einstein slecht was in wiskunde is apocrief.",
      herkomst: "Grieks apokryphos (verborgen).",
      beeld: "Een stoffig boek dat uit de kloosterbibliotheek is verbannen en stiekem onder een deken wordt bewaard.",
      emoji: "📕🕯️",
      afleiders: [
        "Voorspellend over het einde der tijden.",
        "Door de kerk officieel heilig verklaard.",
        "Oorspronkelijk in het Grieks geschreven.",
      ],
    },
    {
      niveau: "expert",
      woord: "serendipiteit",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het doen van een gelukkige, onverwachte ontdekking terwijl je naar iets anders zoekt.",
      voorbeeldzin: "De ontdekking van penicilline wordt vaak genoemd als voorbeeld van serendipiteit.",
      herkomst: "Engels serendipity, bedacht door Horace Walpole naar het sprookje 'De drie prinsen van Serendip' (een oude naam voor Sri Lanka).",
      beeld: "Iemand die in de tuin naar zijn kwijtgeraakte sleutels graaft en een schatkist vindt.",
      emoji: "🔑💰",
      afleiders: [
        "Een diepe innerlijke rust die je na meditatie ervaart.",
        "Het geloof dat alles in het leven vooraf bepaald is.",
        "Het vermogen om de gevoelens van anderen aan te voelen.",
      ],
    },
  ],

  Politiek: [
    {
      niveau: "basis",
      woord: "coalitie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een samenwerkingsverband van meerdere politieke partijen die samen een regering vormen of steunen.",
      voorbeeldzin: "Na de verkiezingen duurde het maanden voordat er een coalitie was gevormd.",
      herkomst: "Latijn coalescere (samengroeien).",
      beeld: "Vier roeiers in verschillend gekleurde shirts die in één bootje proberen dezelfde kant op te roeien.",
      emoji: "🚣🤝",
      afleiders: [
        "Het geheel van partijen dat de regering niet steunt.",
        "Een tijdelijk verbod op het houden van demonstraties.",
        "Een stemming waarbij alle burgers over één vraag beslissen.",
      ],
    },
    {
      niveau: "basis",
      woord: "motie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een voorstel van Kamerleden waarin de Kamer een wens of oordeel uitspreekt, bijvoorbeeld een verzoek aan de regering.",
      voorbeeldzin: "De Kamer nam een motie aan die het kabinet vraagt de huurverhoging te bevriezen.",
      herkomst: "Latijn motio (beweging).",
      beeld: "Een Kamerlid dat een papieren vliegtuigje met 'Graag regelen!' erop naar de ministers gooit.",
      emoji: "✈️📝",
      afleiders: [
        "Een wetsvoorstel dat door de regering wordt ingediend.",
        "Het recht van de Kamer om een minister te ondervragen.",
        "Een wijziging in de tekst van een wetsvoorstel.",
      ],
    },
    {
      niveau: "basis",
      woord: "populisme",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een politieke stroming die 'het gewone volk' tegenover een als corrupt voorgestelde elite plaatst.",
      voorbeeldzin: "Politicologen discussiëren over de vraag of populisme een ideologie is of vooral een stijl.",
      herkomst: "Latijn populus (volk).",
      beeld: "Een spreker op een zeepkist die met zijn vinger naar een glazen paleis vol mensen in pakken wijst.",
      emoji: "📢🏛️",
      afleiders: [
        "Een stelsel waarin alle bedrijven eigendom van de staat zijn.",
        "Het streven naar zo min mogelijk overheidsbemoeienis met de economie.",
        "Een bestuursvorm waarin één partij alle macht heeft.",
      ],
    },
    {
      niveau: "basis",
      woord: "soevereiniteit",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het hoogste gezag van een staat: de onafhankelijke zeggenschap over het eigen grondgebied en de eigen zaken.",
      voorbeeldzin: "Critici vinden dat Europese regels de nationale soevereiniteit aantasten.",
      herkomst: "Oudfrans souverain, van Latijn super (boven).",
      beeld: "Een kasteel met een ophaalbrug waarvan alleen de eigen koning de hendel mag bedienen.",
      emoji: "🏰👑",
      afleiders: [
        "Het verdrag waarmee landen een oorlog officieel beëindigen.",
        "De plicht van een staat om vluchtelingen op te nemen.",
        "Een bestuursvorm met een koning of koningin als staatshoofd.",
      ],
    },
    {
      niveau: "basis",
      woord: "lobby",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het beïnvloeden van politici en beleidsmakers door belangengroepen, of de groep die dat doet.",
      voorbeeldzin: "De tabakslobby probeerde jarenlang strengere regels tegen te houden.",
      herkomst: "Engels lobby (hal), naar de hal van het parlement waar belangenbehartigers politici aanspraken.",
      beeld: "Een drukke hal waar mensen met aktetassen Kamerleden bij hun mouw grijpen.",
      emoji: "🏢💼",
      afleiders: [
        "Een geheime stemming binnen een politieke partij.",
        "Een groep Kamerleden die zich van hun partij heeft afgesplitst.",
        "De periode waarin een nieuwe regering wordt gevormd.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "polarisatie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het proces waarbij groepen in de samenleving steeds scherper tegenover elkaar komen te staan.",
      voorbeeldzin: "Sociale media worden vaak genoemd als oorzaak van de toenemende polarisatie.",
      herkomst: "Latijn polus (pool), zoals de twee tegenovergestelde polen van een magneet.",
      beeld: "Twee groepen mensen op ijsschotsen die steeds verder van elkaar af drijven.",
      emoji: "🧊↔️",
      afleiders: [
        "Het samengaan van twee politieke partijen.",
        "Het verdelen van een land in kleinere bestuurlijke eenheden.",
        "Het meten van de publieke opinie via peilingen.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "demissionair",
      woordsoort: "bijvoeglijk naamwoord",
      definitie: "Gezegd van een kabinet dat zijn ontslag heeft aangeboden en alleen nog de lopende zaken afhandelt.",
      voorbeeldzin: "Een demissionair kabinet neemt doorgaans geen omstreden besluiten.",
      herkomst: "Frans démission (ontslag).",
      beeld: "Een minister met een verhuisdoos op het bureau, die alleen nog de post afhandelt.",
      emoji: "📦🗂️",
      afleiders: [
        "Met een absolute meerderheid in beide Kamers.",
        "Pas beëdigd en nog in de eerste honderd dagen.",
        "Bestaande uit ministers zonder partijbinding.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "subsidiariteit",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het beginsel dat taken worden uitgevoerd op het laagste bestuursniveau waar dat nog goed kan.",
      voorbeeldzin: "Volgens het subsidiariteitsbeginsel moet de EU zich niet bemoeien met wat lidstaten zelf goed kunnen regelen.",
      herkomst: "Latijn subsidium (hulp, reserve).",
      beeld: "Een reus die pas komt helpen als het kleine dorpje het echt niet zelf kan.",
      emoji: "🏘️🗿",
      afleiders: [
        "Het verstrekken van subsidies aan kleine bedrijven.",
        "De plicht van lidstaten om EU-wetten letterlijk over te nemen.",
        "Het principe dat de hoogste rechter altijd het laatste woord heeft.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "technocratie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Bestuur door deskundigen en specialisten in plaats van door gekozen politici.",
      voorbeeldzin: "Critici noemden het kabinet van experts een vorm van technocratie.",
      herkomst: "Grieks technè (vakmanschap) + kratos (macht).",
      beeld: "Een parlement vol mensen in witte laboratoriumjassen met rekenmachines in plaats van stembiljetten.",
      emoji: "🥼🧮",
      afleiders: [
        "Bestuur door de rijkste burgers van een land.",
        "Bestuur door een kleine groep machthebbers.",
        "Een regering die technologie inzet om burgers te bespioneren.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "trias politica",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De scheiding van de staatsmacht in een wetgevende, een uitvoerende en een rechterlijke macht.",
      voorbeeldzin: "Volgens de trias politica mag een minister zich niet met lopende rechtszaken bemoeien.",
      herkomst: "Latijn voor 'politieke driedeling'; bekend geworden door de Franse filosoof Montesquieu.",
      beeld: "Een krukje met drie poten: haal er één weg en alles valt om.",
      emoji: "🪑⚖️",
      afleiders: [
        "Een samenwerking van drie partijen in één kabinet.",
        "De drie fasen die een wetsvoorstel doorloopt.",
        "Een verdrag tussen drie grootmachten.",
      ],
    },
    {
      niveau: "expert",
      woord: "hegemonie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De overheersende positie of invloed van één staat of groep over anderen, ook op cultureel en ideologisch gebied.",
      voorbeeldzin: "Na de Koude Oorlog spraken velen van de Amerikaanse hegemonie.",
      herkomst: "Grieks hègemonia (leiderschap).",
      beeld: "Eén reusachtige boom waarvan de kruin alle kleinere bomen in de schaduw zet.",
      emoji: "🌳🌱",
      afleiders: [
        "Een evenwicht van macht tussen meerdere grote landen.",
        "Een verbond van staten met een gemeenschappelijk leger.",
        "Het afstaan van grondgebied na een verloren oorlog.",
      ],
    },
    {
      niveau: "expert",
      woord: "realpolitik",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Politiek die zich laat leiden door praktische belangen en machtsverhoudingen in plaats van door idealen of moraal.",
      voorbeeldzin: "Uit realpolitik bleef het land handel drijven met het regime, ondanks de mensenrechtenschendingen.",
      herkomst: "Duits, 19e eeuw; vaak verbonden met het beleid van de Pruisische staatsman Bismarck.",
      beeld: "Een diplomaat die met één hand een vredesduif vasthoudt en met de andere een oliecontract tekent.",
      emoji: "🕊️🛢️",
      afleiders: [
        "Politiek die uitsluitend gebaseerd is op wetenschappelijke feiten.",
        "Het beleid om bij conflicten altijd neutraal te blijven.",
        "Politiek die draait om directe inspraak van burgers.",
      ],
    },
    {
      niveau: "expert",
      woord: "filibuster",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het extreem lang aan het woord blijven om een stemming te vertragen of te blokkeren.",
      voorbeeldzin: "Een Amerikaanse senator hield in 1957 een filibuster van meer dan 24 uur.",
      herkomst: "Via het Spaanse filibustero (vrijbuiter, piraat).",
      beeld: "Een piraat achter het spreekgestoelte die urenlang blijft voorlezen uit het telefoonboek.",
      emoji: "🏴‍☠️🎤",
      afleiders: [
        "Het uitlekken van vertrouwelijke stukken naar de pers.",
        "Het stemmen namens een afwezig parlementslid.",
        "Een onverwachte overstap naar een andere partij vlak voor een stemming.",
      ],
    },
    {
      niveau: "expert",
      woord: "gerrymandering",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het zo indelen van kiesdistricten dat één partij er voordeel van heeft.",
      voorbeeldzin: "Door gerrymandering kon de partij met minder stemmen toch de meeste zetels winnen.",
      herkomst: "Naar de Amerikaanse gouverneur Elbridge Gerry (1812), wiens nieuwe kiesdistrict op een salamander leek.",
      beeld: "Een landkaart waarop een kiesdistrict als een kronkelende salamander is ingetekend.",
      emoji: "🦎🗺️",
      afleiders: [
        "Het kopen van stemmen met geld of gunsten.",
        "Het uitstellen van verkiezingen tijdens een crisis.",
        "Het hertellen van stemmen door een onafhankelijke commissie.",
      ],
    },
    {
      niveau: "expert",
      woord: "cordon sanitaire",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De afspraak van partijen om niet samen te werken met een bepaalde, vaak extreme, partij.",
      voorbeeldzin: "In België houden de meeste partijen al sinds 1989 een cordon sanitaire in stand rond extreemrechts.",
      herkomst: "Frans: 'hygiënische afzetting'; oorspronkelijk een quarantainegordel tegen besmettelijke ziektes.",
      beeld: "Een partij binnen een kring van rood-wit afzetlint, terwijl iedereen op veilige afstand blijft.",
      emoji: "🚧🔴",
      afleiders: [
        "Een zone rond het parlementsgebouw waar niet gedemonstreerd mag worden.",
        "Een wet die partijen verplicht hun financiën openbaar te maken.",
        "Een verbod op campagne voeren vlak voor de verkiezingen.",
      ],
    },
  ],

  Biologie: [
    {
      niveau: "basis",
      woord: "fotosynthese",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het proces waarbij planten met behulp van licht water en koolstofdioxide omzetten in suikers en zuurstof.",
      voorbeeldzin: "Zonder fotosynthese zou er nauwelijks zuurstof in de atmosfeer zijn.",
      herkomst: "Grieks phoos (licht) + synthesis (samenstelling).",
      beeld: "Een blad met een klein zonnepaneel dat suikerklontjes en zuurstofbelletjes uitspuugt.",
      emoji: "🌿☀️",
      afleiders: [
        "Het proces waarbij cellen suikers afbreken om energie vrij te maken.",
        "Het transport van water door de vaten van een plant.",
        "Het verspreiden van zaden door wind of dieren.",
      ],
    },
    {
      niveau: "basis",
      woord: "symbiose",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het langdurig samenleven van twee verschillende soorten, vaak tot wederzijds voordeel.",
      voorbeeldzin: "Clownvissen leven in symbiose met zeeanemonen.",
      herkomst: "Grieks sym (samen) + bios (leven).",
      beeld: "Een clownvis die veilig tussen de prikkende tentakels van een anemoon woont en ze schoonhoudt.",
      emoji: "🐠🪸",
      afleiders: [
        "Het ontstaan van een nieuwe soort uit een bestaande soort.",
        "Een ziekte die van dier op mens kan overgaan.",
        "De concurrentie tussen soorten om hetzelfde voedsel.",
      ],
    },
    {
      niveau: "basis",
      woord: "mutatie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een verandering in het DNA van een organisme, die erfelijk kan zijn.",
      voorbeeldzin: "Een enkele mutatie kan ervoor zorgen dat een bacterie ongevoelig wordt voor antibiotica.",
      herkomst: "Latijn mutare (veranderen).",
      beeld: "Iemand die een lang recept overschrijft, per ongeluk één letter verandert, en nu wordt de taart blauw.",
      emoji: "⌨️🎂",
      afleiders: [
        "Het samensmelten van een eicel en een zaadcel.",
        "De deling van een cel in twee identieke dochtercellen.",
        "Het aanpassen van gedrag aan een nieuwe omgeving.",
      ],
    },
    {
      niveau: "basis",
      woord: "ecosysteem",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een gemeenschap van organismen samen met hun omgeving, waarin ze allemaal op elkaar inwerken.",
      voorbeeldzin: "De Waddenzee is een uniek ecosysteem.",
      herkomst: "Grieks oikos (huis) + systema (geheel).",
      beeld: "Een afgesloten glazen pot waarin planten, slakjes, water en licht samen een klein wereldje vormen.",
      emoji: "🫙🐌",
      afleiders: [
        "De indeling van alle levende wezens in groepen.",
        "De totale hoeveelheid levende organismen op aarde.",
        "Een lijst van bedreigde diersoorten in een gebied.",
      ],
    },
    {
      niveau: "basis",
      woord: "metabolisme",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Stofwisseling: alle chemische processen waarmee een organisme energie en bouwstoffen verkrijgt en verwerkt.",
      voorbeeldzin: "Kolibries hebben een extreem snel metabolisme.",
      herkomst: "Grieks metabolè (verandering).",
      beeld: "Een drukke fabriek in je buik waar voedsel binnenkomt en energie in batterijen de deur uit gaat.",
      emoji: "🏭🔋",
      afleiders: [
        "Het vermogen van een organisme om zich voort te planten.",
        "De groei van een embryo tot een volwassen organisme.",
        "De verdediging van het lichaam tegen ziekteverwekkers.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "homeostase",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het vermogen van een organisme om zijn interne omstandigheden, zoals temperatuur en bloedsuiker, stabiel te houden.",
      voorbeeldzin: "Zweten is een manier waarop het lichaam de homeostase van de lichaamstemperatuur bewaart.",
      herkomst: "Grieks homoios (gelijk) + stasis (stilstand).",
      beeld: "Een thermostaat in je hoofd die de verwarming aan- en uitzet om precies 37 graden te houden.",
      emoji: "🌡️🧠",
      afleiders: [
        "Het verschijnsel dat nakomelingen op hun ouders lijken.",
        "Het stilvallen van de groei bij een tekort aan voedsel.",
        "De voorkeur van dieren om met soortgenoten te paren.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "endemisch",
      woordsoort: "bijvoeglijk naamwoord",
      definitie: "Alleen van nature voorkomend in één bepaald gebied.",
      voorbeeldzin: "De dodo was endemisch op Mauritius.",
      herkomst: "Grieks endèmos (inheems), van en (in) + dèmos (volk).",
      beeld: "Een schildpad met een paspoort waarin staat: 'Mag dit eiland nooit verlaten'.",
      emoji: "🐢🏝️",
      afleiders: [
        "Zich snel over de hele wereld verspreidend.",
        "Door de mens ingevoerd vanuit een ander gebied.",
        "Op het punt staand om uit te sterven.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "enzym",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een eiwit dat een chemische reactie in een organisme versnelt zonder zelf te worden verbruikt.",
      voorbeeldzin: "Het enzym amylase in speeksel begint al in je mond met het afbreken van zetmeel.",
      herkomst: "Grieks en (in) + zymè (zuurdesem, gist).",
      beeld: "Een klein schaartje dat razendsnel lange kettingen doorknipt en daarna onbeschadigd verdergaat met de volgende.",
      emoji: "✂️⛓️",
      afleiders: [
        "Een hormoon dat de bloedsuikerspiegel verlaagt.",
        "Een bouwsteen waaruit DNA is opgebouwd.",
        "Een vetachtige stof waaruit celwanden van dieren bestaan.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "fenotype",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De waarneembare eigenschappen van een organisme, zoals uiterlijk en gedrag, als resultaat van genen en omgeving.",
      voorbeeldzin: "Eeneiige tweelingen hebben dezelfde genen, maar hun fenotype kan door hun leefstijl verschillen.",
      herkomst: "Grieks phainein (tonen) + typos (vorm).",
      beeld: "Twee identieke fietsen uit dezelfde fabriek: de een glanst in de schuur, de ander roest na jaren in de regen.",
      emoji: "🚲🌧️",
      afleiders: [
        "De volledige genetische code van een organisme.",
        "Een groep organismen die onderling nakomelingen kunnen krijgen.",
        "Een gen dat alleen tot uiting komt als het dubbel aanwezig is.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "mitochondrium",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een onderdeel van de cel dat via de celademhaling energie (ATP) produceert.",
      voorbeeldzin: "Mitochondriën hebben hun eigen DNA, dat je alleen van je moeder erft.",
      herkomst: "Grieks mitos (draad) + chondrion (korreltje).",
      beeld: "Kleine energiecentrales in de vorm van boontjes die in elke cel staan te zoemen.",
      emoji: "⚡🫘",
      afleiders: [
        "Het deel van een plantencel waarin fotosynthese plaatsvindt.",
        "Het deel van de cel waarin het DNA ligt opgeslagen.",
        "Het deel van de cel dat eiwitten in blaasjes verpakt.",
      ],
    },
    {
      niveau: "expert",
      woord: "apoptose",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Geprogrammeerde celdood: het gecontroleerd opruimen van cellen die beschadigd zijn of niet meer nodig zijn.",
      voorbeeldzin: "Bij een embryo zorgt apoptose ervoor dat de vliezen tussen de vingers verdwijnen.",
      herkomst: "Grieks apoptosis (het afvallen, zoals bladeren van een boom).",
      beeld: "Herfstbladeren die keurig één voor één loslaten, zodat de boom gezond de winter in gaat.",
      emoji: "🍂🌳",
      afleiders: [
        "Ongecontroleerde celdeling die tot een tumor leidt.",
        "Het versmelten van twee cellen tot één cel.",
        "Het afsterven van weefsel door een tekort aan zuurstof.",
      ],
    },
    {
      niveau: "expert",
      woord: "epigenetica",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De studie van erfelijke veranderingen in genactiviteit die niet berusten op veranderingen in de DNA-volgorde zelf.",
      voorbeeldzin: "Onderzoek naar kinderen van moeders uit de Hongerwinter laat zien hoe epigenetica de gezondheid kan beïnvloeden.",
      herkomst: "Grieks epi (bovenop) + genetica.",
      beeld: "Een pianopartituur (het DNA) waarop met potlood staat welke passages zacht of helemaal niet gespeeld worden.",
      emoji: "🎹✏️",
      afleiders: [
        "Het gericht veranderen van DNA met moleculaire scharen.",
        "De studie van erfelijkheid bij uitgestorven soorten.",
        "Het in kaart brengen van alle genen van een organisme.",
      ],
    },
    {
      niveau: "expert",
      woord: "allopatrisch",
      woordsoort: "bijvoeglijk naamwoord",
      definitie: "Gezegd van soortvorming die ontstaat doordat populaties geografisch van elkaar gescheiden raken.",
      voorbeeldzin: "Wanneer een bergketen een populatie in tweeën splitst, kan allopatrische soortvorming optreden.",
      herkomst: "Grieks allos (ander) + patris (vaderland).",
      beeld: "Een groep muizen die door een nieuwe rivier in tweeën wordt gesplitst en aan beide oevers anders evolueert.",
      emoji: "🐭🌊",
      afleiders: [
        "In hetzelfde gebied levend zonder zich met elkaar te vermengen.",
        "Ontstaan door kruising van twee verschillende soorten.",
        "Afstammend van één gemeenschappelijke voorouder.",
      ],
    },
    {
      niveau: "expert",
      woord: "trofisch niveau",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De positie van een organisme in een voedselketen, zoals producent, planteneter of roofdier.",
      voorbeeldzin: "Bij elke stap naar een hoger trofisch niveau gaat ongeveer negentig procent van de energie verloren.",
      herkomst: "Grieks trophè (voeding).",
      beeld: "Een piramide met etages: gras onderin, konijnen daarboven en een vos helemaal bovenop.",
      emoji: "🌾🐇🦊",
      afleiders: [
        "De mate waarin een soort zich aan zijn omgeving heeft aangepast.",
        "Het gemiddelde aantal nakomelingen van een organisme.",
        "De hoogte boven zeeniveau waarop een soort voorkomt.",
      ],
    },
    {
      niveau: "expert",
      woord: "convergente evolutie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het onafhankelijk ontstaan van vergelijkbare eigenschappen bij niet-verwante soorten die zich aan vergelijkbare omstandigheden aanpassen.",
      voorbeeldzin: "De vleugels van vleermuizen en vogels zijn een voorbeeld van convergente evolutie.",
      herkomst: "Latijn convergere (naar elkaar toe buigen, samenkomen).",
      beeld: "Een haai en een dolfijn die geen familie zijn, maar toch in hetzelfde gestroomlijnde pak op een feest verschijnen.",
      emoji: "🦈🐬",
      afleiders: [
        "Het opsplitsen van één soort in veel nieuwe soorten.",
        "Het samen evolueren van twee soorten die elkaar beïnvloeden.",
        "Het terugkeren van een voorouderlijk kenmerk na vele generaties.",
      ],
    },
  ],

  Natuurkunde: [
    {
      niveau: "basis",
      woord: "inertie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Traagheid: de neiging van een voorwerp om in rust of in beweging te blijven zolang er geen kracht op werkt.",
      voorbeeldzin: "Door inertie schiet je naar voren als de bus plotseling remt.",
      herkomst: "Latijn iners (traag, inactief).",
      beeld: "Een ijshockeypuck die over het ijs blijft glijden en weigert te stoppen.",
      emoji: "🏒🧊",
      afleiders: [
        "De kracht waarmee twee massa's elkaar aantrekken.",
        "Het omzetten van bewegingsenergie in warmte.",
        "De snelheid waarmee een voorwerp van richting verandert.",
      ],
    },
    {
      niveau: "basis",
      woord: "frequentie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het aantal trillingen of herhalingen per seconde, uitgedrukt in hertz.",
      voorbeeldzin: "Een geluid met een hogere frequentie hoor je als een hogere toon.",
      herkomst: "Latijn frequens (talrijk, vaak voorkomend).",
      beeld: "Een kolibrie die zo vaak per seconde met zijn vleugels slaat dat ze zoemen.",
      emoji: "🐦〰️",
      afleiders: [
        "De hoogte van een golf, gemeten vanaf de evenwichtsstand.",
        "De afstand tussen twee toppen van een golf.",
        "De snelheid waarmee geluid zich voortplant.",
      ],
    },
    {
      niveau: "basis",
      woord: "condensatie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De overgang van een gas naar een vloeistof, bijvoorbeeld als waterdamp afkoelt.",
      voorbeeldzin: "Door condensatie verschijnen er druppels op de buitenkant van een koud glas.",
      herkomst: "Latijn condensare (verdichten).",
      beeld: "Een badkamerspiegel die na een warme douche langzaam beslaat.",
      emoji: "🚿🪞",
      afleiders: [
        "De overgang van een vaste stof direct naar een gas.",
        "De overgang van een vloeistof naar een vaste stof.",
        "Het uitzetten van een stof bij verwarming.",
      ],
    },
    {
      niveau: "basis",
      woord: "geleider",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een materiaal waar elektrische stroom of warmte gemakkelijk doorheen kan.",
      voorbeeldzin: "Koper is een goede geleider en wordt daarom in elektriciteitskabels gebruikt.",
      herkomst: "Van het werkwoord geleiden (doorvoeren, leiden).",
      beeld: "Een brede snelweg waarover elektronen zonder file voortrazen.",
      emoji: "🛣️⚡",
      afleiders: [
        "Een materiaal dat elektrische stroom tegenhoudt.",
        "Een apparaat dat wisselstroom omzet in gelijkstroom.",
        "Een onderdeel dat elektrische lading tijdelijk opslaat.",
      ],
    },
    {
      niveau: "basis",
      woord: "brandpunt",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het punt waar evenwijdige lichtstralen samenkomen nadat ze door een lens zijn gebroken of door een holle spiegel zijn teruggekaatst.",
      voorbeeldzin: "Met een vergrootglas kun je zonlicht in het brandpunt zo sterk bundelen dat papier gaat smeulen.",
      herkomst: "Letterlijk: het punt waar het brandt.",
      beeld: "Een vergrootglas dat een felle stip zonlicht op een blad papier laat roken.",
      emoji: "🔍🔥",
      afleiders: [
        "Het punt waar een voorwerp in evenwicht is.",
        "De temperatuur waarbij een stof vlam vat.",
        "Het dikste punt in het midden van een lens.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "entropie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een maat voor de wanorde van een systeem; in een afgesloten systeem neemt ze nooit af.",
      voorbeeldzin: "Dat een gebroken kopje nooit vanzelf weer heel wordt, heeft te maken met entropie.",
      herkomst: "Grieks en (in) + tropè (verandering); bedacht door de Duitse natuurkundige Rudolf Clausius.",
      beeld: "Een opgeruimde kamer die zonder dat iemand iets doet steeds rommeliger lijkt te worden.",
      emoji: "🧹🌀",
      afleiders: [
        "De hoeveelheid energie die nodig is om een stof één graad te verwarmen.",
        "De kracht die een voorwerp in een cirkelbaan houdt.",
        "De totale hoeveelheid energie die een systeem bevat.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "impuls",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De hoeveelheid beweging van een voorwerp: massa maal snelheid.",
      voorbeeldzin: "Bij een botsing blijft de totale impuls van de biljartballen behouden.",
      herkomst: "Latijn impellere (voortstuwen).",
      beeld: "Een zware vrachtwagen en een razendsnelle tennisbal die allebei lastig te stoppen zijn.",
      emoji: "🚚🎾",
      afleiders: [
        "De kracht per oppervlakte-eenheid.",
        "De energie die een voorwerp heeft door zijn hoogte.",
        "De verandering van snelheid per seconde.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "halfwaardetijd",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De tijd waarin de helft van een hoeveelheid radioactieve atoomkernen vervalt.",
      voorbeeldzin: "Koolstof-14 heeft een halfwaardetijd van ongeveer 5730 jaar.",
      herkomst: "Samenstelling van half, waarde en tijd.",
      beeld: "Een zak snoep waaruit elke vijf minuten de helft verdwijnt, maar die nooit helemaal leeg raakt.",
      emoji: "🍬⏳",
      afleiders: [
        "De tijd die licht nodig heeft om van de zon naar de aarde te reizen.",
        "De helft van de totale levensduur van een ster.",
        "De tijd waarin een voorwerp tot de helft van zijn temperatuur afkoelt.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "interferentie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het verschijnsel dat golven elkaar versterken of uitdoven wanneer ze samenkomen.",
      voorbeeldzin: "De kleuren op een zeepbel ontstaan door interferentie van licht.",
      herkomst: "Latijn inter (tussen) + ferire (slaan).",
      beeld: "Twee stenen in een vijver waarvan de kringen elkaar kruisen, zodat het water op sommige plekken hoger en op andere vlak wordt.",
      emoji: "🪨💧",
      afleiders: [
        "Het buigen van een golf om een obstakel heen.",
        "Het terugkaatsen van een golf tegen een oppervlak.",
        "Het van richting veranderen van licht bij de overgang naar een ander materiaal.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "supergeleiding",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het verschijnsel dat sommige materialen bij zeer lage temperatuur stroom geleiden zonder enige weerstand.",
      voorbeeldzin: "MRI-scanners gebruiken supergeleidende magneten die met vloeibaar helium worden gekoeld.",
      herkomst: "Ontdekt in 1911 door de Nederlandse natuurkundige Heike Kamerlingh Onnes in Leiden.",
      beeld: "Een ijskoude glijbaan waarop elektronen eindeloos doorglijden zonder ooit af te remmen.",
      emoji: "🛝❄️",
      afleiders: [
        "Het versterken van een elektrisch signaal met een transistor.",
        "Het geleiden van stroom door een gas, zoals in een tl-buis.",
        "Het opwekken van stroom door licht op een materiaal te laten vallen.",
      ],
    },
    {
      niveau: "expert",
      woord: "kwantumverstrengeling",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een verschijnsel waarbij deeltjes zo verbonden zijn dat hun toestanden niet los van elkaar te beschrijven zijn, ongeacht de afstand.",
      voorbeeldzin: "Onderzoekers in Delft toonden in 2015 kwantumverstrengeling aan tussen deeltjes die ruim een kilometer uit elkaar lagen.",
      herkomst: "Vertaling van het Duitse Verschränkung, een term van Erwin Schrödinger.",
      beeld: "Twee dobbelstenen in verschillende steden die, als je ze gooit, altijd bij elkaar passende uitkomsten geven.",
      emoji: "🎲🎲",
      afleiders: [
        "Het verschijnsel dat een deeltje door een barrière heen kan gaan.",
        "Het principe dat je plaats en snelheid niet tegelijk exact kunt kennen.",
        "Het samensmelten van atoomkernen onder extreme druk en temperatuur.",
      ],
    },
    {
      niveau: "expert",
      woord: "golf-deeltjedualiteit",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het inzicht dat licht en materie zich, afhankelijk van het experiment, als golf of als deeltje gedragen.",
      voorbeeldzin: "Het dubbelspleetexperiment met elektronen laat de golf-deeltjedualiteit zien.",
      herkomst: "Latijn dualis (tweeledig).",
      beeld: "Een kameleon die de ene keer als rimpeling door het water gaat en de andere keer als knikker over de vloer rolt.",
      emoji: "🦎〰️",
      afleiders: [
        "Het verschijnsel dat elk deeltje een antideeltje heeft.",
        "De gelijkwaardigheid van massa en energie.",
        "Het verschil tussen de klassieke natuurkunde en de relativiteitstheorie.",
      ],
    },
    {
      niveau: "expert",
      woord: "tijddilatatie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het effect uit de relativiteitstheorie dat tijd langzamer verstrijkt bij hoge snelheid of sterke zwaartekracht, gezien door een andere waarnemer.",
      voorbeeldzin: "Gps-satellieten moeten corrigeren voor tijddilatatie, anders wordt de plaatsbepaling snel onnauwkeurig.",
      herkomst: "Latijn dilatare (uitrekken).",
      beeld: "Een astronaut die na een razendsnelle ruimtereis terugkomt en jonger is dan zijn tweelingbroer.",
      emoji: "🚀👴",
      afleiders: [
        "Het uitdijen van het heelal in de loop van de tijd.",
        "Het korter worden van voorwerpen in hun bewegingsrichting.",
        "De vertraging van licht in een dicht materiaal zoals glas.",
      ],
    },
    {
      niveau: "expert",
      woord: "lagrangepunt",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een punt in de ruimte waar een klein object door de zwaartekracht van twee grote hemellichamen op een vaste plek ten opzichte van beide kan blijven.",
      voorbeeldzin: "De James Webb-ruimtetelescoop draait rond het tweede lagrangepunt van de zon en de aarde.",
      herkomst: "Naar de wiskundige Joseph-Louis Lagrange (18e eeuw).",
      beeld: "Een ballon die precies tussen twee magneten blijft zweven.",
      emoji: "🎈🧲",
      afleiders: [
        "Het punt in een baan dat het dichtst bij de zon ligt.",
        "De grens rond een zwart gat waarachter niets kan ontsnappen.",
        "Het punt waar een komeet zijn staart begint te vormen.",
      ],
    },
    {
      niveau: "expert",
      woord: "neutrino",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een elektrisch neutraal elementair deeltje met een extreem kleine massa, dat bijna nergens mee reageert.",
      voorbeeldzin: "Elke seconde gaan er miljarden neutrino's van de zon dwars door je lichaam heen.",
      herkomst: "Italiaans voor 'klein neutraaltje'; de naam komt van Enrico Fermi.",
      beeld: "Een onzichtbaar spookje dat dwars door muren, mensen en zelfs de hele aarde heen vliegt.",
      emoji: "👻🌍",
      afleiders: [
        "Het elektrisch neutrale deeltje in de atoomkern.",
        "Het lichtdeeltje dat de elektromagnetische kracht overbrengt.",
        "De positief geladen tegenhanger van het elektron.",
      ],
    },
  ],

  Tech: [
    {
      niveau: "basis",
      woord: "algoritme",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een reeks duidelijke stappen of instructies om een probleem op te lossen of een taak uit te voeren.",
      voorbeeldzin: "Het algoritme van de streamingdienst bepaalt welke series je te zien krijgt.",
      herkomst: "Naar de Perzische wiskundige al-Chwarizmi (9e eeuw).",
      beeld: "Een kok die stap voor stap een recept volgt zonder ook maar één regel over te slaan.",
      emoji: "👨‍🍳📋",
      afleiders: [
        "Een programma dat zich zelfstandig over computers verspreidt.",
        "Een eenheid voor de rekenkracht van een processor.",
        "Een verzameling gegevens in tabelvorm.",
      ],
    },
    {
      niveau: "basis",
      woord: "encryptie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het versleutelen van gegevens, zodat alleen wie de juiste sleutel heeft ze kan lezen.",
      voorbeeldzin: "Dankzij end-to-end-encryptie kan zelfs de chatdienst je berichten niet lezen.",
      herkomst: "Grieks kryptos (verborgen).",
      beeld: "Een brief die in een kluisje gaat waarvan alleen de ontvanger de code kent.",
      emoji: "🔐✉️",
      afleiders: [
        "Het comprimeren van bestanden zodat ze minder ruimte innemen.",
        "Het maken van een reservekopie van gegevens.",
        "Het controleren of een wachtwoord sterk genoeg is.",
      ],
    },
    {
      niveau: "basis",
      woord: "bandbreedte",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De hoeveelheid data die per seconde over een verbinding kan worden verstuurd.",
      voorbeeldzin: "Als het hele gezin tegelijk video's streamt, raakt de bandbreedte op.",
      herkomst: "Oorspronkelijk uit de radiotechniek: de breedte van een frequentieband.",
      beeld: "Een snelweg waarvan het aantal rijstroken bepaalt hoeveel auto's er tegelijk doorheen kunnen.",
      emoji: "🛣️🚗",
      afleiders: [
        "Het aantal apparaten dat tegelijk met een netwerk verbonden kan zijn.",
        "De maximale opslagcapaciteit van een harde schijf.",
        "Het bereik van een wifi-router in meters.",
      ],
    },
    {
      niveau: "basis",
      woord: "open source",
      woordsoort: "bijvoeglijk naamwoord",
      definitie: "Gezegd van software waarvan de broncode openbaar is en die iedereen mag bekijken, aanpassen en verspreiden.",
      voorbeeldzin: "Firefox en Linux zijn bekende voorbeelden van open source software.",
      herkomst: "Engels: open bron(code).",
      beeld: "Een restaurant waar het recept naast de kassa hangt en iedereen het mag meenemen en verbeteren.",
      emoji: "📖🍝",
      afleiders: [
        "Gezegd van software die gratis is, maar waarvan de code geheim blijft.",
        "Gezegd van software die alleen online in de browser werkt.",
        "Gezegd van software die door de overheid is goedgekeurd.",
      ],
    },
    {
      niveau: "basis",
      woord: "phishing",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Oplichting waarbij criminelen zich voordoen als een betrouwbare partij om wachtwoorden of bankgegevens te ontfutselen.",
      voorbeeldzin: "De mail van 'de bank' die vroeg om je pincode te bevestigen, was phishing.",
      herkomst: "Engels, afgeleid van fishing (vissen), met de 'ph' uit hackerjargon.",
      beeld: "Een hengel met een nep-bankpas als aas die in je inbox bungelt.",
      emoji: "🎣💳",
      afleiders: [
        "Het ongevraagd versturen van grote hoeveelheden reclamemail.",
        "Het gijzelen van bestanden totdat er losgeld is betaald.",
        "Het platleggen van een website door hem te overspoelen met nepverkeer.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "latentie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De vertraging tussen het versturen van een signaal of verzoek en het moment waarop het aankomt of er antwoord komt.",
      voorbeeldzin: "Bij online gamen is een lage latentie belangrijker dan een hoge downloadsnelheid.",
      herkomst: "Latijn latere (verborgen zijn).",
      beeld: "Een echo in de bergen: je roept, en pas even later hoor je antwoord.",
      emoji: "🏔️📣",
      afleiders: [
        "Het percentage datapakketten dat onderweg verloren gaat.",
        "De tijd die een computer nodig heeft om op te starten.",
        "De maximale hoeveelheid werkgeheugen van een apparaat.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "API",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een vastgelegde manier waarop softwareprogramma's met elkaar communiceren en gegevens uitwisselen.",
      voorbeeldzin: "De weer-app haalt zijn voorspellingen op via de API van een weerdienst.",
      herkomst: "Afkorting van het Engelse Application Programming Interface.",
      beeld: "Een ober die bestellingen van de gasten naar de keuken brengt en de gerechten weer terugbrengt.",
      emoji: "🧑‍🍳🍽️",
      afleiders: [
        "Een programmeertaal voor het bouwen van websites.",
        "Een beveiligde verbinding tussen twee netwerken.",
        "Een opslagplaats voor de broncode van een project.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "cloud computing",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het via internet gebruiken van rekenkracht, opslag en software op servers van een externe aanbieder.",
      voorbeeldzin: "Door cloud computing hoeft een start-up geen eigen serverruimte meer te bouwen.",
      herkomst: "Engels; een wolk was het gebruikelijke symbool voor internet in netwerkschema's.",
      beeld: "Een computer die als wolk boven de stad hangt, waar iedereen met een draadje op kan inpluggen.",
      emoji: "☁️🔌",
      afleiders: [
        "Het draadloos met elkaar verbinden van apparaten in huis.",
        "Het koelen van servers met buitenlucht.",
        "Het verwerken van gegevens direct op het apparaat zelf.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "machine learning",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een vorm van kunstmatige intelligentie waarbij computers patronen leren uit voorbeelden, in plaats van dat elke regel wordt voorgeprogrammeerd.",
      voorbeeldzin: "Spamfilters gebruiken machine learning om nieuwe soorten ongewenste mail te herkennen.",
      herkomst: "Engels: machinaal leren.",
      beeld: "Een robot die na het bekijken van duizenden foto's zelf het verschil tussen katten en honden leert zien.",
      emoji: "🤖🐱",
      afleiders: [
        "Het automatiseren van fabrieksprocessen met robots.",
        "Het programmeren van een computer met vaste als-dan-regels.",
        "Het leren programmeren via online cursussen.",
      ],
    },
    {
      niveau: "gevorderd",
      woord: "tweefactorauthenticatie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een inlogmethode waarbij je naast je wachtwoord nog een tweede bewijs nodig hebt, zoals een code op je telefoon.",
      voorbeeldzin: "Zet tweefactorauthenticatie aan, zodat een gestolen wachtwoord alleen niet genoeg is.",
      herkomst: "Grieks authentikos (echt, betrouwbaar).",
      beeld: "Een voordeur met twee sloten: de sleutel zit in je zak, de code staat op je telefoon.",
      emoji: "🚪📱",
      afleiders: [
        "Het versleutelen van gegevens met twee verschillende sleutels.",
        "Het automatisch wijzigen van je wachtwoord na twee maanden.",
        "Met hetzelfde account op twee apparaten tegelijk ingelogd zijn.",
      ],
    },
    {
      niveau: "expert",
      woord: "blockchain",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een gedeeld, decentraal register waarin transacties in aan elkaar gekoppelde blokken worden vastgelegd die achteraf vrijwel niet te wijzigen zijn.",
      voorbeeldzin: "Bitcoin gebruikt een blockchain om alle transacties bij te houden.",
      herkomst: "Engels block (blok) + chain (ketting).",
      beeld: "Een ketting van glazen kluisjes waarin elk kluisje een afdruk van het vorige bevat, zodat knoeien meteen opvalt.",
      emoji: "⛓️📦",
      afleiders: [
        "Een centrale database die door één bank wordt beheerd.",
        "Een netwerk van computers dat samen één supercomputer vormt.",
        "Een beveiligingsmethode die schadelijke websites blokkeert.",
      ],
    },
    {
      niveau: "expert",
      woord: "containerisatie",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Het verpakken van software samen met alles wat ze nodig heeft, zodat ze op elke computer op dezelfde manier draait.",
      voorbeeldzin: "Dankzij containerisatie werkt de applicatie op de server precies zoals op de laptop van de ontwikkelaar.",
      herkomst: "Naar de zeecontainer, die goederenvervoer wereldwijd standaardiseerde.",
      beeld: "Een zeecontainer met een complete keuken erin, die je op elk schip kunt zetten en overal meteen kunt koken.",
      emoji: "🚢📦",
      afleiders: [
        "Het opdelen van een harde schijf in afzonderlijke partities.",
        "Het bundelen van meerdere servers tot één geheel.",
        "Het beperken van de toegang van apps tot persoonsgegevens.",
      ],
    },
    {
      niveau: "expert",
      woord: "zero-day",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een beveiligingslek in software dat nog niet bekend is bij de maker, zodat er nog geen oplossing voor bestaat.",
      voorbeeldzin: "Criminelen betalen soms grote bedragen voor een zero-day in een populaire browser.",
      herkomst: "Engels: de maker heeft 'nul dagen' gehad om het lek te dichten.",
      beeld: "Een inbreker die een geheime achterdeur vindt waarvan de bewoners niet eens weten dat die bestaat.",
      emoji: "🚪🕵️",
      afleiders: [
        "Een update die dezelfde dag nog bij alle gebruikers wordt geïnstalleerd.",
        "Een computervirus dat zichzelf na één dag vernietigt.",
        "De dag waarop een softwareversie niet meer wordt ondersteund.",
      ],
    },
    {
      niveau: "expert",
      woord: "technische schuld",
      woordsoort: "zelfstandig naamwoord",
      definitie: "De extra kosten en moeite die later ontstaan doordat je in software nu kiest voor een snelle maar minder goede oplossing.",
      voorbeeldzin: "Na jaren van haastwerk was de technische schuld zo groot dat elke kleine aanpassing weken kostte.",
      herkomst: "Vertaling van technical debt, een term van programmeur Ward Cunningham.",
      beeld: "Een stapel afwas die je steeds laat staan, tot je geen schoon bord meer hebt.",
      emoji: "🍽️📈",
      afleiders: [
        "Het bedrag dat een bedrijf nog moet betalen voor softwarelicenties.",
        "Het tekort aan technisch personeel op de arbeidsmarkt.",
        "De waardevermindering van computers door veroudering.",
      ],
    },
    {
      niveau: "expert",
      woord: "taalmodel",
      woordsoort: "zelfstandig naamwoord",
      definitie: "Een AI-model dat getraind is op grote hoeveelheden tekst en daardoor tekst kan voorspellen, begrijpen en genereren.",
      voorbeeldzin: "Moderne chatbots zijn gebaseerd op een groot taalmodel.",
      herkomst: "Vertaling van het Engelse language model.",
      beeld: "Een reusachtige bibliotheek met een stem die elke zin die je begint kan afmaken.",
      emoji: "📚🗣️",
      afleiders: [
        "Een woordenboek dat zichzelf automatisch bijwerkt.",
        "Een programma dat gesproken taal omzet in geschreven tekst.",
        "Een vertaalprogramma dat werkt met vaste grammaticaregels.",
      ],
    },
  ],
};

export const DOMEINEN = Object.keys(WOORDENBANK);

/** Een vast id per woord, zodat de app weet welke woorden je al kent. */
export function woordId(domein: string, woord: string): string {
  return `${domein}:${woord}`.toLowerCase();
}

const NIVEAU_VOLGORDE: Niveau[] = ["basis", "gevorderd", "expert"];

/**
 * Kies nieuwe woorden uit een vakgebied die je nog niet geleerd hebt.
 * Woorden op je eigen niveau gaan voor; zijn die op, dan volgen de dichtstbijzijnde niveaus.
 */
export function kiesNieuweWoorden(
  domein: string,
  niveau: Niveau,
  bekend: Set<string>,
  aantal: number,
  kans: () => number = Math.random,
): Woord[] {
  const eigen = NIVEAU_VOLGORDE.indexOf(niveau);
  const afstand = (w: BankWoord) => Math.abs(NIVEAU_VOLGORDE.indexOf(w.niveau) - eigen);

  return (WOORDENBANK[domein] ?? [])
    .map((w) => ({ ...w, id: woordId(domein, w.woord), domein, _toeval: kans() }))
    .filter((w) => !bekend.has(w.id))
    .sort((a, b) => afstand(a) - afstand(b) || a._toeval - b._toeval)
    .slice(0, aantal)
    .map(({ _toeval, ...w }) => w);
}

/** Hoeveel woorden er in een vakgebied nog over zijn. */
export function aantalOver(domein: string, bekend: Set<string>): number {
  return (WOORDENBANK[domein] ?? []).filter((w) => !bekend.has(woordId(domein, w.woord))).length;
}
